### ISSUE TITLE
Redis - Request failed with status code 401

### ISSUE THREAD

**Issue by ChrisProlls** [dapr/dapr#1378]
## Ask your question here

I was testing Dapr with a Typescript Azure Function. I just wanted a simple function that push a state into my Redis storage.
- Docker and Azure Core Tools are installed
- I launched `dapr init`
- The code is here : https://github.com/ChrisProlls/Dapr-demo

The important code is here :
```ts
const urlState = `http://localhost:3500/v1.0/state/${stateKey}`;

const httpTrigger: AzureFunction = async function (context: Context, req: HttpRequest): Promise<void> {
    context.log('HTTP trigger function processed a request.');

    let { data } = await axios.default.get<number>(urlState)

    if(!data) {
        data = 0;
    } else {
        data++;
    }

    // const data = 5;

    console.log(`value : ${data}`);

    await axios.default.post<number>(urlState, data)

    console.log(`value persisted`);
};

```
After launching `dapr run --port 3500 --app-id ts-function --app-port 7071 func start`, I can see Dapr and my function running successfully. With this URL, I can see that my function is successfully reached : `GET http://localhost:3500/v1.0/invoke/ts-function/method/updatestate`, but Redis returned an error when I tried to get or post my state
![image](https://user-images.githubusercontent.com/1511666/78714964-fda95680-791c-11ea-86a8-d2195654c45d.png)

I have missed something ?
NB : I use the Redis config file in `components` folder from `dapr run` command, so no specific local Redis instance

**Comment by yaron2** [comment]
Do you see anything from the Dapr logs? can you paste the entire log output here?

**Comment by yaron2** [comment]
Also, please add the `--log-level debug` param to `dapr run`.

**Comment by ChrisProlls** [comment]
Here are the logs

```
== DAPR == time="2020-04-08T18:11:38.463055+02:00" level=info msg="starting Dapr Runtime -- version 0.5.1 -- commit v0.3.0-rc.0-160-g514f806-dirty" app_id=ts-function instance=DESKTOP-VPMK0NH scope=dapr.runtime type=log ver=0.5.1
== DAPR == time="2020-04-08T18:11:38.463055+02:00" level=info msg="log level set to: debug" app_id=ts-function instance=DESKTOP-VPMK0NH scope=dapr.runtime type=log ver=0.5.1
== DAPR == time="2020-04-08T18:11:38.4641715+02:00" level=info msg="metrics server started on :64982/" app_id=ts-function instance=DESKTOP-VPMK0NH scope=dapr.metrics type=log ver=0.5.1
== DAPR == time="2020-04-08T18:11:38.4641715+02:00" level=info msg="standalone mode configured" app_id=ts-function instance=DESKTOP-VPMK0NH scope=dapr.runtime type=log ver=0.5.1
== DAPR == time="2020-04-08T18:11:38.4641715+02:00" level=info msg="dapr id: ts-function" app_id=ts-function instance=DESKTOP-VPMK0NH scope=dapr.runtime type=log ver=0.5.1
== DAPR == time="2020-04-08T18:11:38.4641715+02:00" level=info msg="mTLS is disabled. Skipping certificate request and tls validation" app_id=ts-function instance=DESKTOP-VPMK0NH scope=dapr.runtime type=log ver=0.5.1
== DAPR == time="2020-04-08T18:11:38.46801+02:00" level=info msg="found component statestore (state.redis)" app_id=ts-function instance=DESKTOP-VPMK0NH scope=dapr.runtime type=log ver=0.5.1
== DAPR == time="2020-04-08T18:11:38.46801+02:00" level=info msg="found component messagebus (pubsub.redis)" app_id=ts-function instance=DESKTOP-VPMK0NH scope=dapr.runtime type=log ver=0.5.1
== DAPR == time="2020-04-08T18:11:38.46801+02:00" level=info msg="application protocol: http. waiting on port 7071" app_id=ts-function instance=DESKTOP-VPMK0NH scope=dapr.runtime type=log ver=0.5.1
== APP ==
== APP ==                   %%%%%%
== APP ==                  %%%%%%
== APP ==             @   %%%%%%    @
== APP ==           @@   %%%%%%      @@
== APP ==        @@@    %%%%%%%%%%%    @@@
== APP ==      @@      %%%%%%%%%%        @@
== APP ==        @@         %%%%       @@
== APP ==          @@      %%%       @@
== APP ==            @@    %%      @@
== APP ==                 %%
== APP ==                 %
== APP ==
== APP == Azure Functions Core Tools (3.0.2245 Commit hash: 1d094e2f3ef79b9a478a1621ea7ec3f93ac1910d)
== APP == Function Runtime Version: 3.0.13139.0
== APP == [4/8/2020 4:11:43 PM] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language:java
== APP == [4/8/2020 4:11:43 PM] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language:powershell
== APP == [4/8/2020 4:11:43 PM] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language:python
== APP == [4/8/2020 4:11:43 PM] Building host: startup suppressed: 'False', configuration suppressed: 'False', startup operation id: 'd4d4cd70-0aa1-4d10-853d-2b9600edd1cc'
== APP == [4/8/2020 4:11:43 PM] Reading host configuration file 'C:\Users\chris\Documents\_Git\dapr-demo\src\function\host.json'
== APP == [4/8/2020 4:11:43 PM] Host configuration file read:
== APP == [4/8/2020 4:11:43 PM] {
== APP == [4/8/2020 4:11:43 PM]   "version": "2.0",
== APP == [4/8/2020 4:11:43 PM]   "extensionBundle": {
== APP == [4/8/2020 4:11:43 PM]     "id": "Microsoft.Azure.Functions.ExtensionBundle",
== APP == [4/8/2020 4:11:43 PM]     "version": "[1.*, 2.0.0)"
== APP == [4/8/2020 4:11:43 PM]   }
== APP == [4/8/2020 4:11:43 PM] }
== APP == [4/8/2020 4:11:43 PM] Reading functions metadata
== APP == [4/8/2020 4:11:43 PM] 1 functions found
== APP == [4/8/2020 4:11:43 PM] Looking for extension bundle Microsoft.Azure.Functions.ExtensionBundle at C:\Users\chris\AppData\Local\Temp\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle
== APP == [4/8/2020 4:11:43 PM] Found a matching extension bundle at C:\Users\chris\AppData\Local\Temp\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle\1.1.1
== APP == [4/8/2020 4:11:43 PM] Fetching information on versions of extension bundle Microsoft.Azure.Functions.ExtensionBundle available on https://functionscdn.azureedge.net/public/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/index.json
== APP == [4/8/2020 4:11:44 PM] Skipping bundle download since it already exists at path C:\Users\chris\AppData\Local\Temp\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle\1.1.1
== APP == [4/8/2020 4:11:44 PM] Loading Extention bundle from C:\Users\chris\AppData\Local\Temp\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle\1.1.1
== APP == [4/8/2020 4:11:44 PM] Initializing Warmup Extension.
== APP == [4/8/2020 4:11:44 PM] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language:java
== APP == [4/8/2020 4:11:44 PM] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language:powershell
== APP == [4/8/2020 4:11:44 PM] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language:python
== APP == [4/8/2020 4:11:44 PM] Initializing Host. OperationId: 'd4d4cd70-0aa1-4d10-853d-2b9600edd1cc'.
== APP == [4/8/2020 4:11:44 PM] Host initialization: ConsecutiveErrors=0, StartupCount=1, OperationId=d4d4cd70-0aa1-4d10-853d-2b9600edd1cc
== APP == [4/8/2020 4:11:44 PM] LoggerFilterOptions
== APP == [4/8/2020 4:11:44 PM] {
== APP == [4/8/2020 4:11:44 PM]   "MinLevel": "None",
== APP == [4/8/2020 4:11:44 PM]   "Rules": [
== APP == [4/8/2020 4:11:44 PM]     {
== APP == [4/8/2020 4:11:44 PM]       "ProviderName": null,
== APP == [4/8/2020 4:11:44 PM]       "CategoryName": null,
== APP == [4/8/2020 4:11:44 PM]       "LogLevel": null,
== APP == [4/8/2020 4:11:44 PM]       "Filter": "<AddFilter>b__0"
== APP == [4/8/2020 4:11:44 PM]     },
== APP == [4/8/2020 4:11:44 PM]     {
== APP == [4/8/2020 4:11:44 PM]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
== APP == [4/8/2020 4:11:44 PM]       "CategoryName": null,
== APP == [4/8/2020 4:11:44 PM]       "LogLevel": "None",
== APP == [4/8/2020 4:11:44 PM]       "Filter": null
== APP == [4/8/2020 4:11:44 PM]     },
== APP == [4/8/2020 4:11:44 PM]     {
== APP == [4/8/2020 4:11:44 PM]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
== APP == [4/8/2020 4:11:44 PM]       "CategoryName": null,
== APP == [4/8/2020 4:11:44 PM]       "LogLevel": null,
== APP == [4/8/2020 4:11:44 PM]       "Filter": "<AddFilter>b__0"
== APP == [4/8/2020 4:11:44 PM]     }
== APP == [4/8/2020 4:11:44 PM]   ]
== APP == [4/8/2020 4:11:44 PM] }
== APP == [4/8/2020 4:11:44 PM] FunctionResultAggregatorOptions
== APP == [4/8/2020 4:11:44 PM] {
== APP == [4/8/2020 4:11:44 PM]   "BatchSize": 1000,
== APP == [4/8/2020 4:11:44 PM]   "FlushTimeout": "00:00:30",
== APP == [4/8/2020 4:11:44 PM]   "IsEnabled": true
== APP == [4/8/2020 4:11:44 PM] }
== APP == [4/8/2020 4:11:44 PM] SingletonOptions
== APP == [4/8/2020 4:11:44 PM] {
== APP == [4/8/2020 4:11:44 PM]   "LockPeriod": "00:00:15",
== APP == [4/8/2020 4:11:44 PM]   "ListenerLockPeriod": "00:00:15",
== APP == [4/8/2020 4:11:44 PM]   "LockAcquisitionTimeout": "10675199.02:48:05.4775807",
== APP == [4/8/2020 4:11:44 PM]   "LockAcquisitionPollingInterval": "00:00:05",
== APP == [4/8/2020 4:11:44 PM]   "ListenerLockRecoveryPollingInterval": "00:01:00"
== APP == [4/8/2020 4:11:44 PM] }
== APP == [4/8/2020 4:11:44 PM] HttpOptions
== APP == [4/8/2020 4:11:44 PM] {
== APP == [4/8/2020 4:11:44 PM]   "DynamicThrottlesEnabled": false,
== APP == [4/8/2020 4:11:44 PM]   "MaxConcurrentRequests": -1,
== APP == [4/8/2020 4:11:44 PM]   "MaxOutstandingRequests": -1,
== APP == [4/8/2020 4:11:44 PM]   "RoutePrefix": ""
== APP == [4/8/2020 4:11:44 PM] }
== APP == [4/8/2020 4:11:44 PM] Starting JobHost
== APP == [4/8/2020 4:11:44 PM] Starting Host (HostId=desktopvpmk0nh-1378314681, InstanceId=cc5e1b6f-de8f-47fe-8969-eeeec133d961, Version=3.0.13139.0, ProcessId=15988, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=(null))
== APP == [4/8/2020 4:11:44 PM] Loading functions metadata
== APP == [4/8/2020 4:11:44 PM] 1 functions loaded
== APP == [4/8/2020 4:11:44 PM] Loading proxies metadata
== APP == [4/8/2020 4:11:44 PM] Initializing Azure Function proxies
== APP == [4/8/2020 4:11:45 PM] 0 proxies loaded
== APP == [4/8/2020 4:11:45 PM] Starting worker process:node  "C:\Users\chris\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\dist/src/nodejsWorker.js" --host 127.0.0.1 --port 65006 --workerId de65e0e7-5383-42b6-a5ec-b74dd7195182 --requestIdf5a301e8-e235-48b8-9b9e-7e2f35e924e1 --grpcMaxMessageLength 134217728
== APP == [4/8/2020 4:11:45 PM] node process with Id=17308 started
== APP == [4/8/2020 4:11:45 PM] Generating 1 job function(s)
== APP == [4/8/2020 4:11:45 PM] Found the following functions:
== APP == [4/8/2020 4:11:45 PM] Host.Functions.UpdateState
== APP == [4/8/2020 4:11:45 PM]
== APP == [4/8/2020 4:11:45 PM] Initializing function HTTP routes
== APP == [4/8/2020 4:11:45 PM] Mapped function route '/UpdateState' [get,post] to 'UpdateState'
== APP == [4/8/2020 4:11:45 PM]
== APP == [4/8/2020 4:11:45 PM] Host initialized (847ms)
== APP == [4/8/2020 4:11:45 PM] Host started (860ms)
== APP == [4/8/2020 4:11:45 PM] Job host started
== APP == Hosting environment: Production
== APP == Content root path: C:\Users\chris\Documents\_Git\dapr-demo\src\function
== APP == Now listening on: http://0.0.0.0:7071
== APP == Application started. Press Ctrl+C to shut down.
== APP ==
== APP == Http Functions:
== APP ==
== APP ==       UpdateState: [GET,POST] http://localhost:7071/UpdateState
== APP ==
== DAPR == time="2020-04-08T18:11:45.9402009+02:00" level=info msg="application discovered on port 7071" app_id=ts-function instance=DESKTOP-VPMK0NH scope=dapr.runtime type=log ver=0.5.1
== APP == [4/8/2020 4:11:46 PM] Worker de65e0e7-5383-42b6-a5ec-b74dd7195182 connecting on 127.0.0.1:65006
== APP == [4/8/2020 4:11:46 PM] Executing HTTP request: {
== APP == [4/8/2020 4:11:46 PM]   "requestId": "bc5714d4-96f6-4a4a-b668-1a5751daefdd",
== APP == [4/8/2020 4:11:46 PM]   "method": "GET",
== APP == [4/8/2020 4:11:46 PM]   "uri": "/dapr/config"
== APP == [4/8/2020 4:11:46 PM] }
== APP == [4/8/2020 4:11:46 PM] Executed HTTP request: {
== APP == [4/8/2020 4:11:46 PM]   "requestId": "bc5714d4-96f6-4a4a-b668-1a5751daefdd",
== APP == [4/8/2020 4:11:46 PM]   "method": "GET",
== APP == [4/8/2020 4:11:46 PM]   "uri": "/dapr/config",
== APP == [4/8/2020 4:11:46 PM]   "identities": [],
== APP == [4/8/2020 4:11:46 PM]   "status": 404,
== APP == [4/8/2020 4:11:46 PM]   "duration": 189
== APP == [4/8/2020 4:11:46 PM] }
== DAPR == 2020-04-08 18:11:46.240122 I | redis: connecting to localhost:6379
== DAPR == 2020-04-08 18:11:46.245124 I | redis: connected to localhost:6379 (localAddr: [::1]:65026, remAddr: [::1]:6379)
== APP == [4/8/2020 4:11:46 PM] Executing HTTP request: {
== APP == [4/8/2020 4:11:46 PM]   "requestId": "b7fbc0b1-83d2-4ec4-8e79-01dc8022233c",
== APP == [4/8/2020 4:11:46 PM]   "method": "GET",
== APP == [4/8/2020 4:11:46 PM]   "uri": "/dapr/subscribe"
== APP == [4/8/2020 4:11:46 PM] }
== APP == [4/8/2020 4:11:46 PM] Executed HTTP request: {
== APP == [4/8/2020 4:11:46 PM]   "requestId": "b7fbc0b1-83d2-4ec4-8e79-01dc8022233c",
== APP == [4/8/2020 4:11:46 PM]   "method": "GET",
== APP == [4/8/2020 4:11:46 PM]   "uri": "/dapr/subscribe",
== APP == [4/8/2020 4:11:46 PM]   "identities": [],
== APP == [4/8/2020 4:11:46 PM]   "status": 404,
== APP == [4/8/2020 4:11:46 PM]   "duration": 2
== APP == [4/8/2020 4:11:46 PM] }
== DAPR == time="2020-04-08T18:11:46.2952538+02:00" level=info msg="App is subscribed to the following topics: []" app_id=ts-function instance=DESKTOP-VPMK0NH scope=dapr.runtime type=log ver=0.5.1
== DAPR == time="2020-04-08T18:11:46.2952538+02:00" level=info msg="Initialized service discovery to standalone" app_id=ts-function instance=DESKTOP-VPMK0NH scope=dapr.runtime type=log ver=0.5.1
== DAPR == time="2020-04-08T18:11:46.2952538+02:00" level=info msg="actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s" app_id=ts-function instance=DESKTOP-VPMK0NH scope=dapr.runtime.actor type=log ver=0.5.1
== DAPR == time="2020-04-08T18:11:46.2952538+02:00" level=info msg="starting connection attempt to placement service at localhost:6050" app_id=ts-function instance=DESKTOP-VPMK0NH scope=dapr.runtime.actor type=log ver=0.5.1
== DAPR == time="2020-04-08T18:11:46.2962488+02:00" level=info msg="enabled metrics grpc middleware" app_id=ts-function instance=DESKTOP-VPMK0NH scope=dapr.runtime.grpc type=log ver=0.5.1
== DAPR == time="2020-04-08T18:11:46.2962488+02:00" level=info msg="gRPC server is running on port 64981" app_id=ts-function instance=DESKTOP-VPMK0NH scope=dapr.runtime type=log ver=0.5.1
== DAPR == time="2020-04-08T18:11:46.2962488+02:00" level=info msg="enabled cors http middleware" app_id=ts-function instance=DESKTOP-VPMK0NH scope=dapr.runtime.http type=log ver=0.5.1
== DAPR == time="2020-04-08T18:11:46.2962488+02:00" level=info msg="enabled proxy http middleware" app_id=ts-function instance=DESKTOP-VPMK0NH scope=dapr.runtime.http type=log ver=0.5.1
== DAPR == time="2020-04-08T18:11:46.2962488+02:00" level=info msg="enabled metrics http middleware" app_id=ts-function instance=DESKTOP-VPMK0NH scope=dapr.runtime.http type=log ver=0.5.1
== DAPR == time="2020-04-08T18:11:46.2972503+02:00" level=info msg="http server is running on port 3500" app_id=ts-function instance=DESKTOP-VPMK0NH scope=dapr.runtime type=log ver=0.5.1
== DAPR == time="2020-04-08T18:11:46.2972503+02:00" level=info msg="local service entry announced" app_id=ts-function instance=DESKTOP-VPMK0NH scope=dapr.runtime type=log ver=0.5.1
== DAPR == time="2020-04-08T18:11:46.2972503+02:00" level=info msg="dapr initialized. Status: Running. Init Elapsed 7833.0788ms" app_id=ts-function instance=DESKTOP-VPMK0NH scope=dapr.runtime type=log ver=0.5.1
== DAPR == time="2020-04-08T18:11:46.2992497+02:00" level=info msg="established connection to placement service at localhost:6050" app_id=ts-function instance=DESKTOP-VPMK0NH scope=dapr.runtime.actor type=log ver=0.5.1
== DAPR == time="2020-04-08T18:11:46.3053072+02:00" level=info msg="placement order received: lock" app_id=ts-function instance=DESKTOP-VPMK0NH scope=dapr.runtime.actor type=log ver=0.5.1
== DAPR == time="2020-04-08T18:11:46.3053072+02:00" level=info msg="placement order received: update" app_id=ts-function instance=DESKTOP-VPMK0NH scope=dapr.runtime.actor type=log ver=0.5.1
== DAPR == time="2020-04-08T18:11:46.3053072+02:00" level=info msg="actors: placement tables updated" app_id=ts-function instance=DESKTOP-VPMK0NH scope=dapr.runtime.actor type=log ver=0.5.1
== DAPR == time="2020-04-08T18:11:46.3053072+02:00" level=info msg="placement order received: unlock" app_id=ts-function instance=DESKTOP-VPMK0NH scope=dapr.runtime.actor type=log ver=0.5.1
Updating metadata for app command: func start
You're up and running! Both Dapr and your app logs will appear here.
== APP == [4/8/2020 4:11:50 PM] Host lock lease acquired by instance ID '000000000000000000000000C098B34A'.
== APP == [4/8/2020 4:11:58 PM] Executing HTTP request: {
== APP == [4/8/2020 4:11:58 PM]   "requestId": "12833d20-2b89-4447-b675-724b8794106b",
== APP == [4/8/2020 4:11:58 PM]   "method": "GET",
== APP == [4/8/2020 4:11:58 PM]   "uri": "/updatestate"
== APP == [4/8/2020 4:11:58 PM] }
== APP == [4/8/2020 4:11:58 PM] Executing 'Functions.UpdateState' (Reason='This function was programmatically called via the host APIs.', Id=f16ad3e8-0e8f-4902-88ca-a1eb2ac19f65)
== APP == [4/8/2020 4:11:58 PM] HTTP trigger function processed a request.
== APP == [4/8/2020 4:11:58 PM] Executed 'Functions.UpdateState' (Failed, Id=f16ad3e8-0e8f-4902-88ca-a1eb2ac19f65)
== APP == [4/8/2020 4:11:58 PM] System.Private.CoreLib: Exception while executing function: Functions.UpdateState. System.Private.CoreLib: Result: Failure
== APP == Exception: Error: Request failed with status code 401
== APP == Stack: Error: Request failed with status code 401
== APP ==     at createError (C:\Users\chris\Documents\_Git\dapr-demo\src\function\node_modules\axios\lib\core\createError.js:16:15)
== APP ==     at settle (C:\Users\chris\Documents\_Git\dapr-demo\src\function\node_modules\axios\lib\core\settle.js:17:12)
== APP ==     at IncomingMessage.handleStreamEnd (C:\Users\chris\Documents\_Git\dapr-demo\src\function\node_modules\axios\lib\adapters\http.js:236:11)
== APP ==     at IncomingMessage.emit (events.js:187:15)
== APP ==     at endReadableNT (_stream_readable.js:1094:12)
== APP ==     at process._tickCallback (internal/process/next_tick.js:63:19).
== APP == [4/8/2020 4:11:58 PM] Executed HTTP request: {
== APP == [4/8/2020 4:11:58 PM]   "requestId": "12833d20-2b89-4447-b675-724b8794106b",
== APP == [4/8/2020 4:11:58 PM]   "method": "GET",
== APP == [4/8/2020 4:11:58 PM]   "uri": "/updatestate",
== APP == [4/8/2020 4:11:58 PM]   "identities": [
== APP == [4/8/2020 4:11:58 PM]     {
== APP == [4/8/2020 4:11:58 PM]       "type": "WebJobsAuthLevel",
== APP == [4/8/2020 4:11:58 PM]       "level": "Admin"
== APP == [4/8/2020 4:11:58 PM]     }
== APP == [4/8/2020 4:11:58 PM]   ],
== APP == [4/8/2020 4:11:58 PM]   "status": 500,
== APP == [4/8/2020 4:11:58 PM]   "duration": 437
== APP == [4/8/2020 4:11:58 PM] }
```

**Comment by msfussell** [comment]
@yaron2

**Comment by yaron2** [comment]
Hey @ChrisProlls, can you paste your redis.yaml component here?

**Comment by ChrisProlls** [comment]
Here is the `statestore.yaml` generated by `dapr run`

````yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"

````

**Comment by yaron2** [comment]
Hey @ChrisProlls, I ran your code and got it to work.
You were missing a few things with the API.

First, the state url required the state store name as a part of the path, as Dapr allows an app to target multiple state stores.

So this:

```ts
const urlState = `http://localhost:3500/v1.0/state/${stateKey}`;
````

Becomes this:

```ts
const urlState = `http://localhost:3500/v1.0/state/statestore/${stateKey}`;
````

`statestore` is the name of the Redis component above. 

Also, for saving state, the API is different.
I've created a simplified code snippet based on yours:

```ts
const stateKey = "stateCounter";
const urlState = `http://localhost:3500/v1.0/state/statestore`;

setTimeout(function () {
    axios.default.get<number>(urlState + `/${stateKey}`).then(v => {
        let data = v.data;
        console.log(data);

        data++;

        console.log(`value : ${data}`);

        let stateRequest = [
            {
                key: stateKey,
                value: data
            }
        ]

        axios.default.post<number>(urlState, stateRequest).then(v => {
            console.log(v.statusText);
            console.log(v.status.toString());
        })
    });

}, 2000);
```

**Comment by ChrisProlls** [comment]
Understood ! This worked, thanks :)
