### ISSUE TITLE
io.grpc.StatusRuntimeException: unknown service dapr.Dapr after updating to 0.7.0

### ISSUE THREAD

**Issue by javageek79** [dapr/dapr#1550]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?

> 0.7.x

## Expected Behavior

no exception

## Actual Behavior

After updating our k8s cluster to Version 0.7.0 we are facing `java.util.concurrent.ExecutionException` in our logs. Both node and java applications are affected.
java:
`java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service dapr.Dapr
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:552)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:533)
	at io.dapr.client.DaprClientGrpc.lambda$publishEvent$0(DaprClientGrpc.java:91)
	at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:56)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4210)
	at reactor.core.publisher.Mono.subscribeWith(Mono.java:4316)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4182)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4118)
	at `
node: 
`Error publishing dapr event: Error: 12 UNIMPLEMENTED: unknown service dapr.Dapr`

**Comment by artursouza** [comment]
Which version of the Java SDK are you using?

**Comment by javageek79** [comment]
node: 0.3.0-preview01
java: 0.4.0
Does 0.7.0 causes incomaptibilities with those versions?

**Comment by artursouza** [comment]
Absolutely.  Please, upgrade the SDKs to the latest version.

— Artur Souza
________________________________

**Comment by youngbupark** [comment]
@javageek79 is your problem resolved?

**Comment by javageek79** [comment]
yes

**Comment by youngbupark** [comment]
> yes

Cool. I will close this.
