### ISSUE TITLE
GetStarted example failing "UNIMPLEMENTED: unknown service dapr.proto.runtime.v1.Dapr"

### ISSUE THREAD

**Issue by moderakh** [dapr/dapr#1635]
I started with Dapr getStarted example 
https://github.com/dapr/java-sdk/tree/master/examples/src/main/java/io/dapr/examples/invoke/http

## What version of Dapr?

installed latest version of dapr from homebrew
```bash
dapr --version
CLI version: 0.7.0
Runtime version: 0.7.1
```

java version
```bash
java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)
```

docker version
```bash
docker --version
Docker version 19.03.8, build afacb8b
```
## Expected Behavior
the example https://github.com/dapr/java-sdk/tree/master/examples/src/main/java/io/dapr/examples/invoke/http
should work

## Actual Behavior
after this starts
```bash
dapr run --app-id invokedemo --app-port 3000 --port 3005 -- java -jar examples/target/dapr-java-sdk-examples-exec.jar io.dapr.examples.invoke.http.DemoService -p 3000
```

running of the client fails:
```bash
dapr run --port 3006 -- java -jar examples/target/dapr-java-sdk-examples-exec.jar io.dapr.examples.invoke.http.InvokeClient 'message one' 'message two'
```

error msg
```bash
Updating metadata for app command: java -jar examples/target/dapr-java-sdk-examples-exec.jar io.dapr.examples.invoke.http.InvokeClient message one message two
✅  You're up and running! Both Dapr and your app logs will appear here.

== APP == Exception in thread "main" java.lang.reflect.InvocationTargetException

== APP == 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

== APP == 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

== APP == 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

== APP == 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)

== APP == 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)

== APP == 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)

== APP == 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)

== APP == 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)

== APP == Caused by: java.lang.reflect.InvocationTargetException

== APP == 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

== APP == 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

== APP == 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

== APP == 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)

== APP == 	at io.dapr.springboot.DaprMainApplication.main(DaprMainApplication.java:29)

== APP == 	... 8 more

== APP == Caused by: reactor.core.Exceptions$ReactiveException: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service dapr.proto.runtime.v1.Dapr

== APP == 	at reactor.core.Exceptions.propagate(Exceptions.java:366)

== APP == 	at reactor.core.publisher.MonoCallable.block(MonoCallable.java:84)

== APP == 	at reactor.core.publisher.MonoCallable.block(MonoCallable.java:74)

== APP == 	at io.dapr.examples.invoke.http.InvokeClient.main(InvokeClient.java:35)

== APP == 	... 13 more

== APP == Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service dapr.proto.runtime.v1.Dapr

== APP == 	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:552)

== APP == 	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:533)

== APP == 	at io.dapr.client.DaprClientGrpc.lambda$invokeService$1(DaprClientGrpc.java:149)

== APP == 	at reactor.core.publisher.MonoCallable.block(MonoCallable.java:81)

== APP == 	... 15 more

== APP == Caused by: io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service dapr.proto.runtime.v1.Dapr

== APP == 	at io.grpc.Status.asRuntimeException(Status.java:533)

== APP == 	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:495)

== APP == 	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)

== APP == 	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)

== APP == 	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)

== APP == 	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)

== APP == 	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)

== APP == 	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)

== APP == 	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)

== APP == 	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)

== APP == 	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510)

== APP == 	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66)

== APP == 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630)

== APP == 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518)

== APP == 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:692)

== APP == 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:681)

== APP == 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)

== APP == 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)

== APP == 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

== APP == 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

== APP == 	at java.base/java.lang.Thread.run(Thread.java:834)
````

**Comment by yaron2** [comment]
The master branch of the Java SDK is targeting the master branch of Dapr.

Can you try with the latest stable release of the Java SDK?

https://github.com/dapr/java-sdk/tree/release-0.5

**Comment by yaron2** [comment]
Closing for now. Retry with 0.8.0 and re-open if this happens again. Thanks!
