### ISSUE TITLE
gRPC & HTTP Socket Timeout

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/dapr#1639]
## In what area(s)?

> /area runtime

## What version of Dapr?

> 0.7.0 CLI & 0.7.1 Runtime

## Expected Behavior

No Socket Timeout to appear.

## Actual Behavior

gRPC and HTTP are giving "Socket Closed" after a while of interacting with it in High Performance use-case. Initial start-up is working fine, error occurs while running.

**gRPC Logs:**

```bash
Traceback (most recent call last):
  File "main.py", line 110, in <module>
    solver.run()
  File "main.py", line 68, in run
    current_state = self.discretize(self.env.Reset())
  File "/app/Client.py", line 50, in Reset
    res = self.DaprInvoke("reset", req, roadwork_messages.ResetResponse)
  File "/app/Client.py", line 32, in DaprInvoke
    res = self.client.InvokeService(envelope)
  File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "Socket closed"
        debug_error_string = "{"created":"@1591193163.315580000","description":"Error received from peer ipv4:127.0.0.1:50001","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}"
```

**HTTP:**

```bash
==================================================
DAPR_PORT_GRPC: 50001; DAPR_PORT_HTTP: 3500
==================================================
Action Space (Name= Discrete; N=2)
[Episode 0] - Mean survival time over last 100 episodes was 28.0 ticks.
[Episode 10] - Mean survival time over last 100 episodes was 21.272727272727273 ticks.
[Episode 20] - Mean survival time over last 100 episodes was 21.047619047619047 ticks.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1332, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 272, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1332, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 272, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 111, in <module>
    solver.run()
  File "main.py", line 80, in run
    stepResponse = self.env.Step(action)
  File "/app/Client.py", line 50, in Step
    res = requests.post(f"{self.url}/method/{self.instanceId}/step", json=msg)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

## Steps to Reproduce the Problem

Not entirely sure, but this is happening at: https://github.com/thebillkidy/Roadwork-RL after startup (gRPC example):

```bash
cd src/

**Server**
./Scripts/windows/build.ps1 ./Servers/OpenAI/ rw-server-openai
./Scripts/windows/start-server.ps1 ./Servers/OpenAI/ rw-server-openai

**Client**
./Scripts/windows/build.ps1 ./Clients/python/experiments/cartpole/ rw-client-python-cartpole
./Scripts/windows/start-client.ps1 ./Clients/python/experiments/cartpole/ rw-client-python-cartpole
```

**Comment by youngbupark** [comment]
Thanks for the report. @thebillkidy do you know max RPS for this scenario ?

**Comment by thebillkidy** [comment]
What would be the preferred way for measuring RPS? (gRPC and HTTP scenarios)

Note: this is also happening through HTTP:

```bash
==================================================
DAPR_PORT_GRPC: 50001; DAPR_PORT_HTTP: 3500
==================================================
Action Space (Name= Discrete; N=2)
[Episode 0] - Mean survival time over last 100 episodes was 28.0 ticks.
[Episode 10] - Mean survival time over last 100 episodes was 21.272727272727273 ticks.
[Episode 20] - Mean survival time over last 100 episodes was 21.047619047619047 ticks.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1332, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 272, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1332, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 272, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 111, in <module>
    solver.run()
  File "main.py", line 80, in run
    stepResponse = self.env.Step(action)
  File "/app/Client.py", line 50, in Step
    res = requests.post(f"{self.url}/method/{self.instanceId}/step", json=msg)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by youngbupark** [comment]
@XavierGeerinck Have you run your applications on K8s cluster? can you see the same issue?

**Comment by XavierGeerinck** [comment]
@youngbupark these are both running on the K8S cluster installation :) since there is the other bug in the normal one preventing good performance

**Comment by youngbupark** [comment]
Please try with the latest build.

For selfhost mode, you can download binaries from
https://github.com/dapr/dapr/actions/runs/137600612
Then replace daprd in /usr/local/bin/ with the new downloaded binary.

For Kubernetes mode, use helm.
```
helm install dapr dapr/dapr -n dapr-system --set-string global.tag=edge
```

**Comment by youngbupark** [comment]
@XavierGeerinck any updates? do you still see the problem ?

**Comment by XavierGeerinck** [comment]
Hi @youngbupark my apologies for the late answer! Currently I am not seeing this issue anymore so I guess this is solved :) thanks a lot for this!

**Comment by youngbupark** [comment]
Closed by https://github.com/dapr/dapr/pull/1692
