### ISSUE TITLE
Sidecar GRPC endpoint not immediately ready for app

### ISSUE THREAD

**Issue by artursouza** [dapr/dapr#1933]
## In what area(s)?

 /area runtime

## What version of Dapr?

0.9

## Expected Behavior

App can connect to Dapr sidecar via GRPC right away since Dapr waits for its GRPC and HTTP endpoint to be up before starting the app.

## Actual Behavior

App needs to wait for a few seconds before Dapr's sidecar is ready on GRPC port.

## Steps to Reproduce the Problem

This Java SDK example can repro the issue when the client app is invoked:

https://github.com/dapr/java-sdk/tree/release-0.7/examples/src/main/java/io/dapr/examples/invoke/http

```
←[94;1m== APP == Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:59551
←[0m
←[94;1m== APP == Caused by: java.net.ConnectException: Connection refused: no further information
←[0m
←[94;1m== APP ==        at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
←[0m
←[94;1m== APP ==        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)
←[0m
←[94;1m== APP ==        at io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
←[0m
←[94;1m== APP ==        at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
```

**Comment by artursouza** [comment]
BTW, this issue can also be reproduced with unreleased version 0.10 (master).

**Comment by yaron2** [comment]
The expected behavior though cannot be achieved, if the app starts and tries to connect to Dapr before Dapr opens it's gRPC server, you will get this error

**Comment by artursouza** [comment]
I wonder if Dapr sidecar should/could wait for its GRPC and HTTP endpoint to be up before starting the app.

**Comment by yaron2** [comment]
> I wonder if Dapr sidecar should/could wait for its GRPC and HTTP endpoint to be up before starting the app.

That would be the Dapr CLI, as the sidecar itself doesn't start the app.

daprd has a health endpoint that returns 200 ok when it's fully initialized.

**Comment by artursouza** [comment]
So should the Dapr cli wait for Dapr sidecar to be up before starting the app? Another question is: should SDKs offer a `wait()` API for use cases when client needs to wait to make sure Dapr sidecar is up on start up? In the worst case scenario, we can have this `wait()` method on all our examples to make sure they are re-playable.

**Comment by yaron2** [comment]
> So should the Dapr cli wait for Dapr sidecar to be up before starting the app? Another question is: should SDKs offer a `wait()` API for use cases when client needs to wait to make sure Dapr sidecar is up on start up? In the worst case scenario, we can have this `wait()` method on all our examples to make sure they are re-playable.

That's a good idea.

**Comment by artursouza** [comment]
What is the "good idea"? The cli to wait or the SDK to wait?

**Comment by yaron2** [comment]
> What is the "good idea"? The cli to wait or the SDK to wait?

Both the CLI and SDKs should wait for the `daprd` health checks to pass before launching the app and issuing API calls, respectively.

**Comment by artursouza** [comment]
OK. I am working on it.

**Comment by artursouza** [comment]
It is not possible to wait for sidecar before starting app, **unless** app does not listen to port. Today, starting sidecar depends on app being up and running to get actors and topics configuration. In anyway, I have a PR adding this feature to the cli, which will make our demos more stable since publishing/invoking apps will only run after the sidecar is up.
