### ISSUE TITLE
Install Dapr to an arm64 Kubernetes cluster(k3s v1.19.3) using the Dapr CLI(v1.0.0-rc.3) failed, all pods pending.

### ISSUE THREAD

**Issue by F-Sidney** [dapr/dapr#2605]
## Expected Behavior

Install Dapr to an arm64 Kubernetes cluster(k3s v1.19.3) using the Dapr CLI(v1.0.0-rc.3) should works.

## Actual Behavior

After init, the Dapr status -k output error messages, 
and Dapr pods are all pending, with message: "0/3 nodes are available: 3 node(s) didn't match node selector."

```shell
[root@k3s-master ~]# ./dapr status -k
panic: runtime error: index out of range [0] with length 0

goroutine 15 [running]:
github.com/dapr/cli/pkg/kubernetes.(*StatusClient).Status.func1(0x400046fb90, 0x16e13a0, 0x40006b1760, 0x400046fb88, 0x40004458a0, 0x14747a6, 0x15)
        /home/runner/work/cli/cli/pkg/kubernetes/status.go:98 +0x74c
created by github.com/dapr/cli/pkg/kubernetes.(*StatusClient).Status
        /home/runner/work/cli/cli/pkg/kubernetes/status.go:70 +0x130
```
```shell
[root@k3s-master ~]# kubectl get pods -n dapr-system
NAME                                     READY   STATUS    RESTARTS   AGE
dapr-sentry-7c4fb54fb7-jjjpx             0/1     Pending   0          26m
dapr-sidecar-injector-6bdbc588fc-nltdk   0/1     Pending   0          26m
dapr-dashboard-6f749469dd-qw68m          0/1     Pending   0          26m
dapr-operator-699cd79686-gdskz           0/1     Pending   0          26m
dapr-placement-server-0                  0/1     Pending   0          26m
```
## Steps to Reproduce the Problem

1. Setup an arm64 Kubenetes cluster use rancher k3s v1.19.3, with one master and two workd nodes, follow this guid:https://rancher.com/docs/k3s/latest/en/installation/airgap/

2. Those are the nodes:

```shell
[root@k3s-master ~]# kubectl get nodes -o wide
NAME         STATUS   ROLES    AGE    VERSION        INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION                 CONTAINER-RUNTIME
k3s-master   Ready    master   21m    v1.19.3+k3s3   192.168.0.30   <none>        CentOS Linux 8 (Core)   4.18.0-147.5.1.el8_1.aarch64   containerd://1.4.1-k3s1
k3s-knode1   Ready    <none>   6m6s   v1.19.3+k3s3   192.168.0.31   <none>        CentOS Linux 8 (Core)   4.18.0-147.5.1.el8_1.aarch64   containerd://1.4.1-k3s1
k3s-knode2   Ready    <none>   68s    v1.19.3+k3s3   192.168.0.32   <none>        CentOS Linux 8 (Core)   4.18.0-147.5.1.el8_1.aarch64   containerd://1.4.1-k3s1
```

3. On master node, install dapr with CLI
download https://github.com/dapr/cli/releases/download/v1.0.0-rc.3/dapr_linux_arm64.tar.gz, untar and execute this command: ` ./dapr init -k --runtime-version 1.0.0-rc.2`  got those output:

```shell
[root@k3s-master ~]# ./dapr init -k --runtime-version 1.0.0-rc.2
⌛  Making the jump to hyperspace...
ℹ️  Note: To install Dapr using Helm, see here:  https://docs.dapr.io/getting-started/install-dapr/#install-with-helm-advanced

✅  Deploying the Dapr control plane to your cluster...
✅  Success! Dapr has been installed to namespace dapr-system. To verify, run `dapr status -k' in your terminal. To get started, go here: https://aka.ms/dapr-getting-started
```

4. Execute this command to check the dapr status: `./dapr status -k`, got those output:
```shell
[root@k3s-master ~]# ./dapr status -k
panic: runtime error: index out of range [0] with length 0

goroutine 15 [running]:
github.com/dapr/cli/pkg/kubernetes.(*StatusClient).Status.func1(0x400046fb90, 0x16e13a0, 0x40006b1760, 0x400046fb88, 0x40004458a0, 0x14747a6, 0x15)
        /home/runner/work/cli/cli/pkg/kubernetes/status.go:98 +0x74c
created by github.com/dapr/cli/pkg/kubernetes.(*StatusClient).Status
        /home/runner/work/cli/cli/pkg/kubernetes/status.go:70 +0x130
```
5. Check the pods:

```shell
[root@k3s-master ~]# kubectl get pods -n dapr-system
NAME                                     READY   STATUS    RESTARTS   AGE
dapr-sentry-7c4fb54fb7-jjjpx             0/1     Pending   0          26m
dapr-sidecar-injector-6bdbc588fc-nltdk   0/1     Pending   0          26m
dapr-dashboard-6f749469dd-qw68m          0/1     Pending   0          26m
dapr-operator-699cd79686-gdskz           0/1     Pending   0          26m
dapr-placement-server-0                  0/1     Pending   0          26m
```

6. Check the dapr-placement-server-0 pod status:

```shell
[root@k3s-master ~]# kubectl describe pods dapr-placement-server-0 -n dapr-system
Name:           dapr-placement-server-0
Namespace:      dapr-system
Priority:       0
Node:           <none>
Labels:         app=dapr-placement-server
                app.kubernetes.io/component=placement
                app.kubernetes.io/managed-by=helm
                app.kubernetes.io/name=dapr
                app.kubernetes.io/part-of=dapr
                app.kubernetes.io/version=1.0.0-rc.2
                controller-revision-hash=dapr-placement-server-6677c8b455
                statefulset.kubernetes.io/pod-name=dapr-placement-server-0
Annotations:    prometheus.io/path: /
                prometheus.io/port: 9090
                prometheus.io/scrape: true
Status:         Pending
IP:
IPs:            <none>
Controlled By:  StatefulSet/dapr-placement-server
Containers:
  dapr-placement-server:
    Image:       docker.io/daprio/dapr:1.0.0-rc.2
    Ports:       50005/TCP, 8201/TCP, 9090/TCP
    Host Ports:  0/TCP, 0/TCP, 0/TCP
    Command:
      /placement
    Args:
      --log-level
      info
      --enable-metrics
      --replicationFactor
      100
      --metrics-port
      9090
      --tls-enabled
    Limits:
      cpu:     1
      memory:  500Mi
    Requests:
      cpu:      250m
      memory:   100Mi
    Liveness:   http-get http://:8080/healthz delay=10s timeout=1s period=3s #success=1 #failure=5
    Readiness:  http-get http://:8080/healthz delay=10s timeout=1s period=3s #success=1 #failure=5
    Environment:
      PLACEMENT_ID:  dapr-placement-server-0 (v1:metadata.name)
      NAMESPACE:     dapr-system (v1:metadata.namespace)
    Mounts:
      /var/run/dapr/credentials from credentials (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from dapr-operator-token-wdv6f (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  credentials:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  dapr-trust-bundle
    Optional:    false
  dapr-operator-token-wdv6f:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  dapr-operator-token-wdv6f
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  27m   default-scheduler  0/3 nodes are available: 3 node(s) didn't match node selector.
  Warning  FailedScheduling  27m   default-scheduler  0/3 nodes are available: 3 node(s) didn't match node selector.
```

7. Check the dapr-placement-server-0 pod yaml:

```shell
[root@k3s-master ~]# kubectl get pod dapr-placement-server-0 -n dapr-system -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    prometheus.io/path: /
    prometheus.io/port: "9090"
    prometheus.io/scrape: "true"
  creationTimestamp: "2020-12-21T11:36:35Z"
  generateName: dapr-placement-server-
  labels:
    app: dapr-placement-server
    app.kubernetes.io/component: placement
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: dapr
    app.kubernetes.io/part-of: dapr
    app.kubernetes.io/version: 1.0.0-rc.2
    controller-revision-hash: dapr-placement-server-6677c8b455
    statefulset.kubernetes.io/pod-name: dapr-placement-server-0
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:prometheus.io/path: {}
          f:prometheus.io/port: {}
          f:prometheus.io/scrape: {}
        f:generateName: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/part-of: {}
          f:app.kubernetes.io/version: {}
          f:controller-revision-hash: {}
          f:statefulset.kubernetes.io/pod-name: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"1ec1b4c0-6293-42d6-a0c9-a18e3bcb67eb"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:affinity:
          .: {}
          f:nodeAffinity:
            .: {}
            f:requiredDuringSchedulingIgnoredDuringExecution:
              .: {}
              f:nodeSelectorTerms: {}
        f:containers:
          k:{"name":"dapr-placement-server"}:
            .: {}
            f:args: {}
            f:command: {}
            f:env:
              .: {}
              k:{"name":"NAMESPACE"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:fieldRef:
                    .: {}
                    f:apiVersion: {}
                    f:fieldPath: {}
              k:{"name":"PLACEMENT_ID"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:fieldRef:
                    .: {}
                    f:apiVersion: {}
                    f:fieldPath: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:livenessProbe:
              .: {}
              f:failureThreshold: {}
              f:httpGet:
                .: {}
                f:path: {}
                f:port: {}
                f:scheme: {}
              f:initialDelaySeconds: {}
              f:periodSeconds: {}
              f:successThreshold: {}
              f:timeoutSeconds: {}
            f:name: {}
            f:ports:
              .: {}
              k:{"containerPort":8201,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:name: {}
                f:protocol: {}
              k:{"containerPort":9090,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:name: {}
                f:protocol: {}
              k:{"containerPort":50005,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:name: {}
                f:protocol: {}
            f:readinessProbe:
              .: {}
              f:failureThreshold: {}
              f:httpGet:
                .: {}
                f:path: {}
                f:port: {}
                f:scheme: {}
              f:initialDelaySeconds: {}
              f:periodSeconds: {}
              f:successThreshold: {}
              f:timeoutSeconds: {}
            f:resources:
              .: {}
              f:limits:
                .: {}
                f:cpu: {}
                f:memory: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:memory: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/var/run/dapr/credentials"}:
                .: {}
                f:mountPath: {}
                f:name: {}
                f:readOnly: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:hostname: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:serviceAccount: {}
        f:serviceAccountName: {}
        f:subdomain: {}
        f:terminationGracePeriodSeconds: {}
        f:volumes:
          .: {}
          k:{"name":"credentials"}:
            .: {}
            f:name: {}
            f:secret:
              .: {}
              f:defaultMode: {}
              f:secretName: {}
      f:status:
        f:conditions:
          .: {}
          k:{"type":"PodScheduled"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
    manager: k3s
    operation: Update
    time: "2020-12-21T11:36:35Z"
  name: dapr-placement-server-0
  namespace: dapr-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: dapr-placement-server
    uid: 1ec1b4c0-6293-42d6-a0c9-a18e3bcb67eb
  resourceVersion: "28252"
  selfLink: /api/v1/namespaces/dapr-system/pods/dapr-placement-server-0
  uid: c780e4c7-b1ce-410e-afeb-371da210213a
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
            - linux
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
  containers:
  - args:
    - --log-level
    - info
    - --enable-metrics
    - --replicationFactor
    - "100"
    - --metrics-port
    - "9090"
    - --tls-enabled
    command:
    - /placement
    env:
    - name: PLACEMENT_ID
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    image: docker.io/daprio/dapr:1.0.0-rc.2
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /healthz
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 3
      successThreshold: 1
      timeoutSeconds: 1
    name: dapr-placement-server
    ports:
    - containerPort: 50005
      name: api
      protocol: TCP
    - containerPort: 8201
      name: raft-node
      protocol: TCP
    - containerPort: 9090
      name: metrics
      protocol: TCP
    readinessProbe:
      failureThreshold: 5
      httpGet:
        path: /healthz
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 3
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: "1"
        memory: 500Mi
      requests:
        cpu: 250m
        memory: 100Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/dapr/credentials
      name: credentials
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: dapr-operator-token-wdv6f
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: dapr-placement-server-0
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: dapr-operator
  serviceAccountName: dapr-operator
  subdomain: dapr-placement-server
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: credentials
    secret:
      defaultMode: 420
      secretName: dapr-trust-bundle
  - name: dapr-operator-token-wdv6f
    secret:
      defaultMode: 420
      secretName: dapr-operator-token-wdv6f
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-12-21T11:36:35Z"
    message: '0/3 nodes are available: 3 node(s) didn''t match node selector.'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: Burstable

 7： Check work node1:
 [root@k3s-master ~]# kubectl describe node k3s-knode1
Name:               k3s-knode1
Roles:              <none>
Labels:             beta.kubernetes.io/arch=arm64
                    beta.kubernetes.io/instance-type=k3s
                    beta.kubernetes.io/os=linux
                    k3s.io/hostname=k3s-knode1
                    k3s.io/internal-ip=192.168.0.31
                    kubernetes.io/arch=arm64
                    kubernetes.io/hostname=k3s-knode1
                    kubernetes.io/os=linux
                    node.kubernetes.io/instance-type=k3s
Annotations:        flannel.alpha.coreos.com/backend-data: {"VtepMAC":"c2:72:c9:cf:b5:e1"}
                    flannel.alpha.coreos.com/backend-type: vxlan
                    flannel.alpha.coreos.com/kube-subnet-manager: true
                    flannel.alpha.coreos.com/public-ip: 192.168.0.31
                    k3s.io/node-args: ["agent"]
                    k3s.io/node-config-hash: KHMB33HFSWENPXK4EJTIZA2OX5DLC4WFTQCZFVQNUJGLPEEJXPRA====
                    k3s.io/node-env:
                      {"K3S_DATA_DIR":"/var/lib/rancher/k3s/data/63dbbe8462074f773c2a00caa9a9a87684fcff868c7e6bf54b4433af70608590","K3S_TOKEN":"********","K3S_U...
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Mon, 30 Nov 2020 17:26:56 +0800
Taints:             <none>
Unschedulable:      false
Lease:
  HolderIdentity:  k3s-knode1
  AcquireTime:     <unset>
  RenewTime:       Mon, 21 Dec 2020 20:18:56 +0800
Conditions:
  Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----                 ------  -----------------                 ------------------                ------                       -------
  NetworkUnavailable   False   Mon, 21 Dec 2020 19:26:31 +0800   Mon, 21 Dec 2020 19:26:31 +0800   FlannelIsUp                  Flannel is running on this node
  MemoryPressure       False   Mon, 21 Dec 2020 20:16:36 +0800   Mon, 30 Nov 2020 17:26:56 +0800   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure         False   Mon, 21 Dec 2020 20:16:36 +0800   Mon, 30 Nov 2020 17:26:56 +0800   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure          False   Mon, 21 Dec 2020 20:16:36 +0800   Mon, 30 Nov 2020 17:26:56 +0800   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready                True    Mon, 21 Dec 2020 20:16:36 +0800   Mon, 30 Nov 2020 17:27:06 +0800   KubeletReady                 kubelet is posting ready status
Addresses:
  InternalIP:  192.168.0.31
  Hostname:    k3s-knode1
Capacity:
  cpu:                2
  ephemeral-storage:  40504576Ki
  hugepages-2Mi:      0
  hugepages-512Mi:    0
  memory:             3628352Ki
  pods:               110
Allocatable:
  cpu:                2
  ephemeral-storage:  39402851502
  hugepages-2Mi:      0
  hugepages-512Mi:    0
  memory:             3628352Ki
  pods:               110
System Info:
  Machine ID:                 d8926d4838654086bb26b9251a33064b
  System UUID:                f97a5f2d-fddc-404f-b22a-daefaa09c0fc
  Boot ID:                    407ef7ca-a7ba-4b41-b2bb-fa7e80dcc4d4
  Kernel Version:             4.18.0-147.5.1.el8_1.aarch64
  OS Image:                   CentOS Linux 8 (Core)
  Operating System:           linux
  Architecture:               arm64
  Container Runtime Version:  containerd://1.4.1-k3s1
  Kubelet Version:            v1.19.3+k3s3
  Kube-Proxy Version:         v1.19.3+k3s3
PodCIDR:                      10.42.1.0/24
PodCIDRs:                     10.42.1.0/24
ProviderID:                   k3s://k3s-knode1
Non-terminated Pods:          (1 in total)
  Namespace                   Name                   CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                   ----                   ------------  ----------  ---------------  -------------  ---
  kube-system                 svclb-traefik-jsh4k    0 (0%)        0 (0%)      0 (0%)           0 (0%)         21d
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests  Limits
  --------           --------  ------
  cpu                0 (0%)    0 (0%)
  memory             0 (0%)    0 (0%)
  ephemeral-storage  0 (0%)    0 (0%)
  hugepages-2Mi      0 (0%)    0 (0%)
  hugepages-512Mi    0 (0%)    0 (0%)
Events:
  Type     Reason                   Age   From        Message
  ----     ------                   ----  ----        -------
  Normal   Starting                 52m   kube-proxy  Starting kube-proxy.
  Normal   Starting                 52m   kubelet     Starting kubelet.
  Warning  InvalidDiskCapacity      52m   kubelet     invalid capacity 0 on image filesystem
  Normal   NodeAllocatableEnforced  52m   kubelet     Updated Node Allocatable limit across pods
  Normal   NodeHasSufficientMemory  52m   kubelet     Node k3s-knode1 status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    52m   kubelet     Node k3s-knode1 status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     52m   kubelet     Node k3s-knode1 status is now: NodeHasSufficientPID
  Warning  Rebooted                 52m   kubelet     Node k3s-knode1 has been rebooted, boot id: 407ef7ca-a7ba-4b41-b2bb-fa7e80dcc4d4
```

8. Conclusion, the node nodeAffinity of Dapr's pods not right, my k3s cluster are arm64, but the pods need amd64, how to fix that? Thanks.

## Release Note

RELEASE NOTE: **FIX** CLI and helm chart no longer default to amd64 architecture for Kubernetes installs. This allows deployments to arm64 Kubernetes clusters to succeed with the default configuration.

**Comment by wcs1only** [comment]
Moved to dapr/dapr, as this is primarily an issue with the helm charts, not the CLI.

**Comment by F-Sidney** [comment]
> We allow setting the affinity when installing via helm:
> 
> ```
> helm repo add dapr https://dapr.github.io/helm-charts/
> helm repo update
> helm install dapr dapr/dapr --set global.daprControlPlaneArch=arm64 --version 1.0.0-rc.2
> ```
> 
> Can you try the above and see if that clears the issue for you?
> 
> **Note:** This was most likely introduced by #2245 . We might be able to fix this by not setting affinity when global.daprControlPlaneArch= is missing. Our default dapr containers should run on both arm64 and amd64, so if we just let the scheduler pick whatever is available by default, that should make the default dapr init -k just work.

Yes, it works, thank you Charlie, now the dapr runing well, but I found it not in dapr-system namespace, 
so I used this command

 `helm install dapr dapr/dapr --namespace dapr-system --set global.daprControlPlaneArch=arm64 --version 1.0.0-rc.2`

here is the whole story:

```shell
[root@k3s-master ~]# dapr uninstall -k
ℹ️  Removing Dapr from your cluster...
✅  Dapr has been removed successfully

[root@k3s-master ~]# helm repo add dapr https://dapr.github.io/helm-charts/
"dapr" has been added to your repositories
[root@k3s-master ~]# helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "dapr" chart repository
Update Complete. ⎈Happy Helming!⎈
[root@k3s-master ~]# helm install dapr dapr/dapr --set global.daprControlPlaneArch=arm64 --version 1.0.0-rc.2
NAME: dapr
LAST DEPLOYED: Wed Dec 23 10:39:59 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you for installing Dapr: High-performance, lightweight serverless runtime for cloud and edge

Your release is named dapr.

To get started with Dapr, we recommend using our quickstarts:
https://github.com/dapr/quickstarts

For more information on running Dapr, visit:
https://dapr.io

[root@k3s-master ~]# dapr status -k
  NAME                   NAMESPACE  HEALTHY  STATUS   REPLICAS  VERSION     AGE  CREATED
  dapr-dashboard         default    True     Running  1         0.5.0       55s  2020-12-23 10:40.00
  dapr-sidecar-injector  default    True     Running  1         1.0.0-rc.2  55s  2020-12-23 10:40.00
  dapr-placement-server  default    True     Running  1         1.0.0-rc.2  54s  2020-12-23 10:40.01
  dapr-operator          default    True     Running  1         1.0.0-rc.2  55s  2020-12-23 10:40.00
  dapr-sentry            default    True     Running  1         1.0.0-rc.2  55s  2020-12-23 10:40.00

[root@k3s-master ~]# helm uninstall dapr
release "dapr" uninstalled
[root@k3s-master ~]# dapr status -k
❌  No status returned. Is Dapr initialized in your cluster?
[root@k3s-master ~]# helm install dapr dapr/dapr --namespace dapr-system --set global.daprControlPlaneArch=arm64 --version 1.0.0-rc.2
NAME: dapr
LAST DEPLOYED: Wed Dec 23 10:52:05 2020
NAMESPACE: dapr-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you for installing Dapr: High-performance, lightweight serverless runtime for cloud and edge

Your release is named dapr.

To get started with Dapr, we recommend using our quickstarts:
https://github.com/dapr/quickstarts

For more information on running Dapr, visit:
https://dapr.io

[root@k3s-master ~]# dapr status -k
  NAME                   NAMESPACE    HEALTHY  STATUS   REPLICAS  VERSION     AGE  CREATED
  dapr-sentry            dapr-system  True     Running  1         1.0.0-rc.2  22s  2020-12-23 10:52.05
  dapr-operator          dapr-system  True     Running  1         1.0.0-rc.2  22s  2020-12-23 10:52.05
  dapr-dashboard         dapr-system  True     Running  1         0.5.0       22s  2020-12-23 10:52.05
  dapr-placement-server  dapr-system  True     Running  1         1.0.0-rc.2  22s  2020-12-23 10:52.05
  dapr-sidecar-injector  dapr-system  True     Running  1         1.0.0-rc.2  22s  2020-12-23 10:52.05
```
