### ISSUE TITLE
Go Panic on Actors usage (Redis) with PubSub (Redis) on Start

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/dapr#3258]
## In what area(s)?

/area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## What version of Dapr?

1.2.0

## Expected Behavior

I would like to utilize Redis as my state store and placement store for Actors as well as create a component to the same Redis for Pub/Sub usage.

In my opinion this is happening due to the fact that the statestore is not correctly initialized. When going to the [source](https://github.com/dapr/dapr/blob/8aab85beca3bc33a3dc848d39ad3263273c5f7cd/pkg/actors/actors.go#L974) it seems that it tries to fetch a key but fails.

When I [set up a state store](https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-redis/#component-format), it is correctly working.

Maybe it would be interesting to see if the message output could be clearer and ask to setup a statestore rather than to throw a Panic?

## Actual Behavior

When executing the following:
1. Create Actor (see Demo Actor - .NET)
2. Add component for `type: pubsub.redis`
3. Start with the component referenced

Then I see

```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x162fca9]

goroutine 140 [running]:
github.com/dapr/dapr/pkg/actors.(*actorsRuntime).getRemindersForActorType(0xc000103080, 0xc000db6720, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/runner/work/dapr/dapr/pkg/actors/actors.go:975 +0xe9
github.com/dapr/dapr/pkg/actors.(*actorsRuntime).evaluateReminders(0xc000103080)
        /home/runner/work/dapr/dapr/pkg/actors/actors.go:557 +0x153
github.com/dapr/dapr/pkg/actors.(*actorsRuntime).Init.func1()
        /home/runner/work/dapr/dapr/pkg/actors/actors.go:158 +0x3d
github.com/dapr/dapr/pkg/actors/internal.(*ActorPlacement).updatePlacements(0xc000914c30, 0xc000464100)
        /home/runner/work/dapr/dapr/pkg/actors/internal/placement.go:366 +0x48c
github.com/dapr/dapr/pkg/actors/internal.(*ActorPlacement).onPlacementOrder(0xc000914c30, 0xc000464080)
        /home/runner/work/dapr/dapr/pkg/actors/internal/placement.go:334 +0x258
github.com/dapr/dapr/pkg/actors/internal.(*ActorPlacement).Start.func1(0xc000914c30)
        /home/runner/work/dapr/dapr/pkg/actors/internal/placement.go:176 +0x2ce
created by github.com/dapr/dapr/pkg/actors/internal.(*ActorPlacement).Start
        /home/runner/work/dapr/dapr/pkg/actors/internal/placement.go:143 +0xf3
```

My component configuration

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub-redis
  namespace: default
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: consumerID
    value: "myGroup"
  - name: enableTLS
    value: "false"
```

When looking at startup, I see my application starting and Dapr seeing that it started but then crashing instantly. I included a full start-up log of this:

```bash
ℹ️  Starting Dapr with id dapr-masked. HTTP Port: 3500. gRPC Port: 10200
INFO[0000] starting Dapr Runtime -- version 1.2.0 -- commit 8e960e2  app_id=dapr-masked instance=THE-BEAST scope=dapr.runtime type=log ver=1.2.0
INFO[0000] log level set to: info                        app_id=dapr-masked instance=THE-BEAST scope=dapr.runtime type=log ver=1.2.0
INFO[0000] metrics server started on :34873/             app_id=dapr-masked instance=THE-BEAST scope=dapr.metrics type=log ver=1.2.0
INFO[0000] standalone mode configured                    app_id=dapr-masked instance=THE-BEAST scope=dapr.runtime type=log ver=1.2.0
INFO[0000] app id: dapr-masked                        app_id=dapr-masked instance=THE-BEAST scope=dapr.runtime type=log ver=1.2.0
INFO[0000] mTLS is disabled. Skipping certificate request and tls validation  app_id=dapr-masked instance=THE-BEAST scope=dapr.runtime type=log ver=1.2.0
INFO[0000] local service entry announced: dapr-masked -> 172.28.141.131:44627  app_id=dapr-masked instance=THE-BEAST scope=dapr.contrib type=log ver=1.2.0
INFO[0000] Initialized name resolution to mdns           app_id=dapr-masked instance=THE-BEAST scope=dapr.runtime type=log ver=1.2.0
INFO[0000] waiting for all outstanding components to be processed  app_id=dapr-masked instance=THE-BEAST scope=dapr.runtime type=log ver=1.2.0
INFO[0000] component loaded. name: pubsub-redis, type: pubsub.redis/v1  app_id=dapr-masked instance=THE-BEAST scope=dapr.runtime type=log ver=1.2.0
INFO[0000] all outstanding components processed          app_id=dapr-masked instance=THE-BEAST scope=dapr.runtime type=log ver=1.2.0
INFO[0000] enabled gRPC tracing middleware               app_id=dapr-masked instance=THE-BEAST scope=dapr.runtime.grpc.api type=log ver=1.2.0
INFO[0000] enabled gRPC metrics middleware               app_id=dapr-masked instance=THE-BEAST scope=dapr.runtime.grpc.api type=log ver=1.2.0
INFO[0000] API gRPC server is running on port 10200      app_id=dapr-masked instance=THE-BEAST scope=dapr.runtime type=log ver=1.2.0
INFO[0000] enabled metrics http middleware               app_id=dapr-masked instance=THE-BEAST scope=dapr.runtime.http type=log ver=1.2.0
INFO[0000] enabled tracing http middleware               app_id=dapr-masked instance=THE-BEAST scope=dapr.runtime.http type=log ver=1.2.0
INFO[0000] http server is running on port 3500           app_id=dapr-masked instance=THE-BEAST scope=dapr.runtime type=log ver=1.2.0
INFO[0000] The request body size parameter is: 4         app_id=dapr-masked instance=THE-BEAST scope=dapr.runtime type=log ver=1.2.0
INFO[0000] enabled gRPC tracing middleware               app_id=dapr-masked instance=THE-BEAST scope=dapr.runtime.grpc.internal type=log ver=1.2.0
INFO[0000] enabled gRPC metrics middleware               app_id=dapr-masked instance=THE-BEAST scope=dapr.runtime.grpc.internal type=log ver=1.2.0
INFO[0000] internal gRPC server is running on port 44627  app_id=dapr-masked instance=THE-BEAST scope=dapr.runtime type=log ver=1.2.0
INFO[0000] application protocol: http. waiting on port 10000.  This will block until the app is listening on that port.  app_id=dapr-masked instance=THE-BEAST scope=dapr.runtime type=log ver=1.2.0
== APP == Building...

ℹ️  Updating metadata for app command: dotnet run
✅  You're up and running! Both Dapr and your app logs will appear here.

== APP == info: Microsoft.Hosting.Lifetime[0]

== APP ==       Now listening on: https://localhost:10001

== APP == info: Microsoft.Hosting.Lifetime[0]

== APP ==       Now listening on: http://localhost:10000

== APP == info: Microsoft.Hosting.Lifetime[0]

== APP ==       Application started. Press Ctrl+C to shut down.

== APP == info: Microsoft.Hosting.Lifetime[0]

== APP ==       Hosting environment: Development

== APP == info: Microsoft.Hosting.Lifetime[0]

== APP ==       Content root path: /home/xanrin/Projects/rw-platform/2-masked/MaskedActorService

INFO[0001] application discovered on port 10000          app_id=dapr-masked instance=THE-BEAST scope=dapr.runtime type=log ver=1.2.0
INFO[0001] application configuration loaded              app_id=dapr-masked instance=THE-BEAST scope=dapr.runtime type=log ver=1.2.0
WARN[0001] actors: state store must be present to initialize the actor runtime  app_id=dapr-masked instance=THE-BEAST scope=dapr.runtime.actor type=log ver=1.2.0
INFO[0001] actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s  app_id=dapr-masked instance=THE-BEAST scope=dapr.runtime.actor type=log ver=1.2.0
INFO[0001] dapr initialized. Status: Running. Init Elapsed 1215.1367ms  app_id=dapr-masked instance=THE-BEAST scope=dapr.runtime type=log ver=1.2.0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x162fca9]

goroutine 214 [running]:
github.com/dapr/dapr/pkg/actors.(*actorsRuntime).getRemindersForActorType(0xc00020b680, 0xc00081ec10, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/runner/work/dapr/dapr/pkg/actors/actors.go:975 +0xe9
github.com/dapr/dapr/pkg/actors.(*actorsRuntime).evaluateReminders(0xc00020b680)
        /home/runner/work/dapr/dapr/pkg/actors/actors.go:557 +0x153
github.com/dapr/dapr/pkg/actors.(*actorsRuntime).Init.func1()
        /home/runner/work/dapr/dapr/pkg/actors/actors.go:158 +0x3d
github.com/dapr/dapr/pkg/actors/internal.(*ActorPlacement).updatePlacements(0xc0008fa4e0, 0xc000822cc0)
        /home/runner/work/dapr/dapr/pkg/actors/internal/placement.go:366 +0x48c
github.com/dapr/dapr/pkg/actors/internal.(*ActorPlacement).onPlacementOrder(0xc0008fa4e0, 0xc000822c80)
        /home/runner/work/dapr/dapr/pkg/actors/internal/placement.go:334 +0x258
github.com/dapr/dapr/pkg/actors/internal.(*ActorPlacement).Start.func1(0xc0008fa4e0)
        /home/runner/work/dapr/dapr/pkg/actors/internal/placement.go:176 +0x2ce
created by github.com/dapr/dapr/pkg/actors/internal.(*ActorPlacement).Start
        /home/runner/work/dapr/dapr/pkg/actors/internal/placement.go:143 +0xf3
```

**Comment by XavierGeerinck** [comment]
Update: also appears to happen on other components 🤔 tried it with PubSub for RabbitMQ and doesn't work either.

**Comment by daixiang0** [comment]
I think need to wait dapr/components-contrib make a release including https://github.com/dapr/components-contrib/pull/757, it would add `Ping()` to check store state. @artursouza 

/assign @daixiang0

**Comment by beiwei30** [comment]
I have a prototype on this, pls. assign 

/assign @beiwei30
