### ISSUE TITLE
oAuth2 with Azure AAD Exception: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by GregorBiswanger** [dapr/dapr#3501]
Used Version 1.3

I have assigned the oAuth Middleware pipeline to the Api Gateway (Envoy). Except when I was authenticated and the journey was back, I got the following error message from Envoy: `upstream connect error or disconnect/reset before headers. reset reason: connection termination.`

**The Dapr container breaks and restarts.** What could be the reason?

My Api Gateway Dapr Sidecar log:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xd1c1e6]

goroutine 229 [running]:
golang.org/x/oauth2.(*Token).Type(0x0, 0xc000fc8900, 0x20e)
        /home/runner/go/pkg/mod/golang.org/x/oauth2@v0.0.0-20201208152858-08078c50e5b5/token.go:59 +0x26
github.com/dapr/components-contrib/middleware/http/oauth2.(*Middleware).GetHandler.func1.1(0xc000331900)
        /home/runner/go/pkg/mod/github.com/dapr/components-contrib@v1.2.0/middleware/http/oauth2/oauth2_middleware.go:100 +0x736
github.com/dapr/dapr/pkg/diagnostics.(*httpMetrics).FastHTTPMiddleware.func1(0xc000331900)
        /home/runner/work/dapr/dapr/pkg/diagnostics/http_monitoring.go:186 +0x1a4
github.com/dapr/dapr/pkg/diagnostics.HTTPTraceMiddleware.func1(0xc000331900)
        /home/runner/work/dapr/dapr/pkg/diagnostics/http_tracing.go:47 +0x177
github.com/valyala/fasthttp.(*Server).serveConn(0xc000433200, 0x3dc4570, 0xc0001871d8, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.21.0/server.go:2193 +0x128e
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc00087b040, 0xc00113e960)
        /home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.21.0/workerpool.go:223 +0xba
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc00087b040, 0xc00113e960, 0x2fd0840, 0xc00113e960)
        /home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.21.0/workerpool.go:195 +0x35
created by github.com/valyala/fasthttp.(*workerPool).getCh
        /home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.21.0/workerpool.go:194 +0x11f
```

**Comment by daixiang0** [comment]
Could share setup steps?

**Comment by GregorBiswanger** [comment]
I noticed it while reproducing. If I ONLY add the oAuth to one service.. the API Gateway it works. But not if several Dapr sidecars are assigned one. Unfortunately I can't fix anonymous routes and I don't get any authorization information.. but it is probably due to the API Gateway Envoy.. that must overwrite the header.. Envoy is really brutally complicated for me..

I would also like to be interested in how others integrate their security into a microservice landscape.. normally an API gateway should regulate the security automatically?! So that not every service would have to consider oAuth logic?!
