### ISSUE TITLE
middleware.http.opa Error at dapr run: invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by melodicdeath** [dapr/dapr#3701]
## In what area(s)?

> /area runtime

## What version of Dapr?

> 1.4.0

## Expected Behavior

Normal start

## Actual Behavior

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15a444d]

goroutine 1 [running]:
github.com/dapr/dapr/pkg/middleware/http.Pipeline.Apply({{0xc000cafa30, 0x17, 0x368d6ff}}, 0x4)
        /home/runner/work/dapr/dapr/pkg/middleware/http/http_pipeline.go:27 +0x2d
github.com/dapr/dapr/pkg/http.(*server).useComponents(...)
        /home/runner/work/dapr/dapr/pkg/http/server.go:183
github.com/dapr/dapr/pkg/http.(*server).StartNonBlocking(0xc000cf8360)
        /home/runner/work/dapr/dapr/pkg/http/server.go:68 +0x65
github.com/dapr/dapr/pkg/runtime.(*DaprRuntime).startHTTPServer(0xc0007d7400, 0xdac, 0x0, 0x1e61, {0x3c5abd8, 0x1}, {{0xc000cafa30, 0x0, 0x7}})
        /home/runner/work/dapr/dapr/pkg/runtime/runtime.go:904 +0x61b
github.com/dapr/dapr/pkg/runtime.(*DaprRuntime).initRuntime(0xc0007d7400, 0xc000355130)
        /home/runner/work/dapr/dapr/pkg/runtime/runtime.go:358 +0x815
github.com/dapr/dapr/pkg/runtime.(*DaprRuntime).Run(0xc0007d7400, {0xc000bbf5a8, 0x7, 0x2})
        /home/runner/work/dapr/dapr/pkg/runtime/runtime.go:230 +0x208
main.main()
        /home/runner/work/dapr/dapr/cmd/daprd/main.go:155 +0x14df
❌  The daprd process exited with error code: exit status 2
⚠  Could not update sidecar metadata for cliPID: PUT http://127.0.0.1:3500/v1.0/metadata/cliPID giving up after 5 attempts
✅  You're up and running! Dapr logs will appear here.

## Steps to Reproduce the Problem

1. component

![2021-09-22_10-41](https://user-images.githubusercontent.com/7873135/134275229-9246a6c8-bace-44f6-98af-70ae5b2c7d43.png)

2. configuration
![2021-09-22_10-44](https://user-images.githubusercontent.com/7873135/134275321-42866e58-5a97-42c0-8ea8-f386901eb9db.png)

3. run
dapr run --app-id dapr-learn --components-path ./components --config ./dapr-config.yaml --app-port 8060 --dapr-http-port 3500 --dapr-grpc-port 50001

P.S.If I delete the definition of my-policy in the dapr-config.yaml file and only use uppercase, there is no problem

**Comment by Taction** [comment]
Thanks for reporting it. Duplicated with #3216, has been fixed but hasn't been fully merged. And you may see it soon.
