### ISSUE TITLE
Panic in actor placement.go

### ISSUE THREAD

**Issue by pkedy** [dapr/dapr#3727]
In this [workflow run](https://github.com/dapr/dapr/actions/runs/1276467499), the pubsub routing test fails because at the same time, `daprd` crashes with this error.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x139fad7]

goroutine 282 [running]:
github.com/dapr/dapr/pkg/actors/internal.(*ActorPlacement).Start.func4.2(0xc0005a49a0, 0x368e75f, 0xc000c98f38)
	/home/runner/work/dapr/dapr/src/github.com/dapr/dapr/pkg/actors/internal/placement.go:258 +0x97
github.com/dapr/dapr/pkg/actors/internal.(*ActorPlacement).Start.func4()
	/home/runner/work/dapr/dapr/src/github.com/dapr/dapr/pkg/actors/internal/placement.go:259 +0x1b8
created by github.com/dapr/dapr/pkg/actors/internal.(*ActorPlacement).Start
	/home/runner/work/dapr/dapr/src/github.com/dapr/dapr/pkg/actors/internal/placement.go:216 +0x105
```

Possibly related to #3726

RELEASE NOTE: **FIX** Fixed panic sending on a nil gRPC stream in the placement heartbeat loop.

**Comment by slacksach** [comment]
@pkedy We observed very similar behaviour similar to this and #3726 in our #3607, might be entirely unrelated but similar characteristics,

In our case it was due to custom manifests, we had done a comparison but not removed these lines from the args
```
        - "--initial-cluster"
        - dapr-placement-server-0=dapr-placement-server-0.dapr-placement-server.dapr-system.svc.cluster.local:8201,dapr-placement-server-1=dapr-placement-server-1.dapr-placement-server.dapr-system.svc.cluster.local:8201,dapr-placement-server-2=dapr-placement-server-2.dapr-placement-server.dapr-system.svc.cluster.local:8201
```

Once removed and the ReplicaSet was updated the error no longer occurs in our setup.
