### ISSUE TITLE
Subscription v1alpha1 applied in v2alpha1

### ISSUE THREAD

**Issue by speedfl** [dapr/dapr#3731]
## In what area(s)?

 /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

1.4.2

## Expected Behavior

I would expect my subscription route to be called

## Actual Behavior

My route is not called.
After looking at the dapr logs I can see ""

## Steps to Reproduce the Problem

From: https://docs.dapr.io/developing-applications/building-blocks/pubsub/howto-publish-subscribe/

```
$ kubectl apply -f subscription.yaml
$ kubectl get subscriptions.dapr.io/myevent-subscription -o yaml
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"dapr.io/v1alpha1","kind":"Subscription","metadata":{"annotations":{},"name":"myevent-subscription","namespace":"orms-localdev"},"scopes":["app1","app2"],"spec":{"pubsubname":"pubsub","route":"/dsstatus","topic":"deathStarStatus"}}
  creationTimestamp: 2021-10-02T06:18:15Z
  generation: 1
  managedFields:
  - apiVersion: dapr.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:scopes: {}
      f:spec:
        .: {}
        f:pubsubname: {}
        f:route: {}
        f:topic: {}
    manager: kubectl
    operation: Update
    time: 2021-10-02T06:18:15Z
  name: myevent-subscription
  namespace: orms-localdev
  resourceVersion: "161810"
  uid: c24065b5-8291-4888-acc3-9b38ce1032fa
scopes:
- app1
- app2
spec:
  pubsubname: pubsub
  topic: deathStarStatus
```

This cause an issue because the **route** disappear 

If you go further by reproducing the full scenario:

- Delete existing CRD on kubernetes Cluster (they are not deleted with `dapr uninstall -k`)
- Install Dapr on a provided namespace with `dapr init -k -n <namespace>`
- Follow this: https://docs.dapr.io/developing-applications/building-blocks/pubsub/howto-publish-subscribe/
- Add the annotations to consumer:

```
        dapr.io/enabled: "true"
        dapr.io/app-id: app1
        dapr.io/app-port: "3000"
        dapr.io/log-level: "debug"
```
- Add the annotations to producer:

```
        dapr.io/enabled: "true"
        dapr.io/app-id: app2
        dapr.io/app-port: "8080"
        dapr.io/log-level: "debug"
```
- Shoot an event

You might see in the dapr logs of the consumer:

```
time="2021-10-02T06:11:43.410597586Z" level=debug msg="no matching route for event 0722e80b-d5af-4c12-b4de-60710f82bba7 in pubsub pubsub and topic deathStarStatus; skipping" app_id=app1=dapr-consumer-6cb9d5c97d-bwbgx scope=dapr.runtime type=log ver=1.4.2
```

## Release Note

RELEASE NOTE:

**Comment by pkedy** [comment]
Hi, @speedfl!  Thanks for reporting this. Looks like your example above is trying to use the `v2alpha1` structure with `v1alpha1`, which obviously won't work. I just want to confirm that is not the issue. This is what the YAML should look like for each version. 

`v1alpha1`

```yaml
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: myevent-subscription
spec:
  topic: deathStarStatus
  pubsubname: pubsub
  route: /dsstatus
scopes:
- app1
- app2
```

`v2alpha1`

```yaml
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: myevent-subscription
spec:
  topic: deathStarStatus
  pubsubname: pubsub
  routes:
    default: /dsstatus
scopes:
- app1
- app2
```

That said the output of `kubectl get subscriptions.dapr.io/myevent-subscription -o yaml`, seems wrong.  Since `v2alpha1` is marked as the "stored version", the output will be confusing, but I would expect to see the `routes` field if it was converted correctly.

I'll try to reproduce and report back. Feel free to ping me directly on Discord.

**Comment by speedfl** [comment]
Hi @pkedy

I tried yesterday with the v2 format and everything is going well.
Have a good day.

**Comment by fjvela** [comment]
/cc @pkedy @artursouza 

I upgrade to 1.4.3.  I get this error:
`time="2021-10-11T12:18:35.519609747Z" level=info msg="log level set to: info" instance=dapr-operator-9bc45d8fc-czqd9 scope=dapr.operator type=log ver=unknown
time="2021-10-11T12:18:35.519784194Z" level=info msg="metrics server started on :9090/" instance=dapr-operator-9bc45d8fc-czqd9 scope=dapr.metrics type=log ver=unknown
time="2021-10-11T12:18:35.520200483Z" level=info msg="starting Dapr Operator -- version 1.4.3 -- commit a8ee30180e1183e2a2e4d00c283448af6d73d0d0" instance=dapr-operator-9bc45d8fc-czqd9 scope=dapr.operator type=log ver=unknown
I1011 12:18:36.573546       1 request.go:655] Throttling request took 1.044726144s, request: GET:https://172.20.0.1:443/apis/coordination.k8s.io/v1?timeout=32s
time="2021-10-11T12:18:36.73283813Z" level=info msg="Dapr Operator is started" instance=dapr-operator-9bc45d8fc-czqd9 scope=dapr.operator type=log ver=unknown
I1011 12:18:36.732953       1 leaderelection.go:243] attempting to acquire leader lease dapr-system/operator.dapr.io...
time="2021-10-11T12:18:36.940709962Z" level=info msg="getting tls certificates" instance=dapr-operator-9bc45d8fc-czqd9 scope=dapr.operator type=log ver=unknown
time="2021-10-11T12:18:36.940842904Z" level=info msg="tls certificates loaded successfully" instance=dapr-operator-9bc45d8fc-czqd9 scope=dapr.operator type=log ver=unknown
time="2021-10-11T12:18:36.941303961Z" level=info msg="starting gRPC server" instance=dapr-operator-9bc45d8fc-czqd9 scope=dapr.operator.api type=log ver=unknown
time="2021-10-11T12:18:36.941386697Z" level=info msg="Healthz server is listening on :8080" instance=dapr-operator-9bc45d8fc-czqd9 scope=dapr.operator type=log ver=unknown
time="2021-10-11T12:18:37.944396942Z" level=info msg="starting webhooks" instance=dapr-operator-9bc45d8fc-czqd9 scope=dapr.operator type=log ver=unknown
I1011 12:18:37.944450       1 leaderelection.go:243] attempting to acquire leader lease dapr-system/webhooks.dapr.io...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13e901a]
goroutine 436 [running[]:
github.com/dapr/dapr/pkg/operator.patchCRDs({0x18e43b0, 0xc0007bf7c0}, 0x0, {0xc000ade270, 0x1, 0x0})
    /home/runner/work/dapr/dapr/pkg/operator/webhooks.go:121 +0x4fa
created by github.com/dapr/dapr/pkg/operator.RunWebhooks
    /home/runner/work/dapr/dapr/pkg/operator/webhooks.go:68 +0x665`

I tried a downgrade to 1.4.2 and now I can't apply a Subscription:
`unable to recognize "": no matches for kind "Subscription" in version "dapr.io/v2alpha1"`

**Comment by fjvela** [comment]
It hasn't been updated

```json
Name:         subscriptions.dapr.io
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  apiextensions.k8s.io/v1
Kind:         CustomResourceDefinition
Metadata:
  Creation Timestamp:  2021-02-16T10:47:00Z
  Generation:          1
  Managed Fields:
    API Version:  apiextensions.k8s.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:conversion:
          .:
          f:strategy:
        f:group:
        f:names:
          f:categories:
          f:kind:
          f:listKind:
          f:plural:
          f:singular:
        f:preserveUnknownFields:
        f:scope:
        f:version:
        f:versions:
      f:status:
        f:storedVersions:
    Manager:      Go-http-client
    Operation:    Update
    Time:         2021-02-16T10:47:00Z
    API Version:  apiextensions.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:acceptedNames:
          f:categories:
          f:kind:
          f:listKind:
          f:plural:
          f:singular:
        f:conditions:
    Manager:         kube-apiserver
    Operation:       Update
    Time:            2021-02-16T10:47:00Z
  Resource Version:  2367663
  Self Link:         /apis/apiextensions.k8s.io/v1/customresourcedefinitions/subscriptions.dapr.io
  UID:               56ae5d44-0ac9-4b9e-94a8-e0164bacec12
Spec:
  Conversion:
    Strategy:  None
  Group:       dapr.io
  Names:
    Categories:
      all
      dapr
    Kind:                   Subscription
    List Kind:              SubscriptionList
    Plural:                 subscriptions
    Singular:               subscription
  Preserve Unknown Fields:  true
  Scope:                    Namespaced
  Versions:
    Name:     v1alpha1
    Served:   true
    Storage:  true
Status:
  Accepted Names:
    Categories:
      all
      dapr
    Kind:       Subscription
    List Kind:  SubscriptionList
    Plural:     subscriptions
    Singular:   subscription
  Conditions:
    Last Transition Time:  2021-02-16T10:47:00Z
    Message:               no conflicts found
    Reason:                NoConflicts
    Status:                True
    Type:                  NamesAccepted
    Last Transition Time:  2021-02-16T10:47:00Z
    Message:               the initial names have been accepted
    Reason:                InitialNamesAccepted
    Status:                True
    Type:                  Established
  Stored Versions:
    v1alpha1
Events:  <none>```

**Comment by pkedy** [comment]
@fjvela That's actually intentional. If you delete a CRD, then it deletes all the instances of that CRD. So having Helm or the Dapr CLI delete them could lead to unintentional data loss.
