### ISSUE TITLE
service-to-service call fails with 400 bad request

### ISSUE THREAD

**Issue by javageek79** [dapr/dapr#4553]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

> 1.7.3

## Expected Behavior

Service-to-service calls work as before

## Actual Behavior

The call works with 1.6.2 and fails with latest patch release.

Inner cause is
```
Caused by: io.dapr.exceptions.DaprException: UNKNOWN: <!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1></body></html>
	at io.dapr.client.DaprHttp.parseDaprError(DaprHttp.java:333)
	at io.dapr.client.DaprHttp.access$200(DaprHttp.java:47)
	at io.dapr.client.DaprHttp$ResponseFutureCallback.onResponse(DaprHttp.java:365)
	... 4 common frames omitted
```

## Steps to Reproduce the Problem

Create a invoke call with

```java
//...
daprInvoker.invokeMethod(properties.getDaprAppId(), methodToInvoke, body, createPostExtension())
//...
private HttpExtension createPostExtension() {
        return new HttpExtension(DaprHttp.HttpMethods.POST, Map.of(), Map.of(
                HttpHeaders.ACCEPT, MediaType.APPLICATION_JSON_VALUE
        ));
    }
```
## Release Note

RELEASE NOTE:

**Comment by yaron2** [comment]
Do we move this to the Java SDK repo then?

**Comment by artursouza** [comment]
Not yet. We are validating if the latest Java SDK is compatible with the previous runtime (1.6.x) for service invocation containing "/".

**Comment by pravinpushkar** [comment]
Summary of tests executed - 

**Runtime- 1.6.2 and java-sdk 1.5.0**
caller method name - "/say/test"
expected callee mapping - "/say/test"

caller method name - "/say/method1%2F111/test"
here %2F is converted to "/" and thus callee expects a mapping "/say/method1/111/test"

**Runtime- 1.7.2 and java-sdk 1.5.0**
caller method name - "/say/method1%2F111/test"
here %2F is not converted to "/" and thus callee expects a mapping "/say/method1%2F111/test"

**Comment by javageek79** [comment]
Hi @pravinpushkar, does this mean, sdk 1.5.0 is compatible with rt 1.6.2?

**Comment by pravinpushkar** [comment]
@javageek79 We can say it is compatible, only thing is it needs to have the fix https://github.com/dapr/dapr/issues/4008 for not decoding the %2F.

Can you please verify this at your end also?

**Comment by javageek79** [comment]
As said, our preferred setup would be,

1. step, run runtime v1.6.2 with sdks 1.5 or 1.4
2. step, run runtime v1.7.2 with sdk 1.5

If those scenarios are possible, it's all fine.

**Comment by pravinpushkar** [comment]
Could you please verify with SDK 1.5 and runtime v1.7.2 or v1.6.2.
These should be fine unless you have method names with `%2F` character like `method1%2F111`. If this is the case then you will need runtime version v1.7.2.
