### ISSUE TITLE
Daprd crashed for race condition of grpc connection pool

### ISSUE THREAD

**Issue by skyao** [dapr/dapr#4688]
## In what area(s)?

/area runtime

## What version of Dapr?

> master

## Expected Behavior

Perf test should pass.

## Actual Behavior

In perf test case (service invoke http) , Daprd crashed for race condition of grpc connection pool.

See page: 
https://github.com/dapr/dapr/actions/runs/2418445782

Download the file [perf_container_logs](https://github.com/dapr/dapr/suites/6737249116/artifacts/257110634) in this page and open the log file tester-7fdf9754fc-vzgq6.daprd.log:

```go
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 563 [running]:
runtime.throw({0x3eabf72?, 0x3a57320?})
	/opt/hostedtoolcache/go/1.18.2/x64/src/runtime/panic.go:992 +0x71 fp=0xc0011f6e78 sp=0xc0011f6e48 pc=0x438471
runtime.mapassign_faststr(0x37117c0, 0xc000ce1c80, {0xc0005bc8a0, 0x2f})
	/opt/hostedtoolcache/go/1.18.2/x64/src/runtime/map_faststr.go:295 +0x38b fp=0xc0011f6ee0 sp=0xc0011f6e78 pc=0x41364b
github.com/dapr/dapr/pkg/grpc.(*connectionPool).Register(0xc000ccf1c0, {0xc0005bc8a0, 0x2f}, 0xc000c52000)
	/home/runner/work/dapr/dapr/pkg/grpc/grpc.go:191 +0x7c fp=0xc0011f6f10 sp=0xc0011f6ee0 pc=0x16f759c
github.com/dapr/dapr/pkg/grpc.(*Manager).GetGRPCConnection(0xc000c99600, {0x45f5be8, 0xc000132008}, {0xc0005bc8a0, 0x2f}, {0xc0007cb248, 0x7}, {0xc00007c00a, 0xa}, 0x0, ...)
	/home/runner/work/dapr/dapr/pkg/grpc/grpc.go:168 +0xfba fp=0xc0011f7238 sp=0xc0011f6f10 pc=0x16f715a
github.com/dapr/dapr/pkg/grpc.(*Manager).GetGRPCConnection-fm({0x45f5be8?, 0xc000132008?}, {0xc0005bc8a0?, 0xc0007cb320?}, {0xc0007cb248?, 0x4176b3?}, {0xc00007c00a?, 0x0?}, 0x3?, 0x0, ...)
	<autogenerated>:1 +0xb6 fp=0xc0011f72b0 sp=0xc0011f7238 pc=0x17999b6
github.com/dapr/dapr/pkg/messaging.(*directMessaging).invokeRemote(0xc0008fa460, {0x45f8620, 0xc000ac8000}, {0xc0007cb248, 0x7}, {0xc00007c00a, 0xa}, {0xc0005bc8a0?, 0x4?}, 0xc00000ea90)
	/home/runner/work/dapr/dapr/pkg/messaging/direct_messaging.go:240 +0xe5 fp=0xc0011f73b0 sp=0xc0011f72b0 pc=0x16dd165
github.com/dapr/dapr/pkg/messaging.(*directMessaging).invokeRemote-fm({0x45f8620?, 0xc000ac8000?}, {0xc0007cb248?, 0x3ea55e2?}, {0xc00007c00a?, 0xc000d3d450?}, {0xc0005bc8a0?, 0x4?}, 0x3520240?)
	<autogenerated>:1 +0x70 fp=0xc0011f7410 sp=0xc0011f73b0 pc=0x16df410
github.com/dapr/dapr/pkg/messaging.(*directMessaging).invokeWithRetry(0xc0008fa460, {0x45f8620, 0xc000ac8000}, 0x3, 0x158ee80?, {{0xc0007cb248, 0x7}, {0xc00007c00a, 0xa}, {0xc0005bc8a0, ...}}, ...)
	/home/runner/work/dapr/dapr/pkg/messaging/direct_messaging.go:202 +0x5ad fp=0xc0011f7568 sp=0xc0011f7410 pc=0x16dc5ed
github.com/dapr/dapr/pkg/messaging.(*directMessaging).Invoke(0xc0008fa460, {0x45f8620, 0xc000ac8000}, {0xc0007cb248?, 0x203000?}, 0xc001080240?)
	/home/runner/work/dapr/dapr/pkg/messaging/direct_messaging.go:134 +0x1e5 fp=0xc0011f7648 sp=0xc0011f7568 pc=0x16dbe85
github.com/dapr/dapr/pkg/http.(*api).onDirectMessage.func1({0x45f8620, 0xc000ac8000})
	/home/runner/work/dapr/dapr/pkg/http/api.go:1014 +0xba fp=0xc0011f7738 sp=0xc0011f7648 pc=0x176f01a
github.com/dapr/dapr/pkg/resiliency.(*NoOp).EndpointPolicy.func1(0x3e743bb?)
	/home/runner/work/dapr/dapr/pkg/resiliency/noop.go:36 +0x27 fp=0xc0011f7758 sp=0xc0011f7738 pc=0x16bbfc7
github.com/dapr/dapr/pkg/http.(*api).onDirectMessage(0xc000d12fc0, 0xc000ac8000)
	/home/runner/work/dapr/dapr/pkg/http/api.go:1013 +0x6f6 fp=0xc0011f78e0 sp=0xc0011f7758 pc=0x176ecb6
github.com/dapr/dapr/pkg/http.(*api).onDirectMessage-fm(0xc000d2b760?)
	<autogenerated>:1 +0x2c fp=0xc0011f7900 sp=0xc0011f78e0 pc=0x177d52c
github.com/fasthttp/router.(*Router).Handler(0xc000554e70, 0xc000ac8000)
	/home/runner/go/pkg/mod/github.com/fasthttp/router@v1.3.8/router.go:427 +0x871 fp=0xc0011f79b0 sp=0xc0011f7900 pc=0x17466f1
github.com/fasthttp/router.(*Router).Handler-fm(0xc00012d020?)
	<autogenerated>:1 +0x2c fp=0xc0011f79d0 sp=0xc0011f79b0 pc=0x177dc8c
github.com/dapr/dapr/pkg/diagnostics.(*httpMetrics).FastHTTPMiddleware.func1(0xc000ac8000)
	/home/runner/work/dapr/dapr/pkg/diagnostics/http_monitoring.go:195 +0x13b fp=0xc0011f7aa8 sp=0xc0011f79d0 pc=0xc6677b
github.com/dapr/dapr/pkg/diagnostics.HTTPTraceMiddleware.func1(0xc000ac8000)
	/home/runner/work/dapr/dapr/pkg/diagnostics/http_tracing.go:56 +0xef fp=0xc0011f7bc0 sp=0xc0011f7aa8 pc=0xc66d2f
github.com/dapr/dapr/pkg/http.(*server).apiLoggingInfo.func1(0xc000ac8000)
	/home/runner/work/dapr/dapr/pkg/http/server.go:222 +0x155 fp=0xc0011f7c40 sp=0xc0011f7bc0 pc=0x177bef5
github.com/valyala/fasthttp.(*Server).serveConn(0xc000857c00, {0x46064f8?, 0xc00000ea38})
	/home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.31.1-0.20211216042702-258a4c17b4f4/server.go:2293 +0x1268 fp=0xc0011f7ec8 sp=0xc0011f7c40 pc=0xbeafe8
github.com/valyala/fasthttp.(*Server).serveConn-fm({0x46064f8?, 0xc00000ea38?})
	<autogenerated>:1 +0x39 fp=0xc0011f7ef0 sp=0xc0011f7ec8 pc=0xbfba79
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc0008501e0, 0xc0006e4a20)
	/home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.31.1-0.20211216042702-258a4c17b4f4/workerpool.go:223 +0xa9 fp=0xc0011f7fa0 sp=0xc0011f7ef0 pc=0xbf7f29
github.com/valyala/fasthttp.(*workerPool).getCh.func1()
	/home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.31.1-0.20211216042702-258a4c17b4f4/workerpool.go:195 +0x38 fp=0xc0011f7fe0 sp=0xc0011f7fa0 pc=0xbf7cb8
runtime.goexit()
	/opt/hostedtoolcache/go/1.18.2/x64/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0011f7fe8 sp=0xc0011f7fe0 pc=0x46b8a1
created by github.com/valyala/fasthttp.(*workerPool).getCh
	/home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.31.1-0.20211216042702-258a4c17b4f4/workerpool.go:194 +0x1b0

```

in dapr/dapr/pkg/grpc/grpc.go:191 : 

```go
func (p *connectionPool) Register(address string, conn *grpc.ClientConn) {
	if oldConn, ok := p.pool[address]; ok {
		// oldConn is not used by pool anymore
		p.Release(oldConn)
	}

	p.pool[address] = conn      // this line is 191 and race condition happens here!
	// conn is used by caller and pool
	// NOTE: pool should also increment referenceCount not to close the pooled connection
	p.referenceCount[conn] = 2
}
```

It seems this issue is related to PR https://github.com/dapr/dapr/pull/4667

**Comment by yaron2** [comment]
Thanks @skyao it looks like we need a lock there. I'll open a PR.

**Comment by skyao** [comment]
@yaron2 I will PR for this to quick fix.

**Comment by skyao** [comment]
To quick fix this issue, I add a write lock for Register method of connectionPool.

```go
	g.lock.Lock()        // add this line
	defer g.lock.Unlock()  // add this line
	g.connectionPool.Register(address, conn)
```

@yaron2 You can merge this PR and let's see if perf test fixed.

**Comment by yaron2** [comment]
> @yaron2 I will PR for this to quick fix.

Ok, mention me for a review.

We need read locks for reading from `p.pool` in `Register` and write locks for assigning a connection on line 191. Same thing for `Release` and `referenceCount`.

**Comment by skyao** [comment]
I still have some suggestion about the usage of the lock, now it's a field in Manager struct:

```go
type Manager struct {
	AppClient      ClientConnCloser
	lock           *sync.RWMutex
	connectionPool *connectionPool
	auth           security.Authenticator
	mode           modes.DaprMode
}
```

Can we move it into the connectionPool struct: 

```go
type connectionPool struct {
	pool           map[string]*grpc.ClientConn
	referenceCount map[*grpc.ClientConn]int
}
```

Then we can get/release the lock in the methods of connectionPool struct with defer, for example:

```go
func (p *connectionPool) Register(address string, conn *grpc.ClientConn) {
        p.lock.Lock()        // add this line
	defer p.lock.Unlock()  // add this line

	if oldConn, ok := p.pool[address]; ok {
		// oldConn is not used by pool anymore
		p.Release(oldConn)
	}

	p.pool[address] = conn
	// conn is used by caller and pool
	// NOTE: pool should also increment referenceCount not to close the pooled connection
	p.referenceCount[conn] = 2
}
```

I suggest to do this refactory because follow code is not safe to release lock if the goroutine panic in the g.connectionPool.Share() method or releaseFactory(conn) method:

```go
		g.lock.RLock()
		if conn, ok := g.connectionPool.Share(address); ok {
			g.lock.RUnlock()

			teardown := releaseFactory(conn)
			return conn, teardown, nil
		}
		g.lock.RUnlock()
```

**Comment by skyao** [comment]
And the share() method of connectionPool is proteced by a Read Lock, but it changed the p.referenceCount[], so there is still a race condition in this share() method: if there are many goroutines to invoke the share() method, all of them can get the read lock and then update the p.referenceCount[] at the same time.

```go
func (p *connectionPool) Share(address string) (*grpc.ClientConn, bool) {
	conn, ok := p.pool[address]
	if !ok {
		return nil, false
	}

	p.referenceCount[conn]++   // here we do write operation with read lock, it is not safe
	return conn, true
}
```

**Comment by skyao** [comment]
There is another risk:


```go
func (g *Manager) GetGRPCConnection(ctx context.Context, address, id string, namespace string, skipTLS, recreateIfExists, sslEnabled bool, customOpts ...grpc.DialOption) (*grpc.ClientConn, func(), error) {
	releaseFactory := func(conn *grpc.ClientConn) func() {
		return func() {
			g.connectionPool.Release(conn) // here we call releaseFactory() method without lock
		}
	}

	// share pooled connection
	if !recreateIfExists {
		g.lock.RLock()
		if conn, ok := g.connectionPool.Share(address); ok {
			g.lock.RUnlock()     // we unlock here

			teardown := releaseFactory(conn)               // here we call releaseFactory() method without lock
			return conn, teardown, nil
		}
		g.lock.RUnlock()
```

So Release() method of connectionPool is called without lock:

```go
func (p *connectionPool) Release(conn *grpc.ClientConn) {
	if _, ok := p.referenceCount[conn]; !ok {
		return
	}

	p.referenceCount[conn]--

	// for concurrent use, connection is closed after all callers release it
	if p.referenceCount[conn] <= 0 {
		conn.Close()
	}
}
```

I'm not sure if it is safe since p.referenceCount[] is also a map.  Is the ++ / -- opeations are safe to map[]?

**Comment by yaron2** [comment]
Yeah we need to `Lock` on incrementing in `Share`. Also, `Release` is returning the teardown method and that is used concurrently:

```go
func (p *connectionPool) Release(conn *grpc.ClientConn) {
	if _, ok := p.referenceCount[conn]; !ok {
		return
	}

	p.referenceCount[conn]--

	// for concurrent use, connection is closed after all callers release it
	if p.referenceCount[conn] <= 0 {
		conn.Close()
	}
}
```

We have to put read/write locks inside of `Release`.

**Comment by yaron2** [comment]
@skyao we are writing concurrently about the same things :D

**Comment by yaron2** [comment]
> I'm not sure if it is safe since p.referenceCount[] is also a map. Is the ++ / -- opeations are safe to map[]?

No, they're not.

**Comment by skyao** [comment]
Yes, I did a test and verified that ++/-- is not safe:

```go
package main

var c = map[string]int{}

func main() {
	for i := 0; i < 100; i++ {
		go doTestIncrease()
		go doTestDecrease()
	}
}

func doTestIncrease() {
	for {
		c["key"]++
	}
}

func doTestDecrease() {
	for {
		c["key"]--
	}
}
```

It crashed for: 

```
fatal error: concurrent map writes

goroutine 8 [running]:
runtime.throw({0x46a92f?, 0x0?})
	/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc000087738 sp=0xc000087708 pc=0x430e31
runtime.mapassign_faststr(0x0?, 0x0?, {0x468cee, 0x3})
	/usr/local/go/src/runtime/map_faststr.go:212 +0x417 fp=0xc0000877a8 sp=0xc000087738 pc=0x40f537
main.doTestDecrease()
	/home/sky/work/code/dapr-fork/dapr/pkg/health/main/aaaaa.go:22 +0x37 fp=0xc0000877e0 sp=0xc0000877a8 pc=0x45c097
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0000877e8 sp=0xc0000877e0 pc=0x458fc1
created by main.main
	/home/sky/work/code/dapr-fork/dapr/pkg/health/main/aaaaa.go:10 +0x5c
```

So we need to update all the code to handle p.referenceCount[].

**Comment by yaron2** [comment]
Yep. Do you want to do it or shall I?

**Comment by yaron2** [comment]
Ok

**Comment by yaron2** [comment]
@skyao Do the perf tests pass now?
