### ISSUE TITLE
panic in grpc proto message v1 client

### ISSUE THREAD

**Issue by BenLocal** [dapr/dapr#4865]
I want to use nacos as nameresolution sever, but nacos-sdk-go use grpc proto message v1 to connect to the nacos server,
The following panic appear：
```
panic: interface conversion: *grpc.Payload is not protoreflect.ProtoMessage: missing method ProtoReflect

goroutine 1 [running]:
github.com/dapr/dapr/pkg/grpc/proxy/codec.(*protoCodec).Marshal(0xd349d1, {0x633c980, 0xc000a57680})
	d:/master/dev/dapr/pkg/grpc/proxy/codec/codec.go:86 +0x72
github.com/dapr/dapr/pkg/grpc/proxy/codec.(*Proxy).Marshal(0xc0001e8280, {0x633c980, 0xc000a57680})
	d:/master/dev/dapr/pkg/grpc/proxy/codec/codec.go:61 +0x13c
google.golang.org/grpc.encode({0x25054929418, 0xc0001e8280}, {0x633c980, 0xc000a57680})
	E:/go/pkg/mod/google.golang.org/grpc@v1.47.0/rpc_util.go:594 +0xba
google.golang.org/grpc.prepareMsg({0x633c980, 0xc000a57680}, {0x25054929418, 0xc0001e8280}, {0x0, 0x0}, {0x0, 0x0})
	E:/go/pkg/mod/google.golang.org/grpc@v1.47.0/stream.go:1641 +0x20e
google.golang.org/grpc.(*clientStream).SendMsg(0xc000f88360, {0x633c980, 0xc000a57680})
	E:/go/pkg/mod/google.golang.org/grpc@v1.47.0/stream.go:813 +0x245
google.golang.org/grpc.invoke({0x6b04760, 0xc000076110}, {0x6609ae2, 0x10}, {0x633c980, 0xc000a57680}, {0x633c980, 0xc000a576b0}, 0xc000edfc00, {0xc000f8d0a0, ...})
	E:/go/pkg/mod/google.golang.org/grpc@v1.47.0/call.go:70 +0x17c
google.golang.org/grpc.(*ClientConn).Invoke(0xc000edfc00, {0x6b04760, 0xc000076110}, {0x6609ae2, 0x10}, {0x633c980, 0xc000a57680}, {0x633c980, 0xc000a576b0}, {0xc000f8d0a0, ...})
	E:/go/pkg/mod/google.golang.org/grpc@v1.47.0/call.go:37 +0x231
github.com/nacos-group/nacos-sdk-go/v2/api/grpc.(*requestClient).Request(0xc00010d970, {0x6b04760, 0xc000076110}, 0xc000a57680, {0x0, 0x0, 0x0})
	E:/go/pkg/mod/github.com/nacos-group/nacos-sdk-go/v2@v2.0.3/api/grpc/nacos_grpc_service.pb.go:307 +0x10f
github.com/nacos-group/nacos-sdk-go/v2/common/remote/rpc.serverCheck({0x6ad5be0, 0xc00010d970})
	E:/go/pkg/mod/github.com/nacos-group/nacos-sdk-go/v2@v2.0.3/common/remote/rpc/grpc_client.go:204 +0x12f
github.com/nacos-group/nacos-sdk-go/v2/common/remote/rpc.(*GrpcClient).connectToServer(0xc00010d848, {{0x65f3d11, 0xa}, 0x2290})
	E:/go/pkg/mod/github.com/nacos-group/nacos-sdk-go/v2@v2.0.3/common/remote/rpc/grpc_client.go:126 +0x17c
github.com/nacos-group/nacos-sdk-go/v2/common/remote/rpc.(*RpcClient).Start(0xc000ed4780)
	E:/go/pkg/mod/github.com/nacos-group/nacos-sdk-go/v2@v2.0.3/common/remote/rpc/rpc_client.go:215 +0x48c
github.com/nacos-group/nacos-sdk-go/v2/clients/naming_client/naming_grpc.NewNamingGrpcProxy({0x1388, 0x0, 0x1388, {0x666fbcf, 0x24}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...}, ...)
	E:/go/pkg/mod/github.com/nacos-group/nacos-sdk-go/v2@v2.0.3/clients/naming_client/naming_grpc/naming_grpc_proxy.go:71 +0x45d
github.com/nacos-group/nacos-sdk-go/v2/clients/naming_client.NewNamingProxyDelegate({0x1388, 0x0, 0x1388, {0x666fbcf, 0x24}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...}, ...)
	E:/go/pkg/mod/github.com/nacos-group/nacos-sdk-go/v2@v2.0.3/clients/naming_client/naming_proxy_delegate.go:51 +0x2f8
github.com/nacos-group/nacos-sdk-go/v2/clients/naming_client.NewNamingClient({0x6b0f038, 0xc000099d40})
	E:/go/pkg/mod/github.com/nacos-group/nacos-sdk-go/v2@v2.0.3/clients/naming_client/naming_client.go:72 +0x5de
github.com/nacos-group/nacos-sdk-go/v2/clients.NewNamingClient({0xc000d18b00, {0xc000f94d40, 0x1, 0x1}})
	E:/go/pkg/mod/github.com/nacos-group/nacos-sdk-go/v2@v2.0.3/clients/client_factory.go:61 +0x10d
github.com/dapr/components-contrib/nameresolution/nacos.(*resolver).Init(0xc000f92c00, {0xc000f9a990, {0x5df4de0, 0xc000eea5d0}})
	d:/master/dev/components-contrib/nameresolution/nacos/nacos.go:134 +0x23d
github.com/dapr/dapr/pkg/runtime.(*DaprRuntime).initNameResolution(0xc000c7f800)
	d:/master/dev/dapr/pkg/runtime/runtime.go:1661 +0xa87
github.com/dapr/dapr/pkg/runtime.(*DaprRuntime).initRuntime(0xc000c7f800, 0xc000d88460)
	d:/master/dev/dapr/pkg/runtime/runtime.go:372 +0x5ef
github.com/dapr/dapr/pkg/runtime.(*DaprRuntime).Run(0xc000c7f800, {0xc000a9ff28, 0x9, 0x9})
	d:/master/dev/dapr/pkg/runtime/runtime.go:288 +0x329
main.main()
	d:/master/dev/dapr/cmd/daprd/main.go:191 +0x5465
```

**Comment by yaron2** [comment]
What version of Dapr are you using?

**Comment by BenLocal** [comment]
master branch code
All grpc client will use `"github.com/dapr/dapr/pkg/grpc/proxy/codec".protoCodec` in dapr, except dapr self, other third package’s grpc client too.
but `"github.com/dapr/dapr/pkg/grpc/proxy/codec".protoCodec` only supports converting proto v2 message(`"google.golang.org/protobuf/proto".Message`)
If use proto  v1 message(`"github.com/golang/protobuf/proto".Message`) in grpc client, panic will appear

**Comment by BenLocal** [comment]
I think, `"github.com/dapr/dapr/pkg/grpc/proxy/codec".protoCodec` needs to support proto v1 message

pkg\grpc\proxy\codec\codec.go line89:
``` go
func (*protoCodec) Marshal(v interface{}) ([]byte, error) {
	switch t := v.(type) {
	case proto.Message:
		return proto.Marshal(v.(proto.Message))
	case protoV1.Message:
		return protoV1.Marshal(v.(protoV1.Message))
	default:
		return nil, fmt.Errorf("failed to marshal, message is %T, want proto.Message", t)
	}
}

func (*protoCodec) Unmarshal(data []byte, v interface{}) error {
	switch t := v.(type) {
	case proto.Message:
		return proto.Unmarshal(data, v.(proto.Message))
	case protoV1.Message:
		return protoV1.Unmarshal(data, v.(protoV1.Message))
	default:
		return fmt.Errorf("failed to unmarshal, message is %T, want proto.Message", t)
	}

}
```
