### ISSUE TITLE
Mongodb state-store not working

### ISSUE THREAD

**Issue by bencz** [dapr/dapr#5118]
When creating/configuring the state-store as mongodb, writing and initializing works correctly, but when trying to read some information from the state-store, a serialization error occurs.

Another point, when comparing the creation of the actors' reminders partitions in other databases, such as PgSQL, in mongo db, every time the application is restarted, more N partitions of the reminders are created

## Expected Behavior

Return state-store information

## Actual Behavior

Exception when trying to deserialize information

```
[18:06:10 ERR] An unhandled exception has occurred while executing the request.
System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.actorDetailsId | LineNumber: 0 | BytePositionInLine: 21.
 ---> System.FormatException: Either the JSON value is not in a supported format, or is out of bounds for an Int32.
   at System.Text.Json.Utf8JsonReader.GetInt32()
   at System.Text.Json.Serialization.Converters.Int32Converter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Dapr.Actors.Runtime.DaprStateProvider.TryLoadStateAsync[T](String actorType, String actorId, String stateName, CancellationToken cancellationToken)
   at Dapr.Actors.Runtime.ActorStateManager.TryGetStateAsync[T](String stateName, CancellationToken cancellationToken)
   at DaprMongoDbBug.API.Actors.BugStateStoreActor.GetActorDetails() in /src/src/DaprMongoDbBug.API/Actors/BugStateStoreActorSample.cs:line 36
   at DaprMongoDbBug.API.Actors.BugStateStoreActor.ExecuteSampleReminder1() in /src/src/DaprMongoDbBug.API/Actors/BugStateStoreActorSample.cs:line 50
   at DaprMongoDbBug.API.Actors.BugStateStoreActor.ReceiveReminderAsync(String reminderName, Byte[] state, TimeSpan dueTime, TimeSpan period) in /src/src/DaprMongoDbBug.API/Actors/BugStateStoreActorSample.cs:line 71
   at Dapr.Actors.Runtime.ActorManager.<>c__DisplayClass24_0.<<FireReminderAsync>g__RequestFunc|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Dapr.Actors.Runtime.ActorManager.DispatchInternalAsync[T](ActorId actorId, ActorMethodContext actorMethodContext, Func`3 actorFunc, CancellationToken cancellationToken)
   at Dapr.Actors.Runtime.ActorManager.DispatchInternalAsync[T](ActorId actorId, ActorMethodContext actorMethodContext, Func`3 actorFunc, CancellationToken cancellationToken)
   at Dapr.Actors.Runtime.ActorManager.DispatchInternalAsync[T](ActorId actorId, ActorMethodContext actorMethodContext, Func`3 actorFunc, CancellationToken cancellationToken)
   at Dapr.Actors.Runtime.ActorManager.FireReminderAsync(ActorId actorId, String reminderName, Stream requestBodyStream, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Builder.ActorsEndpointRouteBuilderExtensions.<>c__DisplayClass4_0.<<MapReminderEndpoint>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

## Steps to Reproduce the Problem

Change the state-store host/server on "dapr/components/daprmongodbbug-statestore.yaml"
I've attached an example ASP.Net core project, just run docker-compose (note there is a docker compose override)

Execute the sample project running the docker-compose,
Navigate to: http://127.0.0.1:5200/swagger/index.html
Execute the endpoint: createActor sending some paramters on model ( the field id is the actor id )
After this, try to read the actor details on the "GET" endpoint

[DaprMongoDbBug.zip](https://github.com/dapr/components-contrib/files/9396651/DaprMongoDbBug.zip)

**Comment by berndverst** [comment]
@artursouza please rename to -- HTTP BingingRequest JSON unmarshaling does not retain integers types.

**Comment by berndverst** [comment]
gRPC is not impacted by this. As such we will be migrating the remaining SDKs to use the gRPC APIs for actors as soon as possible. We will migrate the .NET SDK in time for the 1.9 release.

**Comment by berndverst** [comment]
Quick update here:

If the content Type is specified as `application/JSON` then numbers will become double/float/decimal. That is in line with the JSON spec.

This will still happen with gRPC
https://github.com/dapr/dapr/blob/master/pkg/grpc/api.go#L768

For other content types there is no concern here.

Note that in the case of HTTP the HTTP request JSON unmarshalling always unmarshalled any data value also, which is where the number data type was lost, regardless of content type.
https://github.com/dapr/dapr/blob/master/pkg/http/api.go#L1268

I made a test using the Python SDK using gRPC + Mongo DB state store which shows that gRPC works is expected, with the caveat that in the case of explicit JSON content type integers will become decimals.

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/4535280/188993856-f777bc97-abbb-409d-835e-29e4e5278f8c.png)

**Comment by berndverst** [comment]
@bencz from a Dapr perspective we can retain the data type by storing a value as a string (the SDK will be able to deserialize things correctly), or we lose the data type when inserting a JSON document into Mongo - because the JSON spec doesn't distinguish between integers and decimals.

In virtually all state stores we save the entire document as a string.

**Comment by artursouza** [comment]
> Quick update here:
> 
> If the content Type is specified as `application/json` then numbers will become double/float/decimal. That is in line with the JSON spec.
> 
> This will still happen with gRPC https://github.com/dapr/dapr/blob/master/pkg/grpc/api.go#L768
> 
> For other content types there is no concern here.
> 
> Note that in the case of HTTP the HTTP request JSON unmarshalling always unmarshalled any data value also, which is where the number data type was lost, regardless of content type. https://github.com/dapr/dapr/blob/master/pkg/http/api.go#L1268
> 
> I made a test using the Python SDK using gRPC + Mongo DB state store which shows that gRPC works is expected, with the caveat that in the case of explicit JSON content type integers will become decimals.
> 
> ![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/4535280/188993856-f777bc97-abbb-409d-835e-29e4e5278f8c.png)

Wait. If the `value` is saved as string, then it will not be queriable right?

**Comment by berndverst** [comment]
> > Quick update here:
> > If the content Type is specified as `application/json` then numbers will become double/float/decimal. That is in line with the JSON spec.
> > This will still happen with gRPC https://github.com/dapr/dapr/blob/master/pkg/grpc/api.go#L768
> > For other content types there is no concern here.
> > Note that in the case of HTTP the HTTP request JSON unmarshalling always unmarshalled any data value also, which is where the number data type was lost, regardless of content type. https://github.com/dapr/dapr/blob/master/pkg/http/api.go#L1268
> > I made a test using the Python SDK using gRPC + Mongo DB state store which shows that gRPC works is expected, with the caveat that in the case of explicit JSON content type integers will become decimals.
> > ![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/4535280/188993856-f777bc97-abbb-409d-835e-29e4e5278f8c.png)
> 
> Wait. If the `value` is saved as string, then it will not be queriable right? So, we want JSON as the user experience it seems.

Sadly that is correct @artursouza.

The only way around this is for us to introduce some sort of type annotations which a component can then use to coerce the data into the correct types. That would need to be implemented by the SDKs and then each component (e.g. MongoDB) would need to use this information.

Perhaps on the SetRequest the metadata could be `{'dataTypes': {'somekey.somesubkey': 'int'}}`. This should be populated by the SDKs whenever an integer or long is used! Then the components can use this metadata to do the type conversion.

What do you think?

**Comment by artursouza** [comment]
This is an interesting idea but I am concerning about getting a strict contract for serialization, making the SDKs to basically become a serializer.

What about we support BSON too and then the SDKs would use BSON to avoid this problem?

**Comment by berndverst** [comment]
> This is an interesting idea but I am concerning about getting a strict contract for serialization, making the SDKs to basically become a serializer.
> 
> What about we support BSON too and then the SDKs would use BSON to avoid this problem?

Yes supporting BSON in SDKs, Runtime and Components works too - that's a big effort for sure however.

**Comment by artursouza** [comment]
> > This is an interesting idea but I am concerning about getting a strict contract for serialization, making the SDKs to basically become a serializer.
> > What about we support BSON too and then the SDKs would use BSON to avoid this problem?
> 
> Yes supporting BSON in SDKs, Runtime and Components works too - that's a big effort for sure however.

We can split the work per SDK but it would be the right thing to do.

**Comment by berndverst** [comment]
> This is an interesting idea but I am concerning about getting a strict contract for serialization, making the SDKs to basically become a serializer.
> 
> What about we support BSON too and then the SDKs would use BSON to avoid this problem?

Personally I think this type hint I suggested is only necessary for override from the default JSON unmarshalling. It would only be necessary for numbers and can be specified manually or automatically via the SDKs.

Most components do not support BSON and it feels like too much effort to add BSON to all SDKs and runtime just for MongoDB. Even RethinkDB doesn't support BSON.

**Comment by artursouza** [comment]
My proposal is to use BSON as the transport protocol all the way to component, then the component can decide if it can save as-is or convert to JSON.

**Comment by berndverst** [comment]
> My proposal is to use BSON as the transport protocol all the way to component, then the component can decide if it can save as-is or convert to JSON.

That's fine. Just want to be clear on the effort here:

1. Every SDK must now take a dependency on a BSON SDK / library. If content type is specified as `application/bson` then the SDK must serialize the data to the native BSON binary encoding.
2. The runtime must leave `application/bson` contentType in tact without any modifications -- that's probably the default behavior today, but we need to check.
3. Each component must add a special case for `application/bson` and convert it to a compatible type where bson is not supported natively.

**Comment by WolfspiritM** [comment]
Hi,

What's the state of this?

I had a long time figuring out why my application breaks if the actor isn't called for a while.
The Problem is that it works fine for an hour, only if the actor is recreated it stops working.
Especially as I use another component for state in development I didn't notice it.

I expected my application to work the same with redis and mongodb (which is why I used dapr) but this doesn't seem to be the case at the moment.
