### ISSUE TITLE
Error when Dapr runs two services locally: 'Refreshing mDNS addresses for app id uploader timed out'

### ISSUE THREAD

**Issue by iamsourabh-in** [dapr/dapr#5430]
## Expected Behavior

I have Two Service `Processor` and `Uploader`. Processor Service can reach out to uploader for getting any service details.

The Processor Service should be able to invoke method in Uploader Service

## Actual Behavior

Getting an error after trying Multiple Routes and Scenarios. Processor Service is unable to Invoke any method in Uploader Service

`An exception occurred while invoking method: 'uploads' on app-id: 'uploader'`

## Steps to Reproduce the Problem

Enable Dapr:

```sh
dapr init
```

The Uploader Service has an endpoint `http://<host>:<port>/uploads`

```c
 [ApiController]
 [Route("[controller]")]
 public class UploadsController : ControllerBase
 {
    [HttpGet]
    public async Task<IActionResult> GetAll()
    {
        var response = await _storageService.GetAllVideos(new Services.Models.GetAllVideosRequestModel(){
          BucketName = "*****",
          BucketFolder ="****"   
        });
        return Ok(response);
     }
  }

// output
{
    "videos": [
        {
            "lastModified": "2022-10-09T00:03:17+05:30",
            "size": 3288367,
            "key": "files/4303ckbt.cil.mp4"
        },
        {
            "lastModified": "2022-10-08T22:11:26+05:30",
            "size": 3288367,
            "key": "filesubpmk1a3.hwd.mp4"
        }
    ]
}

```
Also, Note, calling directly through `postman` the `dapr` endpoint do return the response. It's only the App not able to call 

![image](https://user-images.githubusercontent.com/22702292/197148407-47ad3fc7-7c8c-4513-8511-10fe6da27a06.png)

The code for Processor Service to invoke the uploader service which gives an error:

```c
 try
 {             
   CancellationTokenSource source = new CancellationTokenSource();
   var videos = await _daprClient.InvokeMethodAsync<UploadApiVideoModel>(HttpMethod.Get,"uploader", "uploads", source.Token);
   _logger.LogInformation("Video" + videos.Videos[0].Key);
              
 }
 catch (System.Exception ex)
 {
    _logger.LogInformation(" Calling Error " + ex.Message);
  }
```

Now for running it locally:

Uploader Service
```sh
dapr run --app-port 2000 --app-id uploader --app-protocol http --dapr-http-port 2500 --components-path ../../dapr/components -- dotnet run
```
Processor Service
```sh
dapr run --app-port 3000 --app-id processor --app-protocol http --dapr-http-port 3500 --components-path ../../dapr/components -- dotnet run
```

Exception Received in `Processor service`

![image](https://user-images.githubusercontent.com/22702292/197150863-59754d31-165a-4aef-9ac8-5520a8235050.png)

## Other Details 

I also tried using the CreateInvokeHttpClient Method in dapr.
```c
var httpClient = DaprClient.CreateInvokeHttpClient("uploader");
await httpClient.PostAsJsonAsync("/uploads");
```

I also tried enabling `mtls` and then try with `--app-ssl` still no luck.

I also tried it running in K8s still no luck.

I tried with log level debug and found the below loga for `Uploader Service`
Logs

Processor Service
```sh
== APP == info: Processor.Api.Controllers.ProcessorController[0]
== APP ==       3288367
== APP == info: Processor.Api.Controllers.ProcessorController[0]
== APP ==       08-10-2022 18:33:17
== APP == info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
== APP ==       Executing OkObjectResult, writing value of type 'Processor.Api.Services.Models.GetVideoDetailsResponseModel'.
== APP == info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
== APP ==       Executed action Processor.Api.Controllers.ProcessorController.Get (Processor.Api) in 34916.6472ms
== APP == info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
== APP ==       Executed endpoint 'Processor.Api.Controllers.ProcessorController.Get (Processor.Api)'
== APP == info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
== APP ==       Request finished HTTP/1.1 GET http://localhost:3000/Processor?key=files/4303ckbt.cil.mp4&bucketName=evolution-video-uploads application/json 32 - 200 - application/json;+charset=utf-8 34940.3050ms
time="2022-10-29T01:55:12.3504046+05:30" level=debug msg="Refreshing mDNS addresses for app id uploader timed out." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.0
time="2022-10-29T01:55:12.3509222+05:30" level=debug msg="mDNS browse for app id uploader timed out." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.0
time="2022-10-29T01:55:42.3602209+05:30" level=debug msg="Refreshing all mDNS addresses." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.0
time="2022-10-29T01:55:42.3607271+05:30" level=debug msg="0 IPv4 address(es) expired for app id uploader." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.0
time="2022-10-29T01:55:42.3607271+05:30" level=debug msg="Refreshing mDNS addresses for app id uploader." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.0
time="2022-10-29T01:55:42.4014316+05:30" level=debug msg="mDNS response for app id uploader received." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.0
time="2022-10-29T01:55:42.4036351+05:30" level=debug msg="Adding IPv4 address 192.168.1.11:61484 for app id uploader cache entry." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.0
time="2022-10-29T01:55:45.3636849+05:30" level=debug msg="mDNS browse for app id uploader timed out." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.0
time="2022-10-29T01:55:45.3636849+05:30" level=debug msg="Refreshing mDNS addresses for app id uploader timed out." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.0
== APP == info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
== APP ==       Request starting HTTP/1.1 GET http://localhost:3000/Processor?key=files/4303ckbt.cil.mp4&bucketName=evolution-video-uploads application/json 32
== APP == info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
== APP ==       Executing endpoint 'Processor.Api.Controllers.ProcessorController.Get (Processor.Api)'
== APP == info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
== APP ==       Route matched with {action = "Get", controller = "Processor"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get(System.String, System.String) on controller Processor.Api.Controllers.ProcessorController (Processor.Api).  
== APP == info: Processor.Api.Controllers.ProcessorController[0]
== APP ==       been here
time="2022-10-29T01:56:07.2360792+05:30" level=debug msg="found mDNS IPv4 address in cache: 192.168.1.11:61484" app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.0
== APP == info: Processor.Api.Controllers.ProcessorController[0]
== APP ==       ERROR An exception occurred while invoking method: '/uploads' on app-id: 'uploader'
== APP == info: Processor.Api.Controllers.ProcessorController[0]
== APP ==          at Dapr.Client.DaprClientGrpc.InvokeMethodWithResponseAsync(HttpRequestMessage request, CancellationToken cancellationToken)
== APP ==          at Dapr.Client.DaprClientGrpc.InvokeMethodAsync[TResponse](HttpRequestMessage request, CancellationToken cancellationToken)
== APP ==          at Processor.Api.Controllers.ProcessorController.Get(String key, String bucketName) in D:\Work\git_space\cloud-first-approach\Evolution.Processor\src\Processor.Api\Controllers\ProcessorController.cs:line 56
== APP == info: Processor.Api.Controllers.ProcessorController[0]
== APP ==          at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
== APP ==          at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)   
== APP ==          at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
== APP ==          at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
== APP ==          at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)      
== APP ==          at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
== APP ==          at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
== APP ==          at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)  
== APP ==          at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
== APP ==          at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
== APP ==          at Dapr.Client.DaprClientGrpc.InvokeMethodWithResponseAsync(HttpRequestMessage request, CancellationToken cancellationToken)
== APP == info: Processor.Api.Controllers.ProcessorController[0]
== APP ==       3288367
== APP == info: Processor.Api.Controllers.ProcessorController[0]
== APP ==       08-10-2022 18:33:17
== APP == info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
== APP ==       Executing OkObjectResult, writing value of type 'Processor.Api.Services.Models.GetVideoDetailsResponseModel'.
== APP == info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
== APP ==       Executed action Processor.Api.Controllers.ProcessorController.Get (Processor.Api) in 310.8803ms
== APP == info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
== APP ==       Executed endpoint 'Processor.Api.Controllers.ProcessorController.Get (Processor.Api)'
== APP == info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
== APP ==       Request finished HTTP/1.1 GET http://localhost:3000/Processor?key=files/4303ckbt.cil.mp4&bucketName=evolution-video-uploads application/json 32 - 200 - application/json;+charset=utf-8 312.0882ms
time="2022-10-29T01:56:15.3683511+05:30" level=debug msg="Refreshing all mDNS addresses." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.0
time="2022-10-29T01:56:15.3690387+05:30" level=debug msg="0 IPv4 address(es) expired for app id uploader." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.0
time="2022-10-29T01:56:15.3690387+05:30" level=debug msg="Refreshing mDNS addresses for app id uploader." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.0
time="2022-10-29T01:56:15.3948084+05:30" level=debug msg="mDNS response for app id uploader received." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.0
````

I did notice the logs for processor service showing when running in log level debug mode.

`Refreshing mDNS addresses for app id uploader timed out`

Any idea what can cause this ?

Few Version details

`.Net Core: net6.0`
`dapr ver : 1.9.0
`Dapr placement pod on Docker `
`Dapr nuget Client : 1.9.0`

`System : Windwos 11`

Thanks

**Comment by olitomlinson** [comment]
@iamsourabh-in

dapr 1.9.1 contains a hotfix for mDNS issues. Probably worth upgrading? https://github.com/dapr/dapr/releases/tag/v1.9.1

**Comment by iamsourabh-in** [comment]
@olitomlinson - Tried the same a suggested. The issue still persists.

Uninstalled the placement -> install the new version 1.9.1

```sh
C:\Users\Sourabh>dapr -v
CLI version: 1.8.1
Runtime version: 1.9.1

C:\Users\Sourabh>dapr list
  APP ID     HTTP PORT  GRPC PORT  APP PORT  COMMAND     AGE  CREATED              PID
  uploader   2500       53090      2000      dotnet run  6m   2022-10-30 15:20.33  12908
  processor  3500       62521      3000      dotnet run  4m   2022-10-30 15:22.38  20016

```

New Logs from version 1.9.1

```
time="2022-10-30T15:23:38.8863437+05:30" level=debug msg="Refreshing all mDNS addresses." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.1
time="2022-10-30T15:23:38.8868519+05:30" level=debug msg="no mDNS apps to refresh." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.1
== APP == info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
== APP ==       Request starting HTTP/1.1 GET http://localhost:3000/Processor?key=files/4303ckbt.cil.mp4&bucketName=evolution-video-uploads application/json 32
== APP == info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
== APP ==       Executing endpoint 'Processor.Api.Controllers.ProcessorController.Get (Processor.Api)'
== APP == info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
== APP ==       Route matched with {action = "Get", controller = "Processor"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get(System.String, System.String) on controller Processor.Api.Controllers.ProcessorController (Processor.Api).        
== APP == info: AWSSDK[0]
== APP ==       Found AWS credentials for the profile dev_admin_developer_cache
== APP == info: Processor.Api.Controllers.ProcessorController[0]
== APP ==       been here
time="2022-10-30T15:23:45.0133682+05:30" level=debug msg="no mDNS address found in cache, browsing network for app id uploader" app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.1
time="2022-10-30T15:23:45.0133682+05:30" level=debug msg="Browsing for first mDNS address for app id uploader" app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.1
time="2022-10-30T15:23:45.0765772+05:30" level=debug msg="mDNS response for app id uploader received." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.1
time="2022-10-30T15:23:45.0844498+05:30" level=debug msg="Adding IPv4 address 192.168.1.11:53095 for app id uploader cache entry." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.1
time="2022-10-30T15:23:45.085779+05:30" level=debug msg="mDNS browse for app id uploader canceled." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.1
time="2022-10-30T15:23:45.085779+05:30" level=debug msg="Browsing for first mDNS address for app id uploader canceled." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.1
time="2022-10-30T15:23:45.0926341+05:30" level=debug msg="Refreshing mDNS addresses for app id uploader." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.1
time="2022-10-30T15:23:45.1504635+05:30" level=debug msg="mDNS response for app id uploader received." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.1
time="2022-10-30T15:23:45.1516066+05:30" level=debug msg="Adding IPv4 address 192.168.1.11:53095 for app id uploader cache entry." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.1
== APP == info: Processor.Api.Controllers.ProcessorController[0]
== APP ==       ERROR An exception occurred while invoking method: '/uploads' on app-id: 'uploader'
== APP == info: Processor.Api.Controllers.ProcessorController[0]
== APP ==          at Dapr.Client.DaprClientGrpc.InvokeMethodWithResponseAsync(HttpRequestMessage request, CancellationToken cancellationToken)
== APP ==          at Dapr.Client.DaprClientGrpc.InvokeMethodAsync[TResponse](HttpRequestMessage request, CancellationToken cancellationToken)
== APP ==          at Processor.Api.Controllers.ProcessorController.Get(String key, String bucketName) in D:\Work\git_space\cloud-first-approach\Evolution.Processor\src\Processor.Api\Controllers\ProcessorController.cs:line 56
== APP == info: Processor.Api.Controllers.ProcessorController[0]
== APP ==          at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
== APP ==          at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)      
== APP ==          at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
== APP ==          at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
== APP ==          at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
== APP ==          at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
== APP ==          at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
== APP ==          at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)     
== APP ==          at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
== APP ==          at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
== APP ==          at Dapr.Client.DaprClientGrpc.InvokeMethodWithResponseAsync(HttpRequestMessage request, CancellationToken cancellationToken)
== APP == info: Processor.Api.Controllers.ProcessorController[0]
== APP ==       3288367
== APP == info: Processor.Api.Controllers.ProcessorController[0]
== APP ==       08-10-2022 18:33:17
== APP == info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
== APP ==       Executing OkObjectResult, writing value of type 'Processor.Api.Services.Models.GetVideoDetailsResponseModel'.
== APP == info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
== APP ==       Executed action Processor.Api.Controllers.ProcessorController.Get (Processor.Api) in 884.5557ms
== APP == info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
== APP ==       Executed endpoint 'Processor.Api.Controllers.ProcessorController.Get (Processor.Api)'
== APP == info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
== APP ==       Request finished HTTP/1.1 GET http://localhost:3000/Processor?key=files/4303ckbt.cil.mp4&bucketName=evolution-video-uploads application/json 32 - 200 - application/json;+charset=utf-8 926.0481ms
time="2022-10-30T15:23:48.0966021+05:30" level=debug msg="Refreshing mDNS addresses for app id uploader timed out." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.1
time="2022-10-30T15:23:48.0966021+05:30" level=debug msg="mDNS browse for app id uploader timed out." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.1
time="2022-10-30T15:24:15.0943878+05:30" level=debug msg="Refreshing all mDNS addresses." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.1
time="2022-10-30T15:24:15.0943878+05:30" level=debug msg="0 IPv4 address(es) expired for app id uploader." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.1
time="2022-10-30T15:24:15.0948972+05:30" level=debug msg="Refreshing mDNS addresses for app id uploader." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.1
time="2022-10-30T15:24:15.1179712+05:30" level=debug msg="mDNS response for app id uploader received." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.1
time="2022-10-30T15:24:15.1192904+05:30" level=debug msg="Adding IPv4 address 192.168.1.11:53095 for app id uploader cache entry." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.1
time="2022-10-30T15:24:18.1083203+05:30" level=debug msg="mDNS browse for app id uploader timed out." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.1
time="2022-10-30T15:24:18.1083203+05:30" level=debug msg="Refreshing mDNS addresses for app id uploader timed out." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.1
time="2022-10-30T15:24:45.100639+05:30" level=debug msg="Refreshing all mDNS addresses." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.1
time="2022-10-30T15:24:45.101144+05:30" level=debug msg="0 IPv4 address(es) expired for app id uploader." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.1
time="2022-10-30T15:24:45.101144+05:30" level=debug msg="Refreshing mDNS addresses for app id uploader." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.1
time="2022-10-30T15:24:45.1278912+05:30" level=debug msg="mDNS response for app id uploader received." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.1
time="2022-10-30T15:24:45.1284662+05:30" level=debug msg="Adding IPv4 address 192.168.1.11:53095 for app id uploader cache entry." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.1
time="2022-10-30T15:24:48.1047459+05:30" level=debug msg="mDNS browse for app id uploader timed out." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.1
time="2022-10-30T15:24:48.1047459+05:30" level=debug msg="Refreshing mDNS addresses for app id uploader timed out." app_id=processor instance=DESKTOP-FIUUHBV scope=dapr.contrib type=log ver=1.9.1
```

**Comment by iamsourabh-in** [comment]
@olitomlinson - The logs from the Uploader Service  (the service receiving the request)

When running AspNetCore in Debug, was able to get some insights, but still not able to invoke the method.

Seems to be a TLS Issue.

The dapr dashboard shows the below status

![image](https://user-images.githubusercontent.com/22702292/198873365-1af4d8a9-e802-41af-aad4-f9c509a3350f.png)


```sh
== APP == dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[1]
== APP ==       Connection id "0HMLQBQFRB300" started.
== APP == info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
== APP ==       Request starting HTTP/1.1 GET http://127.0.0.1:2000/uploads - -
== APP == dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1001]
== APP ==       1 candidate(s) found for the request path '/uploads'
== APP == dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1005]
== APP ==       Endpoint 'Uploader.Api.Controllers.UploadsController.GetAll (Uploader.Api)' with route pattern 'Uploads' is valid for the request path '/uploads'
== APP == dbug: Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware[1]
== APP ==       Request matched endpoint 'Uploader.Api.Controllers.UploadsController.GetAll (Uploader.Api)'
== APP == dbug: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[15]
== APP ==       Static files was skipped as the request already matched an endpoint.
== APP == dbug: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[1]
== APP ==       Redirecting to 'https://127.0.0.1:2443/uploads'.
== APP == dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[9]
== APP ==       Connection id "0HMLQBQFRB300" completed keep alive response.
== APP == info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
== APP ==       Request finished HTTP/1.1 GET http://127.0.0.1:2000/uploads - - - 307 0 - 13.9515ms
== APP == dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[39]
== APP ==       Connection id "0HMLQBQFRB301" accepted.
== APP == dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[1]
== APP ==       Connection id "0HMLQBQFRB301" started.
== APP == dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[6]
== APP ==       Connection id "0HMLQBQFRB301" received FIN.
== APP == dbug: Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware[3]
== APP ==       Connection 0HMLQBQFRB301 established using the following protocol: Tls13
== APP == dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
== APP ==       Connection id "0HMLQBQFRB301" sending FIN because: "The client closed the connection."
== APP == dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[10]
== APP ==       Connection id "0HMLQBQFRB301" disconnecting.
== APP == dbug: Microsoft.AspNetCore.Server.Kestrel.BadRequests[20]
== APP ==       Connection id "0HMLQBQFRB301" request processing ended abnormally.
== APP ==       System.IO.IOException: The decryption operation failed, see inner exception.
== APP ==        ---> System.ComponentModel.Win32Exception (0x80090327): An unknown error occurred while processing the certificate.
== APP ==          --- End of inner exception stack trace ---
== APP ==          at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
== APP ==          at System.IO.Pipelines.StreamPipeReader.<ReadAsync>g__Core|36_0(StreamPipeReader reader, CancellationTokenSource tokenSource, CancellationToken cancellationToken)
== APP ==          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)        
== APP ==          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)   
== APP == dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[2]
== APP ==       Connection id "0HMLQBQFRB301" stopped.
== APP == dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[6]
== APP ==       Connection id "0HMLQBQFRB300" received FIN.
== APP == dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[10]
== APP ==       Connection id "0HMLQBQFRB300" disconnecting.
== APP == dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[2]
== APP ==       Connection id "0HMLQBQFRB300" stopped.
== APP == dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
== APP ==       Connection id "0HMLQBQFRB300" sending FIN because: "The Socket transport's send loop completed gracefully."

```

**Comment by iamsourabh-in** [comment]
Closing the issue, the issue was related to `HTTPS`, when the receiving service has the https Redirection Enabled

Removing the below line from the uploader service resolved the issues

```java

// Commented this line out
// app.UseHttpsRedirection();

```

**Comment by olitomlinson** [comment]
@iamsourabh-in 

Just as an FYI, It works for me with `UseHttpsRedirection` enabled.

This is my configuration for the App that receives the call from another App.
.NET 6.0 (Created with `dotnet new webapi`)

**.csproj**
```c#
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
  </ItemGroup>
</Project>

```
**program.cs**
```c#
var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Logging.ClearProviders();
builder.Logging.AddConsole();

builder.Services.AddControllers();
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();

```

<img width="490" alt="image" src="https://user-images.githubusercontent.com/4224880/198887024-41ef1d64-d402-470b-b3df-cc4e9695b6c1.png">

**Comment by iamsourabh-in** [comment]
Thank you so much @olitomlinson I tried it running on kubernetes with `mtls enabled` and https redirection on both services , it worked for me too.
