### ISSUE TITLE
Actors not working in Azure Container App (Dapr 1.9.5 / Net7)

### ISSUE THREAD

**Issue by jpiquot** [dapr/dapr#5696]
## In what area(s)?
 /area placement

## What version of Dapr?
1.9.5

## Expected Behavior
The application runs well in a local development environment using Man Sidekick and should also work well in Azure Container App.

## Actual Behavior

Actor call fails with error invoke actor method: **error finding address for actor type InboundMessageHandler** with id z8qcuQ1Lv0-AE8Oknc6u7Q

I also see thousands of  "**try to connect to placement service/established connection to placement service**" messages in DaprD logs when the logging level is debug. It seems to be abnormal for an application with no activity as it only reads one message from Azure Service Bus and calls the handler actor.

The startup loads all components successfully without any error messages.

**APPLICATION LOG:**
> 2023-01-03T22:23:13.160100933Z [22:23:13 INF] Handling event 'ContractEstablished' with Id=z8qcuQ1Lv0-AE8Oknc6u7Q.
> 2023-01-03T22:23:15.674016194Z [22:23:15 INF] Request starting HTTP/1.1 GET http://127.0.0.1:80/healthz - -
> 2023-01-03T22:23:15.674041794Z [22:23:15 INF] Executing endpoint 'Dapr Actors Health Check'
> 2023-01-03T22:23:15.674426790Z [22:23:15 INF] Executed endpoint 'Dapr Actors Health Check'
> 2023-01-03T22:23:15.674451490Z [22:23:15 INF] HTTP GET /healthz responded 200 in 0.1305 ms
> 2023-01-03T22:23:15.674478890Z [22:23:15 INF] Request finished HTTP/1.1 GET http://127.0.0.1:80/healthz - - - 200 - text/plain 0.2760ms
`2023-01-03T22:23:18.300839518Z [22:23:18 ERR] Error processing the message:
> 2023-01-03T22:23:18.300885918Z error invoke actor method: error finding address for actor type InboundMessageHandler with id z8qcuQ1Lv0-AE8Oknc6u7Q`
> 2023-01-03T22:23:18.300892618Z {"ContractId":"TEST-5-1","CustomerAccount":"TesTCust","PaymentAccount":"PayCust","PaymentMode":{"Id":"PAY","BankAccount":{"Iban":"IB123456789"},"DirectDebitMandate":{"Id":"123456789","CreditorBankAccount":"SGBANK"},"PaymentTerm":"13M"},"BusinessEventId":"ContractEstablished","BusinessEventLegalEntity":"SOL","EventId":"z8qcuQ1Lv0-AE8Oknc6u7Q","EventTimeIso8601":"2023-01-03T22:23:09.9046261+00:00","InitiatingUserAADObjectId":"test","MajorVersion":0,"MinorVersion":0}
> 2023-01-03T22:23:18.300897418Z Dapr.DaprApiException: error invoke actor method: error finding address for actor type InboundMessageHandler with id z8qcuQ1Lv0-AE8Oknc6u7Q
> 2023-01-03T22:23:18.300901418Z    at Dapr.Actors.DaprHttpInteractor.SendAsyncHandleUnsuccessfulResponse(Func`1 requestFunc, String relativeUri, CancellationToken cancellationToken)
> 2023-01-03T22:23:18.300905318Z    at Dapr.Actors.DaprHttpInteractor.SendAsync(Func1 requestFunc, String relativeUri, CancellationToken cancellationToken)
> 2023-01-03T22:23:18.300909518Z    at Dapr.Actors.DaprHttpInteractor.InvokeActorMethodWithRemotingAsync(ActorMessageSerializersManager serializersManager, IActorRequestMessage remotingRequestRequestMessage, CancellationToken cancellationToken)
> 2023-01-03T22:23:18.300913618Z    at Dapr.Actors.Communication.Client.ActorRemotingClient.InvokeAsync(IActorRequestMessage remotingRequestMessage, CancellationToken cancellationToken)
> 2023-01-03T22:23:18.300919817Z    at Dapr.Actors.Client.ActorProxy.InvokeMethodAsync(Int32 interfaceId, Int32 methodId, String methodName, IActorRequestMessageBody requestMsgBodyValue, CancellationToken cancellationToken)
> 2023-01-03T22:23:18.300925117Z    at D365FinOpsBridge.Infrastructure.Dynamics365CustomerEngagement.InboundBindings.InboundEventManager.HandleAsync(String eventId, String eventName, String message, CancellationToken cancellationToken) in /src/src/D365FinOpsBridge.Infrastructure.Dynamics365CustomerEngagement.InboundBindings/InboundEventManager.cs:line 45
> 2023-01-03T22:23:18.300929217Z    at D365FinOpsBridge.Controllers.InboundBindingController.ReceiveMessageAsync(JsonElement message) in /src/src/D365FinOpsBridge/Controllers/InboundBindingController.cs:line 76
> 2023-01-03T22:23:18.308184744Z [22:23:18 INF] Executing ObjectResult, writing value of type 'Microsoft.AspNetCore.Mvc.ProblemDetails'.
> 2023-01-03T22:23:18.313165194Z [22:23:18 INF] Executed action D365FinOpsBridge.Controllers.InboundBindingController.ReceiveMessageAsync (D365FinOpsBridge) in 5182.6134ms
> 2023-01-03T22:23:18.313574590Z [22:23:18 INF] Executed endpoint 'D365FinOpsBridge.Controllers.InboundBindingController.ReceiveMessageAsync (D365FinOpsBridge)'
> 2023-01-03T22:23:18.314870477Z [22:23:18 ERR] HTTP POST /contracts-binding responded 500 in 5211.4923 ms
> 2023-01-03T22:23:18.317290652Z [22:23:18 INF] Request finished HTTP/1.1 POST http://127.0.0.1:80/contracts-binding application/json 468 - 500 - application/json;+charset=utf-8 5212.3409ms
> 

**DAPRD LOG**
> 2023-01-03T22:07:55.881799612Z time="2023-01-03T22:07:55.881682514Z" level=debug msg="established connection to placement service at dns:///dapr-placement-server.k8se-system.svc.cluster.local:50005" app_id=d365-finops-bridge instance=slc-fno-dev--jhlv2yo-d648c5c44-dkpqv scope=dapr.runtime.actor.internal.placement type=log ver=1.9.5-msft-1
> 2023-01-03T22:07:55.882369707Z time="2023-01-03T22:07:55.88200181Z" level=debug msg="try to connect to placement service: dns:///dapr-placement-server.k8se-system.svc.cluster.local:50005" app_id=d365-finops-bridge instance=slc-fno-dev--jhlv2yo-d648c5c44-dkpqv scope=dapr.runtime.actor.internal.placement type=log ver=1.9.5-msft-1
> 2023-01-03T22:07:55.892074708Z time="2023-01-03T22:07:55.891987309Z" level=debug msg="established connection to placement service at dns:///dapr-placement-server.k8se-system.svc.cluster.local:50005" app_id=d365-finops-bridge instance=slc-fno-dev--jhlv2yo-d648c5c44-dkpqv scope=dapr.runtime.actor.internal.placement type=log ver=1.9.5-msft-1
> 2023-01-03T22:07:55.892505304Z time="2023-01-03T22:07:55.892271306Z" level=debug msg="try to connect to placement service: dns:///dapr-placement-server.k8se-system.svc.cluster.local:50005" app_id=d365-finops-bridge instance=slc-fno-dev--jhlv2yo-d648c5c44-dkpqv scope=dapr.runtime.actor.internal.placement type=log ver=1.9.5-msft-1
> 2023-01-03T22:07:55.905556671Z time="2023-01-03T22:07:55.905469472Z" level=debug msg="established connection to placement service at dns:///dapr-placement-server.k8se-system.svc.cluster.local:50005" app_id=d365-finops-bridge instance=slc-fno-dev--jhlv2yo-d648c5c44-dkpqv scope=dapr.runtime.actor.internal.placement type=log ver=1.9.5-msft-1
> 2023-01-03T22:07:55.905923368Z time="2023-01-03T22:07:55.905811269Z" level=debug msg="try to connect to placement service: dns:///dapr-placement-server.k8se-system.svc.cluster.local:50005" app_id=d365-finops-bridge instance=slc-fno-dev--jhlv2yo-d648c5c44-dkpqv scope=dapr.runtime.actor.internal.placement type=log ver=1.9.5-msft-1
> 2023-01-03T22:07:55.922585299Z time="2023-01-03T22:07:55.9224732Z" level=debug msg="established connection to placement service at dns:///dapr-placement-server.k8se-system.svc.cluster.local:50005" app_id=d365-finops-bridge instance=slc-fno-dev--jhlv2yo-d648c5c44-dkpqv scope=dapr.runtime.actor.internal.placement type=log ver=1.9.5-msft-1
> 2023-01-03T22:07:55.923164893Z time="2023-01-03T22:07:55.923095593Z" level=debug msg="try to connect to placement service: dns:///dapr-placement-server.k8se-system.svc.cluster.local:50005" app_id=d365-finops-bridge instance=slc-fno-dev--jhlv2yo-d648c5c44-dkpqv scope=dapr.runtime.actor.internal.placement type=log ver=1.9.5-msft-1
> 2023-01-03T22:07:55.933376489Z time="2023-01-03T22:07:55.93328639Z" level=debug msg="established connection to placement service at dns:///dapr-placement-server.k8se-system.svc.cluster.local:50005" app_id=d365-finops-bridge instance=slc-fno-dev--jhlv2yo-d648c5c44-dkpqv scope=dapr.runtime.actor.internal.placement type=log ver=1.9.5-msft-1
> 2023-01-03T22:07:55.974127676Z time="2023-01-03T22:07:55.973975777Z" level=debug msg="try to connect to placement service: dns:///dapr-placement-server.k8se-system.svc.cluster.local:50005" app_id=d365-finops-bridge instance=slc-fno-dev--jhlv2yo-d648c5c44-dkpqv scope=dapr.runtime.actor.internal.placement type=log ver=1.9.5-msft-1
> 2023-01-03T22:07:55.986277852Z time="2023-01-03T22:07:55.986180453Z" level=debug msg="established connection to placement service at dns:///dapr-placement-server.k8se-system.svc.cluster.local:50005" app_id=d365-finops-bridge instance=slc-fno-dev--jhlv2yo-d648c5c44-dkpqv scope=dapr.runtime.actor.internal.placement type=log ver=1.9.5-msft-1
> 2023-01-03T22:07:55.986794047Z time="2023-01-03T22:07:55.98649455Z" level=debug msg="try to connect to placement service: dns:///dapr-placement-server.k8se-system.svc.cluster.local:50005" app_id=d365-finops-bridge instance=slc-fno-dev--jhlv2yo-d648c5c44-dkpqv scope=dapr.runtime.actor.internal.placement type=log ver=1.9.5-msft-1
> 2023-01-03T22:07:55.995939354Z time="2023-01-03T22:07:55.995827255Z" level=debug msg="established connection to placement service at dns:///dapr-placement-server.k8se-system.svc.cluster.local:50005" app_id=d365-finops-bridge instance=slc-fno-dev--jhlv2yo-d648c5c44-dkpqv scope=dapr.runtime.actor.internal.placement type=log ver=1.9.5-msft-1
> 2023-01-03T22:07:55.996156052Z time="2023-01-03T22:07:55.996099553Z" level=debug msg="try to connect to placement service: dns:///dapr-placement-server.k8se-system.svc.cluster.local:50005" app_id=d365-finops-bridge instance=slc-fno-dev--jhlv2yo-d648c5c44-dkpqv scope=dapr.runtime.actor.internal.placement type=log ver=1.9.5-msft-1
> 2023-01-03T22:07:56.009973012Z time="2023-01-03T22:07:56.009882513Z" level=debug msg="established connection to placement service at dns:///dapr-placement-server.k8se-system.svc.cluster.local:50005" app_id=d365-finops-bridge instance=slc-fno-dev--jhlv2yo-d648c5c44-dkpqv scope=dapr.runtime.actor.internal.placement type=log ver=1.9.5-msft-1
> 2023-01-03T22:07:56.010502707Z time="2023-01-03T22:07:56.01020301Z" level=debug msg="try to connect to placement service: dns:///dapr-placement-server.k8se-system.svc.cluster.local:50005" app_id=d365-finops-bridge instance=slc-fno-dev--jhlv2yo-d648c5c44-dkpqv scope=dapr.runtime.actor.internal.placement type=log ver=1.9.5-msft-1
> 

## Steps to Reproduce the Problem

Language : **C#**
Framework: **.NET 7.0**
Cluster : **Azure Container App**

Call an actor method.

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.in-memory
  version: v1
  metadata:
    - name: actorStateStore
      value: "true"

```

**Comment by jpiquot** [comment]
I tried many configurations and I never have any errors in the startup logs but sill have the error finding actor address :


```

2023-01-05T21:08:59.49159  Connecting to the container 'daprd'...

2023-01-05T21:08:59.51082  Successfully Connected to container: 'daprd' [Revision: 'slc-fno-dev--olrj0lt', Replica: 'slc-fno-dev--olrj0lt-58d5cb9dc7-nfzvv']
2023-01-05T21:07:35.704328456Z time="2023-01-05T21:07:35.704279657Z" level=info msg="gRPC proxy enabled" app_id=d365-finops-bridge instance=slc-fno-dev--olrj0lt-58d5cb9dc7-nfzvv scope=dapr.runtime type=log ver=1.9.5-msft-1
2023-01-05T21:07:35.704418555Z time="2023-01-05T21:07:35.704351556Z" level=info msg="enabled API access list on gRPC server" app_id=d365-finops-bridge instance=slc-fno-dev--olrj0lt-58d5cb9dc7-nfzvv scope=dapr.runtime.grpc.api type=log ver=1.9.5-msft-1
2023-01-05T21:07:35.704440655Z time="2023-01-05T21:07:35.704409655Z" level=info msg="enabled gRPC metrics middleware" app_id=d365-finops-bridge instance=slc-fno-dev--olrj0lt-58d5cb9dc7-nfzvv scope=dapr.runtime.grpc.api type=log ver=1.9.5-msft-1
2023-01-05T21:07:35.704527454Z time="2023-01-05T21:07:35.704468155Z" level=info msg="enabled API access list on gRPC server" app_id=d365-finops-bridge instance=slc-fno-dev--olrj0lt-58d5cb9dc7-nfzvv scope=dapr.runtime.grpc.api type=log ver=1.9.5-msft-1
2023-01-05T21:07:35.704549254Z time="2023-01-05T21:07:35.704486354Z" level=info msg="enabled gRPC metrics middleware" app_id=d365-finops-bridge instance=slc-fno-dev--olrj0lt-58d5cb9dc7-nfzvv scope=dapr.runtime.grpc.api type=log ver=1.9.5-msft-1
2023-01-05T21:07:35.704563353Z time="2023-01-05T21:07:35.704528354Z" level=info msg="API gRPC server is running on port 50001" app_id=d365-finops-bridge instance=slc-fno-dev--olrj0lt-58d5cb9dc7-nfzvv scope=dapr.runtime type=log ver=1.9.5-msft-1
2023-01-05T21:07:35.704819450Z time="2023-01-05T21:07:35.704759651Z" level=info msg="enabled metrics http middleware" app_id=d365-finops-bridge instance=slc-fno-dev--olrj0lt-58d5cb9dc7-nfzvv scope=dapr.runtime.http type=log ver=1.9.5-msft-1
2023-01-05T21:07:35.704903349Z time="2023-01-05T21:07:35.70484375Z" level=info msg="enabled metrics http middleware" app_id=d365-finops-bridge instance=slc-fno-dev--olrj0lt-58d5cb9dc7-nfzvv scope=dapr.runtime.http type=log ver=1.9.5-msft-1
2023-01-05T21:07:35.704930549Z time="2023-01-05T21:07:35.70486705Z" level=info msg="http server is running on port 3500" app_id=d365-finops-bridge instance=slc-fno-dev--olrj0lt-58d5cb9dc7-nfzvv scope=dapr.runtime type=log ver=1.9.5-msft-1
2023-01-05T21:07:35.704937149Z time="2023-01-05T21:07:35.704880549Z" level=info msg="The request body size parameter is: 4" app_id=d365-finops-bridge instance=slc-fno-dev--olrj0lt-58d5cb9dc7-nfzvv scope=dapr.runtime type=log ver=1.9.5-msft-1
2023-01-05T21:07:35.704945349Z time="2023-01-05T21:07:35.704907549Z" level=info msg="enabled gRPC metrics middleware" app_id=d365-finops-bridge instance=slc-fno-dev--olrj0lt-58d5cb9dc7-nfzvv scope=dapr.runtime.grpc.internal type=log ver=1.9.5-msft-1
2023-01-05T21:07:35.704950649Z time="2023-01-05T21:07:35.704928049Z" level=info msg="sending workload csr request to sentry" app_id=d365-finops-bridge instance=slc-fno-dev--olrj0lt-58d5cb9dc7-nfzvv scope=dapr.runtime.grpc.internal type=log ver=1.9.5-msft-1
2023-01-05T21:07:35.749544600Z time="2023-01-05T21:07:35.749450201Z" level=info msg="certificate signed successfully" app_id=d365-finops-bridge instance=slc-fno-dev--olrj0lt-58d5cb9dc7-nfzvv scope=dapr.runtime.grpc.internal type=log ver=1.9.5-msft-1
2023-01-05T21:07:35.749700298Z time="2023-01-05T21:07:35.749627299Z" level=info msg="internal gRPC server is running on port 50002" app_id=d365-finops-bridge instance=slc-fno-dev--olrj0lt-58d5cb9dc7-nfzvv scope=dapr.runtime type=log ver=1.9.5-msft-1
2023-01-05T21:07:35.749707498Z time="2023-01-05T21:07:35.749644898Z" level=info msg="application protocol: http. waiting on port 80.  This will block until the app is listening on that port." app_id=d365-finops-bridge instance=slc-fno-dev--olrj0lt-58d5cb9dc7-nfzvv scope=dapr.runtime type=log ver=1.9.5-msft-1
2023-01-05T21:07:35.749922795Z time="2023-01-05T21:07:35.749828896Z" level=info msg="starting workload cert expiry watcher. current cert expires on: 2023-01-06 21:22:35 +0000 UTC" app_id=d365-finops-bridge instance=slc-fno-dev--olrj0lt-58d5cb9dc7-nfzvv scope=dapr.runtime.grpc.internal type=log ver=1.9.5-msft-1
2023-01-05T21:07:35.750051293Z time="2023-01-05T21:07:35.749972094Z" level=info msg="application discovered on port 80" app_id=d365-finops-bridge instance=slc-fno-dev--olrj0lt-58d5cb9dc7-nfzvv scope=dapr.runtime type=log ver=1.9.5-msft-1
2023-01-05T21:07:35.978669379Z time="2023-01-05T21:07:35.978559781Z" level=info msg="application configuration loaded" app_id=d365-finops-bridge instance=slc-fno-dev--olrj0lt-58d5cb9dc7-nfzvv scope=dapr.runtime type=log ver=1.9.5-msft-1
2023-01-05T21:07:35.978862177Z time="2023-01-05T21:07:35.978767278Z" level=info msg="actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s" app_id=d365-finops-bridge instance=slc-fno-dev--olrj0lt-58d5cb9dc7-nfzvv scope=dapr.runtime.actor type=log ver=1.9.5-msft-1
2023-01-05T21:07:36.088716625Z time="2023-01-05T21:07:36.088634126Z" level=info msg="dapr initialized. Status: Running. Init Elapsed 14377ms" app_id=d365-finops-bridge instance=slc-fno-dev--olrj0lt-58d5cb9dc7-nfzvv scope=dapr.runtime type=log ver=1.9.5-msft-1

```

**Comment by yaron2** [comment]
Hi, please open this issue here: https://github.com/microsoft/azure-container-apps.
