### ISSUE TITLE
A duplicate key '***' was found in the secret store '***'

### ISSUE THREAD

**Issue by dima1034** [dapr/dapr#6012]
Got the very same error on .NET k8s cluster as https://github.com/dapr/dapr/issues/4669

dapr is running -> on "dapr-system" namespace. 
app is running -> on "app" namespace. 

application have 2 services with AddDaprStore("storename"...) on the same node.

dapr-config and application in the very same namespace, as I assume, they should be.

```
Unhandled exception. System.InvalidOperationException: A duplicate key 'tls.crt' was found in the secret store 'secretstore'. Please remove any duplicates from your secret store.
   at Dapr.Extensions.Configuration.DaprSecretStore.DaprSecretStoreConfigurationProvider.LoadAsync()
   at Dapr.Extensions.Configuration.DaprSecretStore.DaprSecretStoreConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationManager.AddSource(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.ConfigurationManager.Microsoft.Extensions.Configuration.IConfigurationBuilder.Add(IConfigurationSource source)
   at Dapr.Extensions.Configuration.DaprSecretStoreConfigurationExtensions.AddDaprSecretStore(IConfigurationBuilder configurationBuilder, String store, DaprClient client, IReadOnlyDictionary`2 metadata)
   at Common.Configuration.ServicesAdd.ServicesAdd.AddDaprStore(IConfigurationBuilder configuration) in /src/src/BuildingBlocks/Common/Configuration/ServicesAdd/AddDaprStore.cs:line 11
   at Program.<Main>$(String[] args) in /src/src/Services/app2/Dapr.app2.API/Program.cs:line 34

```

@halspang  would really appreciate your help

**Comment by dima1034** [comment]
Descriptors is the way to go. I'm not sure yet, but I believe it is the right direction.

```
builder.ConfigureAppConfiguration(config =>
{
    var daprClient = new DaprClientBuilder().Build();
    var secretDescriptors = new List<DaprSecretDescriptor>
    {
        new DaprSecretDescriptor("***-secrets")
    };
    config.AddDaprSecretStore("***-secretstore", secretDescriptors, daprClient);
});
```
