### ISSUE TITLE
Create/delete reminder throws "possible etag mismatch" after enabling resiliency

### ISSUE THREAD

**Issue by MargaretKrutikova** [dapr/dapr#6018]
**Note:** If you have a general support question and are looking for a quicker response, please checkout our discord channel for answers from the community:
https://aka.ms/dapr-discord

## In what area(s)?

/area runtime

## Ask your question here

We are using `dapr` actors and our application is very heavy on actor reminders. After enabling `resiliency` feature we started experiencing a lot of exceptions with `error deleting actor reminder: possible etag mismatch` when creating and deleting reminders. We also see that these operations write into a single key `actors||ActorName||metadata` and since we are triggering many reminders from many actors that could cause `ETag` mismatch if used on state requests:
```
Dapr.DaprApiException: error deleting actor reminder: possible etag mismatch. 
error from state store: ERR Error running script @user_script:14:  failed to set key actors||ActorName||metadata
 at Dapr.Actors.DaprHttpInteractor.SendAsyncHandleUnsuccessfulResponse(Func`1 requestFunc, String relativeUri, CancellationToken cancellationToken)\n 
```

Is there any way we could solve this problem and still keep the resiliency feature enabled? Thanks!

**Comment by ItalyPaleAle** [comment]
Thanks for the report, what state store component are you using?

**Comment by MargaretKrutikova** [comment]
We are using self-hosted `redis` state store in kubernetes on azure.

**Comment by MargaretKrutikova** [comment]
We were using `dapr` 1.9.3 and today I upgraded it to 1.10.2 and we see almost none of these errors, there was one during the last 6 hours after the upgrade. I will observe the system for some time tomorrow and report back here. So currently we have:
- `dapr` 1.10.2
- `redis-stack-server` 6.2.6.

**Comment by berndverst** [comment]
Redis is not actually transactional -- see https://github.com/dapr/components-contrib/issues/2071

In the very next upcoming hotfix we are now adding a warning to Redis state store that informs users not to use Redis in production as actor state store.

The lack of transaction guarantees for redis (actor state changes may be inconsistently applied by the database) could very much be the root cause of your problems.

**Comment by et2012** [comment]
We encountered a similar problem when creating reminders using ```state.sqlserver``` as the actor state store.
We tried to create 200 reminders in 3 seconds, 65 failed with the following error:

```
Dapr.DaprApiException: error creating actor reminder: possible etag mismatch. error from state store: mssql: Error number 2601 in the THROW statement is outside the valid range. Specify an error number in the valid range of 50000 to 2147483647.
at Dapr.Actors.DaprHttpInteractor.SendAsyncHandleUnsuccessfulResponse(Func`1 requestFunc, String relativeUri, CancellationToken cancellationToken)
at Dapr.Actors.DaprHttpInteractor.SendAsync(Func`1 requestFunc, String relativeUri, CancellationToken cancellationToken)
at Dapr.Actors.Runtime.DefaultActorTimerManager.RegisterReminderAsync(ActorReminder reminder)
at Dapr.Actors.Runtime.Actor.RegisterReminderAsync(ActorReminderOptions options)
at Dapr.Actors.Runtime.Actor.RegisterReminderAsync(String reminderName, Byte[] state, TimeSpan dueTime, TimeSpan period)
```

Error number 2601 seems to indicate that there are duplicate keys.

Version info:
- dapr runtime 1.10.2
- Dapr .NET SDK 1.10.0 (Dapr.Actors.AspNetCore)
- SQL Server 2012 Standard

**Comment by ItalyPaleAle** [comment]
@et2012 Two questions:

- Is your app scaled horizontally?
- Do you use reminder partitioning?

I think this may actually be a bug in Dapr and looking at the code, I suspect it may be due to `storeReminder`:

https://github.com/dapr/dapr/blob/6ad53d0af348df1ad61ddb4efa5a74230a9955f8/pkg/actors/actors.go#L1941

The operations in that method could be not concurrency-safe for possibly two reasons (I haven't verified these, I'm just studying the code)

### First

If there are multiple `daprd` processes, they may conflict with each other.  

Within the same `daprd` process, there's a lock ([example](https://github.com/dapr/dapr/blob/6ad53d0af348df1ad61ddb4efa5a74230a9955f8/pkg/actors/actors.go#L1238)) that prevents multiple calls to `storeReminder` at the same time. However, if there are multiple instances of `daprd`, they can conflict with each other.

For example, they can both be invoking `getRemindersForActorType`, `saveRemindersInPartition` or `saveActorTypeMetadata` at the same time. These methods do not use transactions (and we really should use a transaction here), so they could race each other and cause etag conflicts.

In some cases these conflicts are "good", meaning that they're actually working to protect the integrity of your data. What concerns me however is if two runtimes, A and B, save 2 different partitions at the same time, and then race to call `saveActorTypeMetadata`, which means that they record the wrong etag for at least one partition.

### Second

The second possible issue is in-process and it's actually due to resiliency. [`policyRunner`](https://github.com/dapr/dapr/blob/6ad53d0af348df1ad61ddb4efa5a74230a9955f8/pkg/actors/actors.go#L1958) runs operations in separate goroutines.

if the operation times out, `policyRunner` will restart the operation from scratch. However, the previous operation doesn't know it's timed out (its context should have been canceled, but the method used there doesn't check for context cancellation between subsequent network calls). So in case of timeouts, we have race conditions in which the "expired" operation could still be writing into the state store.

**Comment by ItalyPaleAle** [comment]
@et2012  would you be able to share the code you're using to reproduce this issue, if possible?

**Comment by et2012** [comment]
@ItalyPaleAle For your questions:
- No, my application does not scale horizontally, but has 2 replicas for testing purposes.
- No, I don't use reminder partitioning

If ```storeReminder``` is not concurrency-safe, is it recommended to use distributed locks before registering reminders?

My code is a simple actor with reminder:

```
// called from [Topic("pubsub", "CreateOrder")
public async Task CreateOrder(OrderPayload order)
{
    // invoke external service to create the order
    await dapr.InvokeMethodAsync("external-order-service", "createOrder", order);

    // publish an event to check order for completion
    await dapr.PublishEventAsync("pubsub", "CheckOrderCompletion", order);
}

// called from [Topic("pubsub", "CheckOrderCompletion")
public async Task CheckOrderCompletion(OrderPayload order)
{
    // invoke external service to get order status
    var orderStatus = await dapr.InvokeMethodAsync("external-order-service", "getOrderStatus", order.Id);
    if (orderStatus != OrderStatus.Completed) {
        // register a reminder to check for completion later
       await RegisterReminderAsync("CheckOrderDelayed", Serializer.SerializeToBytes(order), TimeSpan.FromSeconds(5), TimeSpan.FromMilliseconds(-1));
    }
    else {
        // order is completed
        await dapr.PublishEventAsync("pubsub", "OrderCompleted", order);
    }
}

public async Task ReceiveReminderAsync(string reminderName, byte[] state, TimeSpan dueTime, TimeSpan period)
{
    // if (reminderName != "CheckOrderDelayed") { return };
    var order = Serializer.Deserialize<OrderPayload>(state);

    // publish an event to check order completion
    await dapr.PublishEventAsync("pubsub", "CheckOrderCompletion", order);
}
```

```external-order-service``` is an external service that does not notify my application when an order is completed and I have to continuously check for order completion.

**Comment by ItalyPaleAle** [comment]
Thanks for sharing the code. It will help investigating further, although I have an idea on what could be causing this and opened #6050 with some initial mitigations.

>If storeReminder is not concurrency-safe, is it recommended to use distributed locks before registering reminders?

Let us see how we can fix this in Dapr first. If this is a concurrency error, we need to fix this in Dapr first.

> No, my application does not scale horizontally, but has 2 replicas for testing purposes.

Having 2 replicas in this case has the same effect as scaling horizontally and could trigger the other kinds of race conditions (across processes).

**Comment by ItalyPaleAle** [comment]
@et2012 would you be able to test a different build of Dapr (which includes #6050)? It also has more logs that can help debugging further if you can please post them.

The Docker image is `aledapr.azurecr.io/daprd:reminders-dev-linux-amd64`.

You can use this image by setting the annotation `dapr.io/sidecar-image` to `aledapr.azurecr.io/daprd:reminders-dev-linux-amd64`

**Comment by et2012** [comment]
@ItalyPaleAle

[daprd-logs.zip](https://github.com/dapr/dapr/files/10927548/daprd-logs.zip)

I'm using ```statestore.sqlserver``` as actor state store, error message:

```
Dapr.DaprApiException: error creating actor reminder: error storing reminder: error saving reminders partition: possible etag mismatch. error from state store: mssql: Error number 2601 in the THROW statement is outside the valid range. Specify an error number in the valid range of 50000 to 2147483647.
```

One of the order's id is ```10719676104105985```, in pod ```d2zqb```

- ```ChargeActor``` class: my actor class
- ```ChannelSelect``` method: select one from multiple external order services (aka, ```Channel```)
- ```ChannelCharge``` method: create order via the selected order service
- ```ChannelSync``` method: check order completion and create the reminder if the order is not completed
- ```DelayedSync``` method: name of the actor reminder

**Comment by et2012** [comment]
@ItalyPaleAle 

[daprd-debug-logs.zip](https://github.com/dapr/dapr/files/10928450/daprd-debug-logs.zip)

I created a ```TestActor.TestMethod``` to register ```TestReminder``` directly, with:
- actor state store: ```Azure SQL Server```
- ```dapr.io/log-level: 'debug'```
- ```replicas: 2```

I called ```TestActor.TestMethod```  ```100``` times and ```20``` failed with errors:
```
Dapr.DaprApiException: error creating actor reminder: error storing reminder: error saving reminders partition: possible etag mismatch. error from state store: mssql: Error number 2601 in the THROW statement is outside the valid range. Specify an error number in the valid range of 50000 to 2147483647.
```

Here are the IDs of some of the failed orders:
```
10720239858081793
10720239844843522
10720239807733760
10720239822544896
```

**Comment by CRidge** [comment]
Just a quick FYI: We're seeing the same (intermittently) with Cosmos DB as state store, running in Azure Container Apps. Partitioned storage of the reminder data on. It doesn't seem to be a real issue, as the reminders doesn't re-trigger (as they would if we didn't delete them).

**Comment by ItalyPaleAle** [comment]
Thanks all for confirming.

We have identified the root cause and some potential remediations. We are working on it right now, and depending on how the fix progresses, we will either make a new hotfix for 1.10, or will put this in 1.11 (my hope is that we can complete it quickly for a hotfix). I'll keep this issue posted

**Comment by ItalyPaleAle** [comment]
Thanks all for confirming.

We have identified the root cause and some potential remediations. We are working on it right now, and depending on how the fix progresses, we will either make a new hotfix for 1.10, or will put this in 1.11 (my hope is that we can complete it quickly for a hotfix). I'll keep this issue posted

**One important thing** is that we believe that in _most_ cases when you get an etag error, you can safely re-try the creation of the reminder.

**Comment by ItalyPaleAle** [comment]
Update from this morning's maintainer sync: we are looking at getting this into a hotfix for Dapr 1.10.4. No ETA yet, but likely not this week.

**Comment by ItalyPaleAle** [comment]
Hi all, thanks for your patience.

We just released Dapr 1.10.5-rc.1, could you please try it out and see if that works for you? It should include fixes for race conditions

**Comment by et2012** [comment]
@ItalyPaleAle 

https://github.com/dapr/dapr/issues/6018#issuecomment-1461365046

After updating to ```1.10.5-rc.1```, I tried to create ```10``` reminders at once with the above code and ```1``` failed:

```
Dapr.DaprApiException: error creating actor reminder: error storing reminder: error saving reminders partition and metadata: possible etag mismatch.
```

I checked the logs and found ```2``` requests are racing conditions:
(Actor id format: ```timestamp-threadId```, they are created in the same millisecond)
```
1680674352318-4: error creating actor reminder.
1680674352318-7: reminder created (and triggered) successfully.
```

after all the ```9``` reminders triggered, actor states are not removed from ```state``` table (```mssql``` as actor state store) :

| Key | Data |
|  ----  | ----  |
| actors\|\|TestActor | [{"registeredTime":"2023-04-05T05:59:17Z","data":"cmVtMTY4MDY3NDM1MjMxOC03","actorID":"1680674352318-7","actorType":"TestActor","name":"TestReminder","dueTime":"0h0m5s0ms"}] |
| actors\|\|TestActor\|\|metadata | {"id":"00000000-0000-0000-0000-000000000000","actorRemindersMetadata":{"partitionCount":0}} |
| TestActor\|\|1680674352318-7\|\|TestReminder | {"lastFiredTime":"2023-04-05T05:59:17Z","repetitionLeft":-1} |

**Comment by ItalyPaleAle** [comment]
@et2012 thanks for confirming

1.10.5-rc.1 wasn't meant to eliminate all race conditions _entirely_, as for now the most critical thing was making sure there'd be no data loss in case of a race condition. Some will be inevitable and if you're seeing this error, it's "almost a good thing" at this point. We recommend simply retrying for now, and the reminders should be stored.

However, I can do some more looking into how this can be improved even further. Perhaps I could add a lock to make sure that within the same sidecar, only 1 reminder saving operation can happen at the same time. Wouldn't remove race conditions when multiple processes are doing this, but could help with race conditions in-process.

As for deleting the old "track" of the reminder, I don't believe that has changed recently. Did 1.10.4 delete the "track" record? (I am also looking into how to remove those records entirely in 1.11)

**Comment by et2012** [comment]
@ItalyPaleAle Thanks for response.

Retries can solve some of the problems, but may also cause new race of conditions. e.g.:
I tried to create ```20``` reminders in parallel and retry up to ```3``` times when error creating actor reminder,
- ```15``` of them succeeded without retries
-  ```4``` of them succeeded after 1 retries
-  ```1``` of them failed after 2 retries

As for old tracks of the reminders:
- Under normal circumstances, track of reminder should (and will) be deleted from both sidecar and actor state store after triggering.
- But due to race of conditions, some old tracks are not removed from the sidecar and actor state store, which means they will be triggered again when the application was scaled up or redeployed.
  - The tracks remained in the sidecar are random, could be a normal reminder (which succeeded without retries, did not run into race of conditions)
  - This problem exists in ```1.10.4``` and ```1.10.5-rc.1```

**Comment by ItalyPaleAle** [comment]
I see.

Fixing the leftover tracks may be a more complex thing that will need to wait till 1.11 :(
