### ISSUE TITLE
Panic when subscriber listen message in reids

### ISSUE THREAD

**Issue by onqlave-cesc** [dapr/dapr#6036]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x10541ef1c]

goroutine 29 [running]:
github.com/dapr/dapr/pkg/expr.(*Expr).Eval(0x1?, 0x1088743a0?)
        /Users/runner/work/dapr/dapr/pkg/expr/expr.go:65 +0x1c
github.com/dapr/dapr/pkg/runtime.matchRoutingRule({0x140012d13b0, 0x2, 0x1070c8ac8?}, 0x5?)
        /Users/runner/work/dapr/dapr/pkg/runtime/runtime.go:726 +0x74
github.com/dapr/dapr/pkg/runtime.findMatchingRoute({0x140012d13b0, 0x2, 0x2}, {0x108254da0?, 0x140015f5320})
        /Users/runner/work/dapr/dapr/pkg/runtime/runtime.go:709 +0xa8
github.com/dapr/dapr/pkg/runtime.(*DaprRuntime).beginPubSub.func1({0x108ac4200, 0x14000f84240}, 0x14000f84200)
        /Users/runner/work/dapr/dapr/pkg/runtime/runtime.go:654 +0x714
github.com/dapr/components-contrib/pubsub/redis.(*redisStreams).processMessage(0x140001d8000, {{0x108ac4190, 0x140007f8e00}, {0x140015f00a8, 0xf}, {{0x14000f7c4e0, 0x19b, 0x1a0}, {0x140015bbfb4, 0xa}, ...}, ...})
        /Users/runner/go/pkg/mod/github.com/dapr/components-contrib@v1.8.6/pubsub/redis/redis.go:255 +0x190
github.com/dapr/components-contrib/pubsub/redis.(*redisStreams).worker(0x140001d8000)
        /Users/runner/go/pkg/mod/github.com/dapr/components-contrib@v1.8.6/pubsub/redis/redis.go:238 +0x80
created by github.com/dapr/components-contrib/pubsub/redis.(*redisStreams).Init
        /Users/runner/go/pkg/mod/github.com/dapr/components-contrib@v1.8.6/pubsub/redis/redis.go:153 +0x298
❌  The daprd process exited with error code: exit status 2

**Comment by yaron2** [comment]
Can you paste your subscription YAML or programmatic subscription?

**Comment by dmutterSF** [comment]
ran into the same problem. It occurs because the CEL program of type Expr is nil. Happens when the field "match" of the SubscriptionRule is an empty string which is the default value in the proto generated code.
Could be prevented by also doing a nil check on the program field [here](https://github.com/dapr/dapr/blob/1ae581691b0006cdb20da5f7b8f832e62372ec8e/pkg/runtime/runtime.go#L957)

Reproduced with dapr 1.10.5

**Comment by yaron2** [comment]
@dmutterSF thanks for providing this info. would you be interested in submitting a PR to fix this?
