### ISSUE TITLE
Dapr does not configure pubsub locally

### ISSUE THREAD

**Issue by YordiVanDyckPXL** [dapr/dapr#6146]
I am working for my internship with DAPR and everything has been going perfectly up until yesterdat when it stopped working.
Me and someone from the team looked at it but couldn't find anything. He ran it on his own computer and everything worked fine
It also works perfectly on azure container apps only not on my machine.
 
**Reinstalling dapr does not work!**

I have 2 services running: sensordataproducer and fishtankstatus.

### Running the app:
![image](https://user-images.githubusercontent.com/73341063/228258077-ba781710-cc39-4eac-a3e9-6c3d77514ee2.png)
![image](https://user-images.githubusercontent.com/73341063/228265369-46eb4288-a423-40db-8b0f-73ced76638b7.png)

Component pubsub file: 
![image](https://user-images.githubusercontent.com/73341063/228258605-5bfd249a-2efb-4a21-ace6-6fd0f3740a77.png)

**Logs:**
sensordataproducer service:
![image](https://user-images.githubusercontent.com/73341063/228258281-c81611a3-8edf-4392-8f63-4d2ced6fa96b.png)
![image](https://user-images.githubusercontent.com/73341063/228258431-ca471d7b-d01d-4f06-97d6-28c915215839.png)
![image](https://user-images.githubusercontent.com/73341063/228258468-044f2cb8-a67e-4db6-a1d6-6d479ae812dc.png)

**Code:**
![image](https://user-images.githubusercontent.com/73341063/228259379-f97cbcb6-a501-410f-85b5-6f77834edcbb.png)
![image](https://user-images.githubusercontent.com/73341063/228261354-96639298-59d3-43d1-bf16-766f1d4bdfd9.png)

**Request:**
![image](https://user-images.githubusercontent.com/73341063/228259123-52b570dc-bc12-42b2-8756-a893db915c02.png)

**Error:** 
```
Dapr.DaprException: Publish operation failed: the Dapr endpoint indicated a failure. See InnerException for details.
 ---> Grpc.Core.RpcException: Status(StatusCode="FailedPrecondition", Detail="no pubsub is configured")
   at Dapr.Client.DaprClientGrpc.MakePublishRequest(String pubsubName, String topicName, ByteString content, Dictionary`2 metadata, String dataContentType, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Dapr.Client.DaprClientGrpc.MakePublishRequest(String pubsubName, String topicName, ByteString content, Dictionary`2 metadata, String dataContentType, CancellationToken cancellationToken)
   at sensordataproducer.Services.DataProducerService.Start(Int32 frequency, DaprClient client) in C:\Users\YordiD\Documents\GitHub\EventDrivenMicroservicesYordi2023\current\src\sensordataproducer\sensordataproducer\Services\DataProducerService.cs:line 60
   at sensordataproducer.Controllers.StartStopController.Start(Int32 frequency) in C:\Users\YordiD\Documents\GitHub\EventDrivenMicroservicesYordi2023\current\src\sensordataproducer\sensordataproducer\Controllers\StartStopController.cs:line 27
   at lambda_method5(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
**When I Post to the sensordata endpoint in in my fishtankstatus web api it invokes the middleware:**
![image](https://user-images.githubusercontent.com/73341063/228260955-823cea2d-a9c3-4008-b19f-7ca76e47d638.png)
![image](https://user-images.githubusercontent.com/73341063/228260571-e6b58f78-8d54-41cc-9621-8a31ab8851b4.png)

**Publishing via the DAPR CLI gives the following error:**
```
dapr publish -i fishtankstatus --pubsub sensorpubsub --topic sensordata --data '{}'
http://localhost:62159/v1.0/publish/sensorpubsub/sensordata
Error publishing topic sensordata: unexpected status code 400 on publishing to sensordata in sensorpubsub

```
**The fishtankstatus container subscribes to the topics as we can see via a curl command:**
```
 curl http://localhost:7002/dapr/subscribe -v
VERBOSE: GET with 0-byte payload
VERBOSE: received -1-byte response of content type


StatusCode        : 200
StatusDescription : OK
Content           : {91, 123, 34, 116...}
RawContent        : HTTP/1.1 200 OK
                    Transfer-Encoding: chunked
                    Date: Tue, 28 Mar 2023 14:01:44 GMT
                    Server: Kestrel

                    [{"topic":"sensordata","pubsubName":"sensorpubsub","route":"sensordata"}]
Headers           : {[Transfer-Encoding, chunked], [Date, Tue, 28 Mar 2023 14:01:44 GMT], [Server, Kestrel]}
RawContentLength  : 73
```
Is there anything else I can try to fix this?

**Comment by shubham1172** [comment]
Hi @YordiVanDyckPXL, can you run both the apps with `--log-level` as `debug` and then share them as text files or attachments here?

**Comment by YordiVanDyckPXL** [comment]
[fishtankstatus.txt](https://github.com/dapr/dapr/files/11097335/fishtankstatus.txt)
[sensorDataProdcuer.txt](https://github.com/dapr/dapr/files/11097336/sensorDataProdcuer.txt)

**Comment by shubham1172** [comment]
@YordiVanDyckPXL thanks for sharing, few points
- The `sensordataproducer` app is loading the component correctly, but I don't see the component being loaded by `fishtankstatus`. Are you specifying the components directory properly?
- When you tried to publish a message above, you seem to be using `fishtankstatus`. If you want `sensordataproducer` to publish the message, you should run
```bash
dapr publish -i sensordataproducer --pubsub sensorpubsub --topic sensordata --data '{}'
```
- Publish event won't work from fishtankstatus since the component is not actually loaded.

**Comment by YordiVanDyckPXL** [comment]
They are referencing to the same component folder and checked it many times.

Same happens with the producer: 
```
dapr publish -i sensordataproducer --pubsub sensorpubsub --topic sensordata
http://localhost:6005/v1.0/publish/sensorpubsub/sensordata
Error publishing topic sensordata: unexpected status code 400 on publishing to sensordata in sensorpubsub

```

**Comment by shubham1172** [comment]
@YordiVanDyckPXL interesting. When this happens with producer, do you still see this in logs?
`level=debug msg="found component. name: sensorpubsub, type: pubsub.redis/v1" app_id=sensordataproducer`

**Comment by YordiVanDyckPXL** [comment]
I just ran OpenTelememtry with the application and the trace seems to fail on getting the config:
```

== APP == Activity.TraceId:            3af46abcd1e8f64fe807a06dfcbb209e
== APP == Activity.SpanId:             41662436d5cccbc8
== APP == Activity.TraceFlags:         Recorded
== APP == Activity.ActivitySourceName: OpenTelemetry.Instrumentation.AspNetCore
== APP == Activity.DisplayName:        /dapr/config
== APP == Activity.Kind:               Server
== APP == Activity.StartTime:          2023-03-29T08:36:35.9929842Z
== APP == Activity.Duration:           00:00:00.0624818
== APP == Activity.Tags:
== APP ==     net.host.name: 127.0.0.1
== APP ==     net.host.port: 5241
== APP ==     http.method: GET
== APP ==     http.scheme: http
== APP ==     http.target: /dapr/config
== APP ==     http.url: http://127.0.0.1:5241/dapr/config
== APP ==     http.flavor: 1.1
== APP ==     http.user_agent: Go-http-client/1.1
== APP ==     http.status_code: 404
== APP == Resource associated with Activity:
== APP ==     service.name: unknown_service:sensordataproducer

```

**Comment by YordiVanDyckPXL** [comment]
> @YordiVanDyckPXL interesting. When this happens with producer, do you still see this in logs? `level=debug msg="found component. name: sensorpubsub, type: pubsub.redis/v1" app_id=sensordataproducer`

Yes it is there

**Comment by YordiVanDyckPXL** [comment]
> @YordiVanDyckPXL are you on Dapr discord? You can ping me there (shubham1172), we can do a pair-debugging session https://aka.ms/dapr-discord

I Send a message on discord.

**Comment by YordiVanDyckPXL** [comment]
We found the issue.

It is windows 11 interfering with something.
We tried running dapr in wsl and then it worked perfectly.

This log was missing in the dapr
`DEBU[0000] loading component. name: pubsub, type: pubsub.redis/v1  app_id=test instance=YORDID01 scope=dapr.runtime type=log ver=1.10.4`
