### ISSUE TITLE
Dapr.DaprApiException: error saving actor transaction state: transaction failed due to operation 0 which failed with status code 409

### ISSUE THREAD

**Issue by vladozar** [dapr/dapr#6316]
## In what area(s)?

> /area runtime

## What version of Dapr?

> 1.10.0
> 1.10.5

## Expected Behavior

No Exceptions are thrown

## Actual Behavior

Dapr throws 409 exceptions

This might be related to this issue: https://github.com/dapr/dapr/issues/6018

When we were on version 1.8.4 and 1.9.2, on our deployments, were not getting any Dapr Exeptions. 
We had to update our Azure resources and more to new resources. Once moving to new Auzre resources (same as old with following differences: new naming convention, new subscriptions, newer version of Kubernetes Cluster), the default latest version was 1.10.5 of Dpar runtime. After our service was successfully deployed, we started to get the following error on RegisterReminderAsync call:

`
023-04-20T21:48:24.783Z  time="2023-04-20T21:48:24.783314923Z" level=error msg="Transaction failed due to operation 1 which failed with status code 409" app_id=vehicleactor component="cosmos-statestore (state.azure.cosmosdb/v1)" instance=vehicleactor-5665874777-mhg6c scope=dapr.contrib type=log ver=1.10.5
2023-04-20T21:48:24.783Z  time="2023-04-20T21:48:24.783344922Z" level=error msg="Error getting reminders for actor type VirtualVehicleActor: could not read actor type metadata: failed to perform transaction to migrate records for actor type VirtualVehicleActor: transaction failed due to operation 1 which failed with status code 409" app_id=vehicleactor instance=vehicleactor-5665874777-mhg6c scope=dapr.runtime.actor type=log ver=1.10.5
2023-04-20T21:48:28.082Z  time="2023-04-20T21:48:28.082393154Z" level=error msg="Transaction failed due to operation 1 which failed with status code 409" app_id=vehicleactor component="cosmos-statestore (state.azure.cosmosdb/v1)" instance=vehicleactor-5665874777-mhg6c scope=dapr.contrib type=log ver=1.10.5
2023-04-20T21:48:28.082Z  time="2023-04-20T21:48:28.082467254Z" level=error msg="Error getting reminders for actor type VirtualVehicleActor: could not read actor type metadata: failed to perform transaction to migrate records for actor type VirtualVehicleActor: transaction failed due to operation 1 which failed with status code 409" app_id=vehicleactor instance=vehicleactor-5665874777-mhg6c scope=dapr.runtime.actor type=log ver=1.10.5
2023-04-20T22:45:26.064Z  time="2023-04-20T22:45:26.064747066Z" level=error msg="Transaction failed due to operation 1 which failed with status code 409" app_id=vehicleactor component="cosmos-statestore (state.azure.cosmosdb/v1)" instance=vehicleactor-5665874777-mhg6c scope=dapr.contrib type=log ver=1.10.5
2023-04-20T23:24:09.505Z  time="2023-04-20T23:24:09.505087498Z" level=error msg="Transaction failed due to operation 1 which failed with status code 409" app_id=vehicleactor component="cosmos-statestore (state.azure.cosmosdb/v1)" instance=vehicleactor-5665874777-mhg6c scope=dapr.contrib type=log ver=1.10.5
`
Once receiving this exception, the actor stops and does not continue. 

I have tried to downgrade to an older version that we had on our previous deployment. Now I was getting a Dapr exception something related to not being able to find the address for the actor with the given ID (Similar to this report https://stackoverflow.com/questions/74498799/dapr-cant-find-address-for-net-actor#:~:text=Dapr%20can%27t%20find%20the%20address%20for%20the%20actor,version%3A%201.9.1%20Runtime%20version%3A%201.9.3%20Dapr%20Actor%20output)

Now we are on Dapr runtime version 1.10.0

We are getting the following Exceptions, but the actor successfully completed it's job:
In the Dapr Client Logs on service startup. Once this log is received, no other Dapr Client Logs are logged:

`
2023-05-04T17:33:00.951Z  time="2023-05-04T17:33:00.951295928Z" level=error msg="error getting reminders for actor type VirtualVehicleActor: could not read actor type metadata: POST https://my-cosmosdb.documents.azure.com:443/dbs/AppStateStore/colls/VirtualVehicle-WestUS2/docs\n--------------------------------------------------------------------------------\nRESPONSE 409: 409 Conflict\nERROR CODE: Conflict\n--------------------------------------------------------------------------------\n{\n  \"code\": \"Conflict\",\n  \"message\": \"Entity with the specified id already exists in the system., \\r\\nRequestStartTime: 2023-05-04T17:33:00.9436406Z, RequestEndTime: 2023-05-04T17:33:00.9436406Z,  Number of regions attempted:1\\r\\n{\\\"systemHistory\\\":[{\\\"dateUtc\\\":\\\"2023-05-04T17:32:09.8932732Z\\\",\\\"cpu\\\":0.844,\\\"memory\\\":669348812.000,\\\"threadInfo\\\":{\\\"isThreadStarving\\\":\\\"False\\\",\\\"threadWaitIntervalInMs\\\":0.0758,\\\"availableThreads\\\":32764,\\\"minThreads\\\":64,\\\"maxThreads\\\":32767},\\\"numberOfOpenTcpConnection\\\":2018},{\\\"dateUtc\\\":\\\"2023-05-04T17:32:19.9033432Z\\\",\\\"cpu\\\":0.683,\\\"memory\\\":669366516.000,\\\"threadInfo\\\":{\\\"isThreadStarving\\\":\\\"False\\\",\\\"threadWaitIntervalInMs\\\":0.0641,\\\"availableThreads\\\":32764,\\\"minThreads\\\":64,\\\"maxThreads\\\":32767},\\\"numberOfOpenTcpConnection\\\":2020},{\\\"dateUtc\\\":\\\"2023-05-04T17:32:29.9134090Z\\\",\\\"cpu\\\":0.695,\\\"memory\\\":669373368.000,\\\"threadInfo\\\":{\\\"isThreadStarving\\\":\\\"False\\\",\\\"threadWaitIntervalInMs\\\":0.0575,\\\"availableThreads\\\":32764,\\\"minThreads\\\":64,\\\"maxThreads\\\":32767},\\\"numberOfOpenTcpConnection\\\":2018},{\\\"dateUtc\\\":\\\"2023-05-04T17:32:39.9234996Z\\\",\\\"cpu\\\":0.407,\\\"memory\\\":669084188.000,\\\"threadInfo\\\":{\\\"isThreadStarving\\\":\\\"False\\\",\\\"threadWaitIntervalInMs\\\":0.0389,\\\"availableThreads\\\":32764,\\\"minThreads\\\":64,\\\"maxThreads\\\":32767},\\\"numberOfOpenTcpConnection\\\":2019},{\\\"dateUtc\\\":\\\"2023-05-04T17:32:49.9335672Z\\\",\\\"cpu\\\":0.263,\\\"memory\\\":669076020.000,\\\"threadInfo\\\":{\\\"isThreadStarving\\\":\\\"False\\\",\\\"threadWaitIntervalInMs\\\":0.0544,\\\"availableThreads\\\":32764,\\\"minThreads\\\":64,\\\"maxThreads\\\":32767},\\\"numberOfOpenTcpConnection\\\":2020},{\\\"dateUtc\\\":\\\"2023-05-04T17:32:59.9436363Z\\\",\\\"cpu\\\":0.612,\\\"memory\\\":669097444.000,\\\"threadInfo\\\":{\\\"isThreadStarving\\\":\\\"False\\\",\\\"threadWaitIntervalInMs\\\":0.0518,\\\"availableThreads\\\":32764,\\\"minThreads\\\":64,\\\"maxThreads\\\":32767},\\\"numberOfOpenTcpConnection\\\":2015}]}\\r\\nRequestStart: 2023-05-04T17:33:00.9436406Z; ResponseTime: 2023-05-04T17:33:00.9436406Z; StoreResult: StorePhysicalAddress: rntbd://cdb-ms-prod-westus2-be19.documents.azure.com:14096/apps/caaf92eb-9ea9-4fd1-9dbc-b8d409a7b16d/services/8ba77a28-3b29-469a-a091-6b60cca84dc5/partitions/5322ee75-fe4e-47cc-894b-08a45361b686/replicas/133262262085223442p/, LSN: 1886, GlobalCommittedLsn: 1885, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 409, SubStatusCode: 0, RequestCharge: 1.24, ItemLSN: -1, SessionToken: 0#1886#6=-1#12=-1, UsingLocalLSN: False, TransportException: null, BELatencyMs: 1.013, ActivityId: e7b67503-0e12-4351-a969-1328fc251134, RetryAfterInMs: , TransportRequestTimeline: {\\\"requestTimeline\\\":[{\\\"event\\\": \\\"Created\\\", \\\"startTimeUtc\\\": \\\"2023-05-04T17:33:00.9436406Z\\\", \\\"durationInMs\\\": 0.0092},{\\\"event\\\": \\\"ChannelAcquisitionStarted\\\", \\\"startTimeUtc\\\": \\\"2023-05-04T17:33:00.9436498Z\\\", \\\"durationInMs\\\": 0.0023},{\\\"event\\\": \\\"Pipelined\\\", \\\"startTimeUtc\\\": \\\"2023-05-04T17:33:00.9436521Z\\\", \\\"durationInMs\\\": 0.1616},{\\\"event\\\": \\\"Transit Time\\\", \\\"startTimeUtc\\\": \\\"2023-05-04T17:33:00.9438137Z\\\", \\\"durationInMs\\\": 1.3069},{\\\"event\\\": \\\"Received\\\", \\\"startTimeUtc\\\": \\\"2023-05-04T17:33:00.9451206Z\\\", \\\"durationInMs\\\": 0.0809},{\\\"event\\\": \\\"Completed\\\", \\\"startTimeUtc\\\":
`
While our actor is running, we may get few exceptions in the vehicle actor while the actor completes its job. Now I was not yet being able to pinpoint when exactly this exception happens (definitely not during register/unregister reminders), possibly on reminder updates:

`
2023-05-04T17:36:10.556Z  [40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
2023-05-04T17:36:10.556Z        Executed endpoint 'Dapr Actors Reminder'
2023-05-04T17:36:10.563Z  [41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
2023-05-04T17:36:10.563Z        An unhandled exception has occurred while executing the request.
2023-05-04T17:36:10.563Z        Dapr.DaprApiException: error saving actor transaction state: transaction failed due to operation 0 which failed with status code 409
2023-05-04T17:36:10.563Z           at Dapr.Actors.DaprHttpInteractor.SendAsyncHandleUnsuccessfulResponse(Func`1 requestFunc, String relativeUri, CancellationToken cancellationToken)
2023-05-04T17:36:10.563Z           at Dapr.Actors.DaprHttpInteractor.SendAsync(Func`1 requestFunc, String relativeUri, CancellationToken cancellationToken)
2023-05-04T17:36:10.563Z           at Dapr.Actors.Runtime.DaprStateProvider.DoStateChangesTransactionallyAsync(String actorType, String actorId, IReadOnlyCollection`1 stateChanges, CancellationToken cancellationToken)
2023-05-04T17:36:10.563Z           at Dapr.Actors.Runtime.DaprStateProvider.SaveStateAsync(String actorType, String actorId, IReadOnlyCollection`1 stateChanges, CancellationToken cancellationToken)
2023-05-04T17:36:10.563Z           at Dapr.Actors.Runtime.ActorStateManager.SaveStateAsync(CancellationToken cancellationToken)
2023-05-04T17:36:10.563Z           at Dapr.Actors.Runtime.Actor.SaveStateAsync()
2023-05-04T17:36:10.563Z           at Dapr.Actors.Runtime.Actor.OnPostActorMethodAsyncInternal(ActorMethodContext actorMethodContext)
2023-05-04T17:36:10.563Z           at Dapr.Actors.Runtime.ActorManager.DispatchInternalAsync[T](ActorId actorId, ActorMethodContext actorMethodContext, Func`3 actorFunc, CancellationToken cancellationToken)
2023-05-04T17:36:10.563Z           at Dapr.Actors.Runtime.ActorManager.DispatchInternalAsync[T](ActorId actorId, ActorMethodContext actorMethodContext, Func`3 actorFunc, CancellationToken cancellationToken)
2023-05-04T17:36:10.563Z           at Dapr.Actors.Runtime.ActorManager.DispatchInternalAsync[T](ActorId actorId, ActorMethodContext actorMethodContext, Func`3 actorFunc, CancellationToken cancellationToken)
2023-05-04T17:36:10.563Z           at Dapr.Actors.Runtime.ActorManager.FireReminderAsync(ActorId actorId, String reminderName, Stream requestBodyStream, CancellationToken cancellationToken)
2023-05-04T17:36:10.563Z           at Microsoft.AspNetCore.Builder.ActorsEndpointRouteBuilderExtensions.<>c__DisplayClass4_0.<b__0>d.MoveNext()
2023-05-04T17:36:10.563Z        --- End of stack trace from previous location ---
2023-05-04T17:36:10.563Z           at Microsoft.AspNetCore.Routing.EndpointMiddleware.g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
2023-05-04T17:36:10.563Z           at vwac.VirtualVehicles.Logging.Middleware.TracingMiddleware.InvokeAsync(HttpContext httpContext, ILogger logger) in /ActorTaskManagement/Logging/src/Logging/Middleware/TracingMiddleware.cs:line 78
2023-05-04T17:36:10.563Z           at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2023-05-04T17:36:10.589Z  [40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Diagnostics[2]
2023-05-04T17:36:10.589Z        Request finished HTTP/1.1 PUT http://127.0.0.1:80/actors/VirtualVehicleActor/c889568a-bdb1-4965-b15e-055a0dc960bf/method/remind/BeginSession application/json 182 - 500 - text/plain;+charset=utf-8 1588.4518ms
`

For all Dapr Version deployment, I made sure that .NetSDK Nuget version And Dapr Runtime on AKS were compatible according to https://docs.dapr.io/operations/support/support-release-policy/

## Steps to Reproduce the Problem

We were running on clean CosmosDB state store. 

Dapr Runtime Version 1.10.5:
Exception happens on Dapr/Actor startup and when calling Register Reminder

Dapr Runtime Version 1.10.0:
Exception happens on Dapr/Actor startup and most likey when reminder is being updated. 

## Release Note

RELEASE NOTE:

**Comment by vladozar** [comment]
Update:
With Latest Dapr Runtime 1.10.6: 
When our service start, I get the following logs in the Dapr Client:
```
2023-05-08T17:46:44.115Z  time="2023-05-08T17:46:44.115362353Z" level=error msg="Transaction failed due to operation 1 which failed with status code 409" app_id=vehicleactor component="cosmos-statestore (state.azure.cosmosdb/v1)" instance=vehicleactor-7cb889788c-m9x54 scope=dapr.contrib type=log ver=1.10.6
2023-05-08T17:46:44.115Z  time="2023-05-08T17:46:44.115556953Z" level=error msg="Error getting reminders for actor type VirtualVehicleActor: could not read actor type metadata: failed to perform transaction to migrate records for actor type VirtualVehicleActor: transaction failed due to operation 1 which failed with status code 409" app_id=vehicleactor instance=vehicleactor-7cb889788c-m9x54 scope=dapr.runtime.actor type=log ver=1.10.6
2023-05-08T17:46:44.115Z  time="2023-05-08T17:46:44.115656353Z" level=info msg="placement tables updated, version: 1" app_id=vehicleactor instance=vehicleactor-7cb889788c-m9x54 scope=dapr.runtime.actor.internal.placement type=log ver=1.10.6
2023-05-08T17:46:46.332Z  time="2023-05-08T17:46:46.332713949Z" level=warning msg="migrating actor metadata record for actor type VirtualVehicleActor" app_id=vehicleactor instance=vehicleactor-7cb889788c-m9x54 scope=dapr.runtime.actor type=log ver=1.10.6
2023-05-08T17:46:46.336Z  time="2023-05-08T17:46:46.336406646Z" level=info msg="migrating 0 reminders for actor type VirtualVehicleActor" app_id=vehicleactor instance=vehicleactor-7cb889788c-m9x54 scope=dapr.runtime.actor type=log ver=1.10.6
2023-05-08T17:46:46.339Z  time="2023-05-08T17:46:46.339505244Z" level=error msg="Transaction failed due to operation 1 which failed with status code 409" app_id=vehicleactor component="cosmos-statestore (state.azure.cosmosdb/v1)" instance=vehicleactor-7cb889788c-m9x54 scope=dapr.contrib type=log ver=1.10.6
2023-05-08T17:46:46.339Z  time="2023-05-08T17:46:46.339538744Z" level=error msg="Error getting reminders for actor type VirtualVehicleActor: could not read actor type metadata: failed to perform transaction to migrate records for actor type VirtualVehicleActor: transaction failed due to operation 1 which failed with status code 409" app_id=vehicleactor instance=vehicleactor-7cb889788c-m9x54 scope=dapr.runtime.actor type=log ver=1.10.6
```


When we try to register a reminder we catch the following exception when calling `RegisterReminderAsync`:
```
{"@t":"2023-05-08T18:00:27.8441284Z","@mt":"Failed to Register Reminder details: error creating actor reminder: error storing reminder: error saving reminders partition and metadata: transaction failed due to operation 1 which failed with status code 409)","@l":"Error","@x":"Dapr.DaprApiException: error creating actor reminder: error storing reminder: error saving reminders partition and metadata: transaction failed due to operation 1 which failed with status code 409\n   at Dapr.Actors.DaprHttpInteractor.SendAsyncHandleUnsuccessfulResponse(Func`1 requestFunc, String relativeUri, CancellationToken cancellationToken)\n   at Dapr.Actors.DaprHttpInteractor.SendAsync(Func`1 requestFunc, String relativeUri, CancellationToken cancellationToken)\n   at Dapr.Actors.Runtime.DefaultActorTimerManager.RegisterReminderAsync(ActorReminder reminder)\n   at Dapr.Actors.Runtime.Actor.RegisterReminderAsync(ActorReminderOptions options)\n   at Dapr.Actors.Runtime.Actor.RegisterReminderAsync(String reminderName, Byte[] state, TimeSpan dueTime, TimeSpan period)\n   at vwac.VirtualVehicles.VehicleActor.VirtualVehicleActor.RegisterReminderWithTraceAsync(String reminderName, TimeSpan dueTime, TimeSpan period, TimeSpan ttl) in /src/.........}
```
and in Dapr Client Logs:
```
time="2023-05-08T18:00:27.837876323Z" level=error msg="Transaction failed due to operation 1 which failed with status code 409" app_id=vehicleactor component="cosmos-statestore (state.azure.cosmosdb/v1)" instance=vehicleactor-7cb889788c-m9x54 scope=dapr.contrib type=log ver=1.10.6
```

**Comment by vladozar** [comment]
@artursouza , is there any timeframe when potentially v1.11 will be released? This issue blocker with our production environment.

**Comment by artursouza** [comment]
This is considered a hotfix in 1.10 as well. We are working on reproducing this in our E2E tests first before we have a fix. I cannot have an ETA right now. My recommendation is to downgrade to 1.9 or use the 1.9 daprd image for the apps that host actors.

**Comment by vladozar** [comment]
@artursouza 
Downgrading back to Dapr Runtime version 1.9.5 and .Net Nuget Package to 1.9.0, I get the following error before even getting in to the actor from the web API.

```
[41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
2023-05-08T21:25:51.717Z        An unhandled exception has occurred while executing the request.
2023-05-08T21:25:51.717Z        Dapr.DaprApiException: error invoke actor method: rpc error: code = Internal desc = error invoke actor method: error finding address for actor type VirtualVehicleActor with id 23a6950c-9b70-4a0c-bfb6-53a71ad943fe
2023-05-08T21:25:51.717Z           at Dapr.Actors.DaprHttpInteractor.SendAsyncHandleUnsuccessfulResponse(Func`1 requestFunc, String relativeUri, CancellationToken cancellationToken)
2023-05-08T21:25:51.717Z           at Dapr.Actors.DaprHttpInteractor.SendAsync(Func`1 requestFunc, String relativeUri, CancellationToken cancellationToken)
2023-05-08T21:25:51.717Z           at Dapr.Actors.DaprHttpInteractor.InvokeActorMethodWithRemotingAsync(ActorMessageSerializersManager serializersManager, IActorRequestMessage remotingRequestRequestMessage, CancellationToken cancellationToken)
2023-05-08T21:25:51.717Z           at Dapr.Actors.Communication.Client.ActorRemotingClient.InvokeAsync(IActorRequestMessage remotingRequestMessage, CancellationToken cancellationToken)
2023-05-08T21:25:51.717Z           at Dapr.Actors.Client.ActorProxy.InvokeMethodAsync(Int32 interfaceId, Int32 methodId, String methodName, IActorRequestMessageBody requestMsgBodyValue, CancellationToken cancellationToken)
2023-05-08T21:25:51.717Z           at Dapr.Actors.Client.ActorProxy.ContinueWithResult[TRetval](Int32 interfaceId, Int32 methodId, Task`1 task)
2023-05-08T21:25:51.717Z           at VirtualVehicles.ApplicationWeb.Services.VehicleInterfaceService.GetSessionInfoAsync(Guid vehicleId, Guid environmentId) in /src/ApplicationWeb/Services/VehicleInterfaceService.cs:line 191
2023-05-08T21:25:51.717Z           at VirtualVehicles.ApplicationWeb.Controllers.VehiclesController.GetVehicleSessionInfo(Guid id) in /src/ApplicationWeb/Controllers/VehiclesController.cs:line 218
2023-05-08T21:25:51.717Z           at lambda_method599(Closure , Object , Object[] )
2023-05-08T21:25:51.717Z           at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
2023-05-08T21:25:51.717Z           at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Logged|12_1(ControllerActionInvoker invoker)
2023-05-08T21:25:51.717Z           at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2023-05-08T21:25:51.717Z           at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
2023-05-08T21:25:51.717Z           at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2023-05-08T21:25:51.717Z           at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
2023-05-08T21:25:51.717Z        --- End of stack trace from previous location ---
2023-05-08T21:25:51.717Z           at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2023-05-08T21:25:51.717Z           at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
2023-05-08T21:25:51.717Z           at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2023-05-08T21:25:51.717Z           at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
2023-05-08T21:25:51.717Z        --- End of stack trace from previous location ---
2023-05-08T21:25:51.717Z           at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Logged|17_1(ResourceInvoker invoker)
2023-05-08T21:25:51.717Z           at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Logged|17_1(ResourceInvoker invoker)
2023-05-08T21:25:51.717Z           at Microsoft.AspNetCore.Routing.EndpointMiddleware.g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
2023-05-08T21:25:51.717Z           at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
2023-05-08T21:25:51.717Z           at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
2023-05-08T21:25:51.717Z           at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
2023-05-08T21:25:51.717Z           at VirtualVehicles.Logging.Middleware.TracingMiddleware.InvokeAsync(HttpContext httpContext, ILogger logger) in /ActorTaskManagement/Logging/src/Logging/Middleware/TracingMiddleware.cs:line 78
2023-05-08T21:25:51.717Z           at VirtualVehicles.ApplicationWeb.Middleware.WebSocketProxyMiddleware.InvokeAsync(HttpContext context) in /src/ApplicationWeb/Middleware/WebSocketProxyMiddleware.cs:line 25
2023-05-08T21:25:51.717Z           at VirtualVehicles.ApplicationWeb.Middleware.SubscriptionContextMiddleware.InvokeAsync(HttpContext context, ILogger logger) in /src/ApplicationWeb/Middleware/SubscriptionContextMiddleware.cs:line 26
2023-05-08T21:25:51.717Z           at VirtualVehicles.ApplicationWeb.Middleware.HealthMiddleware.InvokeAsync(HttpContext context, IUnitOfWork unitOfWork) in /src/ApplicationWeb/Middleware/HealthMiddleware.cs:line 29
2023-05-08T21:25:51.717Z           at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
2023-05-08T21:25:51.717Z           at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
2023-05-08T21:25:51.717Z           at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by yaron2** [comment]
When downgrading please update the control plane first, then rollout restart your actor host deployments followed by the actor client deployments

**Comment by vladozar** [comment]
@yaron2 Could you please confirm if the downgrade/updagrad following step that we take are correct?
Our service is hosted in the Azure Kubernetes Service (AKS). We take the following steps:
1. On AKS:
    a. `dapr uninstall -k`
    b. `dapr init --runtime-version $daprVersion -k`
2. On the Service Side:
    a. Update .Net Nuget package to be compatible with the runtime version based on this page: https://docs.dapr.io/operations/support/support-release-policy/
    b. Build and re-deploy our service and actors to the AKS

**Comment by artursouza** [comment]
The error below shows up when you are changing the number of partitions for a given actor type:
`failed to perform transaction to migrate records for actor type MyVirtualActor`

Can you perform this migration using the 1.9 release and then upgrade to 1.10? Only the sidecar version needs to change, not the control plane (entire Dapr installation).

**Comment by vladozar** [comment]
@artursouza 
So I have done the following:

- re-installed dapr on the aks to version 1.9.0
- Updated Dapr Sidecar injector YAML, and changed all version references to version 1.10
- Re-deployed my application
- I'm getting the following error when my application/actors are trying to start:

```
time="2023-05-15T17:07:00.803173796Z" level=fatal msg="failed to start internal gRPC server: error from authenticator CreateSignedWorkloadCert: error from sentry SignCertificate: rpc error: code = Unknown desc = error validating requester identity: csr validation failed: invalid token: [invalid bearer token, token audiences [\"dapr.io/sentry\"] is invalid for the target audiences [\"https://d-cor-vv-uw2-aks-dns-9xec1br7.hcp.westus2.azmk8s.io\" \"\\\"d-cor-vv-uw2-aks-dns-9xec1br7.hcp.westus2.azmk8s.io\\\"\"]]" app_id=resourcemgmtactor instance=time="2023-05-15T17:07:00.803173796Z" level=fatal msg="failed to start internal gRPC server: error from authenticator CreateSignedWorkloadCert: error from sentry SignCertificate: rpc error: code = Unknown desc = error validating requester identity: csr validation failed: invalid token: [invalid bearer token, token audiences [\"dapr.io/sentry\"] is invalid for the target audiences [\"https://my-aks-dns-9xec1br7.hcp.westus2.azmk8s.io\" \"\\\"my-aks-dns-9xec1br7.hcp.westus2.azmk8s.io\\\"\"]]" app_id=resourceactor instance=resourceactor-dcbb4b756-42tb4 scope=dapr.runtime type=log ver=1.10.0-dcbb4b756-42tb4 scope=dapr.runtime type=log ver=1.10.0
```
```

**Comment by artursouza** [comment]
Can you upgrade with the `dapr` CLI tool? If you prefer, I can hop in a call to troubleshoot this together. Ping me on Discord.

**Comment by RyanLettieri** [comment]
> Update: With Latest Dapr Runtime 1.10.6: When our service start, I get the following logs in the Dapr Client:
> 
> ```
> 2023-05-08T17:46:44.115Z  time="2023-05-08T17:46:44.115362353Z" level=error msg="Transaction failed due to operation 1 which failed with status code 409" app_id=myactor component="cosmos-statestore (state.azure.cosmosdb/v1)" instance=myactor-7cb889788c-m9x54 scope=dapr.contrib type=log ver=1.10.6
> 2023-05-08T17:46:44.115Z  time="2023-05-08T17:46:44.115556953Z" level=error msg="Error getting reminders for actor type MyVirtualActor: could not read actor type metadata: failed to perform transaction to migrate records for actor type MyVirtualActor: transaction failed due to operation 1 which failed with status code 409" app_id=myactorinstance=myactor-7cb889788c-m9x54 scope=dapr.runtime.actor type=log ver=1.10.6
> 2023-05-08T17:46:44.115Z  time="2023-05-08T17:46:44.115656353Z" level=info msg="placement tables updated, version: 1" app_id=myactor instance=myactor-7cb889788c-m9x54 scope=dapr.runtime.actor.internal.placement type=log ver=1.10.6
> 2023-05-08T17:46:46.332Z  time="2023-05-08T17:46:46.332713949Z" level=warning msg="migrating actor metadata record for actor type MyVirtualActor" app_id=myactor instance=myactor-7cb889788c-m9x54 scope=dapr.runtime.actor type=log ver=1.10.6
> 2023-05-08T17:46:46.336Z  time="2023-05-08T17:46:46.336406646Z" level=info msg="migrating 0 reminders for actor type MyVirtualActor" app_id=myactorinstance=myactor-7cb889788c-m9x54 scope=dapr.runtime.actor type=log ver=1.10.6
> 2023-05-08T17:46:46.339Z  time="2023-05-08T17:46:46.339505244Z" level=error msg="Transaction failed due to operation 1 which failed with status code 409" app_id=myactor component="cosmos-statestore (state.azure.cosmosdb/v1)" instance=myactor-7cb889788c-m9x54 scope=dapr.contrib type=log ver=1.10.6
> 2023-05-08T17:46:46.339Z  time="2023-05-08T17:46:46.339538744Z" level=error msg="Error getting reminders for actor type MyVirtualActor: could not read actor type metadata: failed to perform transaction to migrate records for actor type MyVirtualActor: transaction failed due to operation 1 which failed with status code 409" app_id=myactorinstance=myactor-7cb889788c-m9x54 scope=dapr.runtime.actor type=log ver=1.10.6
> ```
> 
> When we try to register a reminder we catch the following exception when calling `RegisterReminderAsync`:
> 
> ```
> {"@t":"2023-05-08T18:00:27.8441284Z","@mt":"Failed to Register Reminder details: error creating actor reminder: error storing reminder: error saving reminders partition and metadata: transaction failed due to operation 1 which failed with status code 409)","@l":"Error","@x":"Dapr.DaprApiException: error creating actor reminder: error storing reminder: error saving reminders partition and metadata: transaction failed due to operation 1 which failed with status code 409\n   at Dapr.Actors.DaprHttpInteractor.SendAsyncHandleUnsuccessfulResponse(Func`1 requestFunc, String relativeUri, CancellationToken cancellationToken)\n   at Dapr.Actors.DaprHttpInteractor.SendAsync(Func`1 requestFunc, String relativeUri, CancellationToken cancellationToken)\n   at Dapr.Actors.Runtime.DefaultActorTimerManager.RegisterReminderAsync(ActorReminder reminder)\n   at Dapr.Actors.Runtime.Actor.RegisterReminderAsync(ActorReminderOptions options)\n   at Dapr.Actors.Runtime.Actor.RegisterReminderAsync(String reminderName, Byte[] state, TimeSpan dueTime, TimeSpan period)\n   at MyVirtualActor.RegisterReminderWithTraceAsync(String reminderName, TimeSpan dueTime, TimeSpan period, TimeSpan ttl) in /src/.........}
> ```
> 
> and in Dapr Client Logs:
> 
> ```
> time="2023-05-08T18:00:27.837876323Z" level=error msg="Transaction failed due to operation 1 which failed with status code 409" app_id=myactor component="cosmos-statestore (state.azure.cosmosdb/v1)" instance=myactor-7cb889788c-m9x54 scope=dapr.contrib type=log ver=1.10.6
> ```

@vladozar on dapr 1.10.6+ are you still running into the error message stating: "Transaction failed due to operation 1 which failed with status code 409" or anything similar?
