### ISSUE TITLE
PubSub component not configured

### ISSUE THREAD

**Issue by LucienMoor** [dapr/dapr#6333]
I am trying to setup PubSub using Redis with Dapr. I am trying to make the quickstarts working (.NET):

https://github.com/dapr/quickstarts/tree/master/pub_sub/csharp/sdk

and I also tried to make the tutorial example work:

https://github.com/dapr/quickstarts/tree/master/tutorials/pub-sub

but in both case I met the same error.

When I try to run my publisher I always end up with the following error:

```
time="2023-05-11T16:29:23.5283698+02:00" level=debug msg="rpc error: code = FailedPrecondition desc = no pubsub is configured" app_id=checkout-sdk instance=FI-101 scope=dapr.runtime.grpc.api type=log ver=1.10.6
== APP == Unhandled exception. Dapr.DaprException: Publish operation failed: the Dapr endpoint indicated a failure. See InnerException for details.
== APP ==  ---> Grpc.Core.RpcException: Status(StatusCode="FailedPrecondition", Detail="no pubsub is configured")
== APP ==    at Dapr.Client.DaprClientGrpc.MakePublishRequest(String pubsubName, String topicName, ByteString content, Dictionary`2 metadata, String dataContentType, CancellationToken cancellationToken)
== APP ==    --- End of inner exception stack trace ---
== APP ==    at Dapr.Client.DaprClientGrpc.MakePublishRequest(String pubsubName, String topicName, ByteString content, Dictionary`2 metadata, String dataContentType, CancellationToken cancellationToken)
== APP ==    at Program.<Main>$(String[] args) in C:\Dev\Github\quickstarts\pub_sub\csharp\sdk\checkout\Program.cs:line 11
== APP ==    at Program.<Main>(String[] args)
```

But the thing is, it is configured and properly found:

`time="2023-05-11T16:29:22.2932885+02:00" level=debug msg="found component. name: orderpubsub, type: pubsub.rabbitmq/v1" app_id=checkout-sdk instance=FI-101 scope=dapr.runtime type=log ver=1.10.6`

I have tried with the default configuration of pubsub coming when running dapr init :
pubsub.yml

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: orderpubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
```

and also tried with rabbitMQ sample from the doc: https://docs.dapr.io/developing-applications/building-blocks/pubsub/howto-publish-subscribe/:

## What version of Dapr?

I am using Dapr(1.10 on Windows)

## Expected Behavior

I expected the Sample from tutorial & quickstart to work :(

PubSub should be found and working when specified as a component on windows. specified in %UserProfile%\.dapr\components\pubsub.yaml or by using the --resources-path command parameter

## Actual Behavior

PubSub not found and application unable to publish anything. Either from dapr.Client or directly from the sidecar (via HTTP)

## Steps to Reproduce the Problem

Nothing special, just follow the steps from the documentation and the same behavior should happen. I am using Windows 10.

**Comment by DeepanshuA** [comment]
@LucienMoor After log trace of `Found component`, do you also see something like `Loading component` and then `Loaded component: orderpubsub`, something like following:
```
time="2023-05-12T09:30:56.3942678+05:30" level=info msg="Component loaded: statestore-actors (state.redis/v1)" app_id=orderapp instance=LAPTOP-J62MA7E9 scope=dapr.runtime type=log ver=unknown
```
or do you see any error?
As, it seems that from `Failed precondition` that pubsub was not loaded successfully.
Please confirm.

**Comment by acoLMO** [comment]
Here is the full output for the checkout-sdk application (publisher):

I start the application using `dapr run --app-id checkout-sdk --resources-path ../../../components/ --app-port 6001 --dapr-http-port 3601 --dapr-grpc-port 60001 --log-level debug -- dotnet run --project .`
```
Starting Dapr with id checkout-sdk. HTTP Port: 3601. gRPC Port: 60001
time="2023-05-15T08:44:37.2706829+02:00" level=info msg="starting Dapr Runtime -- version 1.10.6 -- commit a2511d924f7a866907d4bf2db73da5ea6cd63c36" app_id=checkout-sdk instance=FI-101 scope=dapr.runtime type=log ver=1.10.6
time="2023-05-15T08:44:37.2736361+02:00" level=info msg="log level set to: debug" app_id=checkout-sdk instance=FI-101 scope=dapr.runtime type=log ver=1.10.6
time="2023-05-15T08:44:37.2736361+02:00" level=info msg="metrics server started on :65410/" app_id=checkout-sdk instance=FI-101 scope=dapr.metrics type=log ver=1.10.6
time="2023-05-15T08:44:37.2763458+02:00" level=debug msg="Found 0 resiliency configurations." app_id=checkout-sdk instance=FI-101 scope=dapr.runtime type=log ver=1.10.6
time="2023-05-15T08:44:37.2763458+02:00" level=info msg="Resiliency configuration loaded." app_id=checkout-sdk instance=FI-101 scope=dapr.runtime type=log ver=1.10.6
time="2023-05-15T08:44:37.2768485+02:00" level=info msg="standalone mode configured" app_id=checkout-sdk instance=FI-101 scope=dapr.runtime type=log ver=1.10.6
time="2023-05-15T08:44:37.2769063+02:00" level=info msg="app id: checkout-sdk" app_id=checkout-sdk instance=FI-101 scope=dapr.runtime type=log ver=1.10.6
time="2023-05-15T08:44:37.2769063+02:00" level=info msg="mTLS is disabled. Skipping certificate request and tls validation" app_id=checkout-sdk instance=FI-101 scope=dapr.runtime type=log ver=1.10.6
time="2023-05-15T08:44:37.277454+02:00" level=info msg="Dapr trace sampler initialized: DaprTraceSampler(P=1.000000)" app_id=checkout-sdk instance=FI-101 scope=dapr.runtime type=log ver=1.10.6
time="2023-05-15T08:44:37.2917495+02:00" level=info msg="local service entry announced: checkout-sdk -> 172.23.0.36:65411" app_id=checkout-sdk component="mdns (nameResolution/v1)" instance=FI-101 scope=dapr.contrib type=log ver=1.10.6
time="2023-05-15T08:44:37.2917495+02:00" level=info msg="Initialized name resolution to mdns" app_id=checkout-sdk instance=FI-101 scope=dapr.runtime type=log ver=1.10.6
time="2023-05-15T08:44:37.2922552+02:00" level=debug msg="the current OS does not support pluggable components feature, skipping initialization" app_id=checkout-sdk instance=FI-101 scope=dapr.runtime type=log ver=1.10.6
time="2023-05-15T08:44:37.2924487+02:00" level=info msg="loading components" app_id=checkout-sdk instance=FI-101 scope=dapr.runtime type=log ver=1.10.6
time="2023-05-15T08:44:37.2940755+02:00" level=debug msg="found component. name: orderpubsub, type: pubsub.rabbitmq/v1" app_id=checkout-sdk instance=FI-101 scope=dapr.runtime type=log ver=1.10.6
time="2023-05-15T08:44:37.2945799+02:00" level=info msg="waiting for all outstanding components to be processed" app_id=checkout-sdk instance=FI-101 scope=dapr.runtime type=log ver=1.10.6
time="2023-05-15T08:44:37.2946441+02:00" level=info msg="all outstanding components processed" app_id=checkout-sdk instance=FI-101 scope=dapr.runtime type=log ver=1.10.6
time="2023-05-15T08:44:37.2946441+02:00" level=info msg="gRPC proxy enabled" app_id=checkout-sdk instance=FI-101 scope=dapr.runtime type=log ver=1.10.6
time="2023-05-15T08:44:37.2952204+02:00" level=info msg="gRPC server listening on TCP address: :60001" app_id=checkout-sdk instance=FI-101 scope=dapr.runtime.grpc.api type=log ver=1.10.6
time="2023-05-15T08:44:37.2952204+02:00" level=info msg="Enabled gRPC tracing middleware" app_id=checkout-sdk instance=FI-101 scope=dapr.runtime.grpc.api type=log ver=1.10.6
time="2023-05-15T08:44:37.2957736+02:00" level=info msg="Enabled gRPC metrics middleware" app_id=checkout-sdk instance=FI-101 scope=dapr.runtime.grpc.api type=log ver=1.10.6
time="2023-05-15T08:44:37.2957736+02:00" level=info msg="configuring workflow engine gRPC endpoint" app_id=checkout-sdk instance=FI-101 scope=dapr.runtime.wfengine type=log ver=1.10.6
time="2023-05-15T08:44:37.2963857+02:00" level=info msg="API gRPC server is running on port 60001" app_id=checkout-sdk instance=FI-101 scope=dapr.runtime type=log ver=1.10.6
time="2023-05-15T08:44:37.299329+02:00" level=info msg="enabled metrics http middleware" app_id=checkout-sdk instance=FI-101 scope=dapr.runtime.http type=log ver=1.10.6
time="2023-05-15T08:44:37.299329+02:00" level=info msg="enabled tracing http middleware" app_id=checkout-sdk instance=FI-101 scope=dapr.runtime.http type=log ver=1.10.6
time="2023-05-15T08:44:37.2998722+02:00" level=info msg="HTTP server listening on TCP address: :3601" app_id=checkout-sdk instance=FI-101 scope=dapr.runtime.http type=log ver=1.10.6
time="2023-05-15T08:44:37.2998722+02:00" level=info msg="http server is running on port 3601" app_id=checkout-sdk instance=FI-101 scope=dapr.runtime type=log ver=1.10.6
time="2023-05-15T08:44:37.3004011+02:00" level=info msg="The request body size parameter is: 4" app_id=checkout-sdk instance=FI-101 scope=dapr.runtime type=log ver=1.10.6
time="2023-05-15T08:44:37.3019288+02:00" level=info msg="gRPC server listening on TCP address: :65411" app_id=checkout-sdk instance=FI-101 scope=dapr.runtime.grpc.internal type=log ver=1.10.6
time="2023-05-15T08:44:37.3068632+02:00" level=info msg="Enabled gRPC tracing middleware" app_id=checkout-sdk instance=FI-101 scope=dapr.runtime.grpc.internal type=log ver=1.10.6
time="2023-05-15T08:44:37.3073899+02:00" level=info msg="Enabled gRPC metrics middleware" app_id=checkout-sdk instance=FI-101 scope=dapr.runtime.grpc.internal type=log ver=1.10.6
time="2023-05-15T08:44:37.3115924+02:00" level=info msg="internal gRPC server is running on port 65411" app_id=checkout-sdk instance=FI-101 scope=dapr.runtime type=log ver=1.10.6
time="2023-05-15T08:44:37.3121096+02:00" level=info msg="application protocol: http. waiting on port 6001.  This will block until the app is listening on that port." app_id=checkout-sdk instance=FI-101 scope=dapr.runtime type=log ver=1.10.6
Updating metadata for appPID: 107460
Updating metadata for app command: dotnet run --project .
You're up and running! Both Dapr and your app logs will appear here.

time="2023-05-15T08:44:38.8516677+02:00" level=debug msg="rpc error: code = FailedPrecondition desc = no pubsub is configured" app_id=checkout-sdk instance=FI-101 scope=dapr.runtime.grpc.api type=log ver=1.10.6
== APP == Unhandled exception. Dapr.DaprException: Publish operation failed: the Dapr endpoint indicated a failure. See InnerException for details.
== APP ==  ---> Grpc.Core.RpcException: Status(StatusCode="FailedPrecondition", Detail="no pubsub is configured")
== APP ==    at Dapr.Client.DaprClientGrpc.MakePublishRequest(String pubsubName, String topicName, ByteString content, Dictionary`2 metadata, String dataContentType, CancellationToken cancellationToken)
== APP ==    --- End of inner exception stack trace ---
== APP ==    at Dapr.Client.DaprClientGrpc.MakePublishRequest(String pubsubName, String topicName, ByteString content, Dictionary`2 metadata, String dataContentType, CancellationToken cancellationToken)
== APP ==    at Program.<Main>$(String[] args) in C:\Dev\Github\quickstarts\pub_sub\csharp\sdk\checkout\Program.cs:line 11
== APP ==    at Program.<Main>(String[] args)
The App process exited with error code: exit status 0xe0434352
```

Here is my docker ps just in case:

```
0649f886c56c   redis:6              "docker-entrypoint.s…"   3 days ago     Up 3 minutes          0.0.0.0:6379->6379/tcp             dapr_redis
f5b5bd1d2ccb   daprio/dapr:1.10.6   "./placement"            3 days ago     Up 3 minutes          0.0.0.0:6050->50005/tcp            dapr_placement
7b4352daff7d   openzipkin/zipkin    "start-zipkin"           3 days ago     Up 3 days (healthy)   9410/tcp, 0.0.0.0:9411->9411/tcp   dapr_zipkin
```

**Comment by acoLMO** [comment]
Quick update: After some testing, it seems the problem does not from the PubSub component but components in general.

I have the same problem with de fault statestore component (also defined when running `dapr init`)

it seems components are not loading properly on a windows self-hosted environnement. Can anyone make default component work on a windows self-hosted env with dapr 1.10?

```
CLI version: 1.10.0
Runtime version: 1.10.6
````

PS: if I start a sidecar in the docker containers, it works. But I would like to avoid working in this setup

**Comment by LucienMoor** [comment]
Late update: After reinstalling windows, everything is working as expected. But not a great solution. I think something on my PC was interfering with Dapr, but I have no way to know what it was.

It would be great if we could have more details on components loading process in the daprd log?
