### ISSUE TITLE
Zookeeper

### ISSUE THREAD

**Issue by pamav** [dapr/dapr#6695]
Hi,
Dapr StateManagement -> components Zookeeper

After call 
 await daprClient.SaveStateAsync("zookeeper",0);
I got exception

Dapr Exception:
Unhandled exception. Dapr.DaprException: State operation failed: the Dapr endpoint indicated a failure. See InnerException for details.
== APP ==  ---> Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="failed saving state in state store zookeeper: zk: invalid path")
== APP ==    at Dapr.Client.DaprClientGrpc.MakeSaveStateCallAsync[TValue](String storeName, String key, TValue value, String etag, StateOptions stateOptions, IReadOnlyDictionary`2 metadata, CancellationToken cancellationToken)
== APP ==    --- End of inner exception stack trace ---
== APP ==    at Dapr.Client.DaprClientGrpc.MakeSaveStateCallAsync[TValue](String storeName, String key, TValue value, String etag, StateOptions stateOptions, IReadOnlyDictionary`2 metadata, CancellationToken cancellationToken)

zookeeper log:
[NIOWorkerThread-1:o.a.z.s.ZooKeeperServer@1422] - Connection request from old client /172.17.0.1:42248; will be dropped if server is in r-o mode
INFO  [SyncThread:0:o.a.z.s.p.FileTxnLog@285] - Creating new log file: log.1
INFO  [NIOWorkerThread-3:o.a.z.s.NIOServerCnxn@337] - Unable to read additional data from client, it probably closed the socket: address = /172.17.0.1:42248, session = 0x10000

Zookeeper version :3.8.1
Dapr version: 1.11.1
Docker version:24.0.2

**Comment by ItalyPaleAle** [comment]
@pamav could you please share the logs from the daprd container too when the panic happens?

**Comment by pamav** [comment]
here is dapr logs:


dapr run --app-id daprCounter --components-path "./components" -- dotnet run --project ./DaprCounter.csproj
Flag --components-path has been deprecated, This flag is deprecated and will be removed in the future releases. Use "resources-path" flag instead
Starting Dapr with id daprCounter. HTTP Port: 63014. gRPC Port: 63015
Checking if Dapr sidecar is listening on HTTP port 63014
time="2023-07-20T06:55:03.3075013+02:00" level=info msg="starting Dapr Runtime -- version 1.11.1 -- commit 204163e75fcfd4d56b6cdbb849265b223372aab0" app_id=daprCounter instance=RDiGregac scope=dapr.runtime type=log ver=1.11.1
time="2023-07-20T06:55:03.3081282+02:00" level=info msg="log level set to: info" app_id=daprCounter instance=RDiGregac scope=dapr.runtime type=log ver=1.11.1
time="2023-07-20T06:55:03.3087116+02:00" level=info msg="metrics server started on :63016/" app_id=daprCounter instance=RDiGregac scope=dapr.metrics type=log ver=1.11.1
time="2023-07-20T06:55:03.3109992+02:00" level=info msg="Resiliency configuration loaded" app_id=daprCounter instance=RDiGregac scope=dapr.runtime type=log ver=1.11.1
time="2023-07-20T06:55:03.3115794+02:00" level=info msg="standalone mode configured" app_id=daprCounter instance=RDiGregac scope=dapr.runtime type=log ver=1.11.1
time="2023-07-20T06:55:03.3115794+02:00" level=info msg="app id: daprCounter" app_id=daprCounter instance=RDiGregac scope=dapr.runtime type=log ver=1.11.1
time="2023-07-20T06:55:03.3115794+02:00" level=info msg="mTLS is disabled. Skipping certificate request and tls validation" app_id=daprCounter instance=RDiGregac scope=dapr.runtime type=log ver=1.11.1
time="2023-07-20T06:55:03.3121267+02:00" level=info msg="Dapr trace sampler initialized: DaprTraceSampler(P=1.000000)" app_id=daprCounter instance=RDiGregac scope=dapr.runtime type=log ver=1.11.1
time="2023-07-20T06:55:03.3156728+02:00" level=info msg="local service entry announced: daprCounter -> 172.20.134.207:63017" app_id=daprCounter component="mdns (nameResolution/v1)" instance=RDiGregac scope=dapr.contrib type=log ver=1.11.1
time="2023-07-20T06:55:03.3156728+02:00" level=info msg="Initialized name resolution to mdns" app_id=daprCounter instance=RDiGregac scope=dapr.runtime type=log ver=1.11.1
time="2023-07-20T06:55:03.3164382+02:00" level=info msg="Loading components…" app_id=daprCounter instance=RDiGregac scope=dapr.runtime type=log ver=1.11.1
time="2023-07-20T06:55:03.3169632+02:00" level=info msg="Waiting for all outstanding components to be processed" app_id=daprCounter instance=RDiGregac scope=dapr.runtime type=log ver=1.11.1
time="2023-07-20T06:55:03.3253075+02:00" level=info msg="Component loaded: zookeeper (state.zookeeper/v1)" app_id=daprCounter instance=RDiGregac scope=dapr.runtime type=log ver=1.11.1
time="2023-07-20T06:55:03.3258463+02:00" level=info msg="All outstanding components processed" app_id=daprCounter instance=RDiGregac scope=dapr.runtime type=log ver=1.11.1
time="2023-07-20T06:55:03.3261084+02:00" level=info msg="Loading endpoints" app_id=daprCounter instance=RDiGregac scope=dapr.runtime type=log ver=1.11.1
2023/07/20 06:55:03 connected to [::1]:2181
time="2023-07-20T06:55:03.3289625+02:00" level=info msg="Waiting for all outstanding http endpoints to be processed" app_id=daprCounter instance=RDiGregac scope=dapr.runtime type=log ver=1.11.1
time="2023-07-20T06:55:03.3289625+02:00" level=info msg="All outstanding http endpoints processed" app_id=daprCounter instance=RDiGregac scope=dapr.runtime type=log ver=1.11.1
time="2023-07-20T06:55:03.3297133+02:00" level=info msg="gRPC proxy enabled" app_id=daprCounter instance=RDiGregac scope=dapr.runtime type=log ver=1.11.1
time="2023-07-20T06:55:03.330298+02:00" level=info msg="gRPC server listening on TCP address: :63015" app_id=daprCounter instance=RDiGregac scope=dapr.runtime.grpc.api type=log ver=1.11.1
time="2023-07-20T06:55:03.3308645+02:00" level=info msg="Enabled gRPC tracing middleware" app_id=daprCounter instance=RDiGregac scope=dapr.runtime.grpc.api type=log ver=1.11.1
time="2023-07-20T06:55:03.3308645+02:00" level=info msg="Enabled gRPC metrics middleware" app_id=daprCounter instance=RDiGregac scope=dapr.runtime.grpc.api type=log ver=1.11.1
time="2023-07-20T06:55:03.3326934+02:00" level=info msg="configuring workflow engine gRPC endpoint" app_id=daprCounter instance=RDiGregac scope=dapr.runtime.wfengine type=log ver=1.11.1
time="2023-07-20T06:55:03.3333281+02:00" level=info msg="API gRPC server is running on port 63015" app_id=daprCounter instance=RDiGregac scope=dapr.runtime type=log ver=1.11.1
time="2023-07-20T06:55:03.333926+02:00" level=info msg="enabled metrics http middleware" app_id=daprCounter instance=RDiGregac scope=dapr.runtime.http type=log ver=1.11.1
time="2023-07-20T06:55:03.3352312+02:00" level=info msg="enabled tracing http middleware" app_id=daprCounter instance=RDiGregac scope=dapr.runtime.http type=log ver=1.11.1
time="2023-07-20T06:55:03.3359046+02:00" level=info msg="HTTP server listening on TCP address: :63014" app_id=daprCounter instance=RDiGregac scope=dapr.runtime.http type=log ver=1.11.1
time="2023-07-20T06:55:03.3359046+02:00" level=info msg="http server is running on port 63014" app_id=daprCounter instance=RDiGregac scope=dapr.runtime type=log ver=1.11.1
time="2023-07-20T06:55:03.3365321+02:00" level=info msg="The request body size parameter is: 4" app_id=daprCounter instance=RDiGregac scope=dapr.runtime type=log ver=1.11.1
time="2023-07-20T06:55:03.3389624+02:00" level=info msg="gRPC server listening on TCP address: :63017" app_id=daprCounter instance=RDiGregac scope=dapr.runtime.grpc.internal type=log ver=1.11.1
time="2023-07-20T06:55:03.339665+02:00" level=info msg="Enabled gRPC tracing middleware" app_id=daprCounter instance=RDiGregac scope=dapr.runtime.grpc.internal type=log ver=1.11.1
time="2023-07-20T06:55:03.339665+02:00" level=info msg="Enabled gRPC metrics middleware" app_id=daprCounter instance=RDiGregac scope=dapr.runtime.grpc.internal type=log ver=1.11.1
time="2023-07-20T06:55:03.340245+02:00" level=info msg="internal gRPC server is running on port 63017" app_id=daprCounter instance=RDiGregac scope=dapr.runtime type=log ver=1.11.1
time="2023-07-20T06:55:03.3418107+02:00" level=warning msg="App channel is not initialized. Did you configure an app-port?" app_id=daprCounter instance=RDiGregac scope=dapr.runtime type=log ver=1.11.1
time="2023-07-20T06:55:03.3423632+02:00" level=info msg="actors: state store is not configured - this is okay for clients but services with hosted actors will fail to initialize!" app_id=daprCounter instance=RDiGregac scope=dapr.runtime type=log ver=1.11.1
time="2023-07-20T06:55:03.343448+02:00" level=info msg="actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s" app_id=daprCounter instance=RDiGregac scope=dapr.runtime.actor type=log ver=1.11.1
time="2023-07-20T06:55:03.3456916+02:00" level=info msg="configuring workflow engine with actors backend" app_id=daprCounter instance=RDiGregac scope=dapr.runtime.wfengine type=log ver=1.11.1
time="2023-07-20T06:55:03.3462098+02:00" level=info msg="Registering component for dapr workflow engine..." app_id=daprCounter instance=RDiGregac scope=dapr.runtime type=log ver=1.11.1
time="2023-07-20T06:55:03.3463188+02:00" level=info msg="initializing Dapr workflow component" app_id=daprCounter component="dapr (workflow.dapr/v1)" instance=RDiGregac scope=dapr.contrib type=log ver=1.11.1
time="2023-07-20T06:55:03.3474817+02:00" level=warning msg="failed to read from bindings: app channel not initialized " app_id=daprCounter instance=RDiGregac scope=dapr.runtime type=log ver=1.11.1
time="2023-07-20T06:55:03.3502458+02:00" level=info msg="dapr initialized. Status: Running. Init Elapsed 38ms" app_id=daprCounter instance=RDiGregac scope=dapr.runtime type=log ver=1.11.1
2023/07/20 06:55:03 authenticated: id=72057594807648257, timeout=15000
2023/07/20 06:55:03 re-submitting `0` credentials after reconnect
time="2023-07-20T06:55:03.4393965+02:00" level=info msg="placement tables updated, version: 0" app_id=daprCounter instance=RDiGregac scope=dapr.runtime.actor.internal.placement type=log ver=1.11.1
Checking if Dapr sidecar is listening on GRPC port 63015
Dapr sidecar is up and running.
Updating metadata for appPID: 1912
Updating metadata for app command: dotnet run --project ./DaprCounter.csproj
You're up and running! Both Dapr and your app logs will appear here.

== APP == Hello, World!
== APP == Unhandled exception. Dapr.DaprException: State operation failed: the Dapr endpoint indicated a failure. See InnerException for details.
== APP ==  ---> Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="fail to get counter from state store zookeeper: zk: invalid path")
== APP ==    at Dapr.Client.DaprClientGrpc.GetStateAsync[TValue](String storeName, String key, Nullable`1 consistencyMode, IReadOnlyDictionary`2 metadata, CancellationToken cancellationToken)
== APP ==    --- End of inner exception stack trace ---
== APP ==    at Dapr.Client.DaprClientGrpc.GetStateAsync[TValue](String storeName, String key, Nullable`1 consistencyMode, IReadOnlyDictionary`2 metadata, CancellationToken cancellationToken)
== APP ==    at Program.<Main>$(String[] args) in X:\DaprCounter\Program.cs:line 15
== APP ==    at Program.<Main>(String[] args)
The App process exited with error code: exit status 0xe0434352

terminated signal received: shutting down
Exited Dapr successfully
Error exiting App: exit status 0xe0434352

**Comment by ItalyPaleAle** [comment]
Moving to components-contrib as it seems to be an error with the zookeeper component.

Could you also share the Component YAML file?
