### ISSUE TITLE
mysql storestate error

### ISSUE THREAD

**Issue by JanFrank** [dapr/dapr#6706]
My Dapr Version:
``` console
F:\Project\TestDapr\LearnDapr\FirstApi>dapr --version
CLI version: 1.11.0-rc.2
Runtime version: 1.11.0-rc.6
```

mysqlstatestore.yaml:
``` yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mysqlstatestore
spec:
  type: state.mysql
  version: v1
  metadata:
  - name: connectionString
    value: "root:123456@tcp(127.0.0.1:3306)/?allowNativePasswords=true"
  - name: schemaName
    value: "dapr_state_store"
  - name: tableName
    value: "dapr_state"
  - name: actorStateStore
    value: "true"
```

my Code like this:
``` cShapr
//program.cs  files:
...
            app.MapGet("/teststore", async (HttpContext httpcontext) => 
            {

                await client.SaveStateAsync("mysqlstatestore", "MyTestVal", "TheIsValue");

                var theVal= await client.GetStateAsync<string>("mysqlstatestore", "MyTestVal");
                return new {theVal };
            });
...
```

I run my demo in console like this:
``` sharp
dapr run --app-id myserver --app-port 5001 -- dotnet run --no-build
```

the exec logs:(key word: "'IF NOT EXISTS DaprSaveFirstWriteV1(tableName VARCHAR(255), id VARCHAR(255), valu' at line 1" )
``` console
F:\Project\TestDapr\LearnDapr\FirstApi\Assignment.Server>dapr run --app-id myserver --app-port 5001 -- dotnet run --no-build
Starting Dapr with id myserver. HTTP Port: 54849. gRPC Port: 54850
time="2023-07-21T08:33:43.7559628+08:00" level=info msg="starting Dapr Runtime -- version 1.11.0-rc.6 -- commit a2c91952a3557e5dd9744d02fd3fdeaee41598ce" app_id=myserver instance=RD-zengfennan scope=dapr.runtime type=log ver=1.11.0-rc.6
time="2023-07-21T08:33:43.7564668+08:00" level=info msg="log level set to: info" app_id=myserver instance=RD-zengfennan scope=dapr.runtime type=log ver=1.11.0-rc.6
time="2023-07-21T08:33:43.7570893+08:00" level=info msg="metrics server started on :54851/" app_id=myserver instance=RD-zengfennan scope=dapr.metrics type=log ver=1.11.0-rc.6
time="2023-07-21T08:33:43.7619047+08:00" level=info msg="Resiliency configuration loaded" app_id=myserver instance=RD-zengfennan scope=dapr.runtime type=log ver=1.11.0-rc.6
time="2023-07-21T08:33:43.7619047+08:00" level=info msg="standalone mode configured" app_id=myserver instance=RD-zengfennan scope=dapr.runtime type=log ver=1.11.0-rc.6
time="2023-07-21T08:33:43.7624226+08:00" level=info msg="app id: myserver" app_id=myserver instance=RD-zengfennan scope=dapr.runtime type=log ver=1.11.0-rc.6
time="2023-07-21T08:33:43.7629377+08:00" level=info msg="mTLS is disabled. Skipping certificate request and tls validation" app_id=myserver instance=RD-zengfennan scope=dapr.runtime type=log ver=1.11.0-rc.6
time="2023-07-21T08:33:43.7634852+08:00" level=info msg="Dapr trace sampler initialized: DaprTraceSampler(P=1.000000)" app_id=myserver instance=RD-zengfennan scope=dapr.runtime type=log ver=1.11.0-rc.6
time="2023-07-21T08:33:43.7807666+08:00" level=info msg="local service entry announced: myserver -> 10.100.76.172:54852" app_id=myserver component="mdns (nameResolution/v1)" instance=RD-zengfennan scope=dapr.contrib type=log ver=1.11.0-rc.6time="2023-07-21T08:33:43.7812877+08:00" level=info msg="Initialized name resolution to mdns" app_id=myserver instance=RD-zengfennan scope=dapr.runtime type=log ver=1.11.0-rc.6
time="2023-07-21T08:33:43.7818079+08:00" level=info msg="Loading components…" app_id=myserver instance=RD-zengfennan scope=dapr.runtime type=log ver=1.11.0-rc.6
time="2023-07-21T08:33:43.7937316+08:00" level=info msg="Connected to RabbitMQ" app_id=myserver component="myevent (bindings.rabbitmq/v1)" instance=RD-zengfennan scope=dapr.contrib type=log ver=1.11.0-rc.6
time="2023-07-21T08:33:43.7937316+08:00" level=info msg="successful init for output binding myevent (bindings.rabbitmq/v1)" app_id=myserver instance=RD-zengfennan scope=dapr.runtime type=log ver=1.11.0-rc.6
time="2023-07-21T08:33:43.8366179+08:00" level=info msg="Connected to RabbitMQ" app_id=myserver component="myevent (bindings.rabbitmq/v1)" instance=RD-zengfennan scope=dapr.contrib type=log ver=1.11.0-rc.6
time="2023-07-21T08:33:43.8366179+08:00" level=info msg="successful init for input binding myevent (bindings.rabbitmq/v1)" app_id=myserver instance=RD-zengfennan scope=dapr.runtime type=log ver=1.11.0-rc.6
time="2023-07-21T08:33:43.8371373+08:00" level=info msg="Component loaded: myevent (bindings.rabbitmq/v1)" app_id=myserver instance=RD-zengfennan scope=dapr.runtime type=log ver=1.11.0-rc.6
time="2023-07-21T08:33:43.8433828+08:00" level=info msg="Connected to RabbitMQ" app_id=myserver component="emailbing (bindings.rabbitmq/v1)" instance=RD-zengfennan scope=dapr.contrib type=log ver=1.11.0-rc.6
time="2023-07-21T08:33:43.8439024+08:00" level=info msg="successful init for output binding emailbing (bindings.rabbitmq/v1)" app_id=myserver instance=RD-zengfennan scope=dapr.runtime type=log ver=1.11.0-rc.6
time="2023-07-21T08:33:43.8501849+08:00" level=info msg="Connected to RabbitMQ" app_id=myserver component="emailbing (bindings.rabbitmq/v1)" instance=RD-zengfennan scope=dapr.contrib type=log ver=1.11.0-rc.6
time="2023-07-21T08:33:43.8501849+08:00" level=info msg="successful init for input binding emailbing (bindings.rabbitmq/v1)" app_id=myserver instance=RD-zengfennan scope=dapr.runtime type=log ver=1.11.0-rc.6
time="2023-07-21T08:33:43.8507066+08:00" level=info msg="Component loaded: emailbing (bindings.rabbitmq/v1)" app_id=myserver instance=RD-zengfennan scope=dapr.runtime type=log ver=1.11.0-rc.6
time="2023-07-21T08:33:43.8543474+08:00" level=info msg="Component loaded: lockstore (lock.redis/v1)" app_id=myserver instance=RD-zengfennan scope=dapr.runtime type=log ver=1.11.0-rc.6
time="2023-07-21T08:33:43.8653145+08:00" level=warning msg="Error processing component, daprd process will exit gracefully" app_id=myserver instance=RD-zengfennan scope=dapr.runtime type=log ver=1.11.0-rc.6
time="2023-07-21T08:33:43.8653145+08:00" level=fatal msg="process component mysqlstatestore error: [INIT_COMPONENT_FAILURE]: initialization error occurred for mysqlstatestore (state.mysql/v1): Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS DaprSaveFirstWriteV1(tableName VARCHAR(255), id VARCHAR(255), valu' at line 1" app_id=myserver instance=RD-zengfennan scope=dapr.runtime type=log ver=1.11.0-rc.6
The daprd process exited with error code: exit status 1
== APP == info: Microsoft.Hosting.Lifetime[14]
== APP ==       Now listening on: http://localhost:5001
== APP == info: Microsoft.Hosting.Lifetime[0]
== APP ==       Application started. Press Ctrl+C to shut down.
== APP == info: Microsoft.Hosting.Lifetime[0]
== APP ==       Hosting environment: Development
== APP == info: Microsoft.Hosting.Lifetime[0]
== APP ==       Content root path: F:\Project\TestDapr\LearnDapr\FirstApi\Assignment.Server\
== APP == info: Microsoft.Hosting.Lifetime[0]
== APP ==       Application is shutting down...
Exited App successfully
Could not update sidecar metadata for cliPID: PUT http://127.0.0.1:54849/v1.0/metadata/cliPID giving up after 5 attempt(s): Put "http://127.0.0.1:54849/v1.0/metadata/cliPID": dial tcp 127.0.0.1:54849: connectex: No connection could be made because the target machine actively refused it.
Updating metadata for appPID: 35152
```

when i connet to mysql,i found it created  schema:'dapr_state_store',table:'dapr_state'.
when i call http://localhost:5002/teststore ,  i got the error:

RpcException: Status(StatusCode="Unavailable", Detail="Error connecting to subchannel.", DebugException="System.Net.Sockets.SocketException (10061): 由于目标计算机积极拒绝，无法连接。
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
at Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport.TryConnectAsync(CancellationToken cancellationToken)")

but i am sure the mysql ip&port is right. what should i do ?

**Comment by JanFrank** [comment]
by the way ,mysql version is  8.0.25
