### ISSUE TITLE
dapr crash exit

### ISSUE THREAD

**Issue by haowaiwai** [dapr/dapr#6846]
## In what area(s)?

> /area placement

## What version of Dapr?

> daprio/daprd:edge

## Expected Behavior

crash exit

## Actual Behavior

```
cedge-ndn-dapr-1      | panic: runtime error: invalid memory address or nil pointer dereference
cedge-ndn-dapr-1      | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3a71d08]
cedge-ndn-dapr-1      | 
cedge-ndn-dapr-1      | goroutine 300 [running]:
cedge-ndn-dapr-1      | 
cedge-ndn-dapr-1      | github.com/dapr/dapr/pkg/messaging.(*directMessaging).invokeWithRetry.func1({0x57a3d40?, 0x4000b40980?})
cedge-ndn-dapr-1      |         /home/runner/work/dapr/dapr/pkg/messaging/direct_messaging.go:198 +0x178
cedge-ndn-dapr-1      | github.com/dapr/dapr/pkg/resiliency.NewRunnerWithOptions[...].func2.4()
cedge-ndn-dapr-1      |         /home/runner/work/dapr/dapr/pkg/resiliency/policy.go:180 +0x48
cedge-ndn-dapr-1      | github.com/dapr/kit/retry.NotifyRecoverWithData[...].func1()
cedge-ndn-dapr-1      |         /home/runner/go/pkg/mod/github.com/dapr/kit@v0.0.4/retry/retry.go:179 +0x34
cedge-ndn-dapr-1      | github.com/cenkalti/backoff/v4.doRetryNotify[...](0x40012b6850?, {0x577ddb0, 0x4000c118e0}, 0x40012b6830, {0x0, 0x0?})
cedge-ndn-dapr-1      |         /home/runner/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.2.0/retry.go:88 +0xdc
cedge-ndn-dapr-1      | github.com/cenkalti/backoff/v4.RetryNotifyWithData[...](...)
cedge-ndn-dapr-1      |         /home/runner/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.2.0/retry.go:54
cedge-ndn-dapr-1      | github.com/dapr/kit/retry.NotifyRecoverWithData[...](0x4000e46938?, {0x577ddb0?, 0x4000c118e0?}, 0x4000e46920?, 0x4000e46908?)
cedge-ndn-dapr-1      |         /home/runner/go/pkg/mod/github.com/dapr/kit@v0.0.4/retry/retry.go:178 +0xc0
cedge-ndn-dapr-1      | github.com/dapr/dapr/pkg/resiliency.NewRunnerWithOptions[...].func2()
cedge-ndn-dapr-1      |         /home/runner/work/dapr/dapr/pkg/resiliency/policy.go:178 +0x318
cedge-ndn-dapr-1      | github.com/dapr/dapr/pkg/messaging.(*directMessaging).invokeWithRetry(0x40001f8300, {0x57a3d40, 0x4000b40980}, 0x1?, 0x4000e46a68?, {{0x4000fd98b8, 0x5}, {0x0, 0x0}, {0x0, ...}}, ...)
cedge-ndn-dapr-1      |         /home/runner/work/dapr/dapr/pkg/messaging/direct_messaging.go:184 +0x194
cedge-ndn-dapr-1      | github.com/dapr/dapr/pkg/messaging.(*directMessaging).Invoke(0x40001f8300, {0x57a3d40, 0x4000b40980}, {0x4000fd98b8?, 0x4217700?}, 0x4000e46ba8?)
cedge-ndn-dapr-1      |         /home/runner/work/dapr/dapr/pkg/messaging/direct_messaging.go:139 +0x170
cedge-ndn-dapr-1      | github.com/dapr/dapr/pkg/http.(*api).onDirectMessage.func1(
cedge-ndn-dapr-1      | {0x57a3d40?, 0x4000b40980?})
cedge-ndn-dapr-1      |         /home/runner/work/dapr/dapr/pkg/http/api.go:1687 +0x5c
cedge-ndn-dapr-1      | github.com/dapr/dapr/pkg/resiliency.NewRunnerWithOptions[...].func2()
cedge-ndn-dapr-1      |         /home/runner/work/dapr/dapr/pkg/resiliency/policy.go:173 +0x338
cedge-ndn-dapr-1      | github.com/dapr/dapr/pkg/http.(*api).onDirectMessage(0x4000bb4340, 0x40012e5200)
cedge-ndn-dapr-1      |         /home/runner/work/dapr/dapr/pkg/http/api.go:1686 +0x558
cedge-ndn-dapr-1      | github.com/fasthttp/router.(*Router).Handler(0x40008602a0, 0x40012e5200)
cedge-ndn-dapr-1      |         /home/runner/go/pkg/mod/github.com/fasthttp/router@v1.4.15/router.go:427 +0x78c
cedge-ndn-dapr-1      | github.com/dapr/dapr/utils/nethttpadaptor.NewNetHTTPHandlerFunc.func1({0x57907f0, 0x4000b31ec0}, 0x400034d000)
cedge-ndn-dapr-1      |         /home/runner/work/dapr/dapr/utils/nethttpadaptor/nethttpadaptor.go:79 +0x86c
cedge-ndn-dapr-1      | net/http.HandlerFunc.ServeHTTP(0x4001038000?, {0x57907f0?, 0x4000b31ec0?}, 0x1?)
cedge-ndn-dapr-1      |         /opt/hostedtoolcache/go/1.19.5/x64/src/net/http/server.go:2109 +0x38
cedge-ndn-dapr-1      | github.com/dapr/dapr/utils/fasthttpadaptor.NewFastHTTPHandler.func1(0x4001038000)
cedge-ndn-dapr-1      |         /home/runner/work/dapr/dapr/utils/fasthttpadaptor/adaptor.go:58 +0x1b4
cedge-ndn-dapr-1      | github.com/dapr/dapr/pkg/diagnostics.(*httpMetrics).FastHTTPMiddleware.func1(0x4001038000)
cedge-ndn-dapr-1      |         /home/runner/work/dapr/dapr/pkg/diagnostics/http_monitoring.go:227 +0xfc
cedge-ndn-dapr-1      | github.com/dapr/dapr/pkg/diagnostics.HTTPTraceMiddleware.func1(
cedge-ndn-dapr-1      | 0x4001038000)
cedge-ndn-dapr-1      |         /home/runner/work/dapr/dapr/pkg/diagnostics/http_tracing.go:55 +0x144
cedge-ndn-dapr-1      | github.com/valyala/fasthttp.(*Server).serveConn(0x4000990400, {0x57bd8b8?, 0x40012c20a0})
cedge-ndn-dapr-1      |         /home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.44.0/server.go:2372 +0xe0c
cedge-ndn-dapr-1      | github.com/valyala/fasthttp.(*workerPool).workerFunc(0x400076e3c0, 0x40013d7c00)
cedge-ndn-dapr-1      |         /home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.44.0/workerpool.go:224 +0x70
cedge-ndn-dapr-1      | github.com/valyala/fasthttp.(*workerPool).getCh.func1()
cedge-ndn-dapr-1      |         /home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.44.0/workerpool.go:196 +0x38
cedge-ndn-dapr-1      | created by github.com/valyala/fasthttp.(*workerPool).getCh
cedge-ndn-dapr-1      |         /home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.44.0/workerpool.go:195 +0x230
cedge-ndn-dapr-1 exited with code 2
```

## Release Note

RELEASE NOTE:

**Comment by ls-2018** [comment]
I am very interested in this problem and I will try to solve it.

**Comment by ls-2018** [comment]
@yaron2

**Comment by ls-2018** [comment]
Can you provide more information, for example？

- ./daprd -build-info 
- ./daprd -version

**Comment by haowaiwai** [comment]
> * daprd -build-info

Because of the upgrade, I am not sure which version, thanks
starting Dapr Runtime -- version edge -- commit da1d01fb50c9f9755613a451edae045e7f576b6d
or
Starting Dapr Runtime -- version edge -- commit 7371a5c9bd8b1247649724057409482064892591

**Comment by ls-2018** [comment]
I think I found out why.
