### ISSUE TITLE
Crash if actors could not be initilized

### ISSUE THREAD

**Issue by adrianlzt** [dapr/dapr#702]
## In what area(s)?

/area runtime

## What version of Dapr?

0.1.1

## Expected Behavior
Fail nicely.

## Actual Behavior
daprd crashes if actors could not be initialized properly.

## Steps to Reproduce the Problem
I was trying to debug some problem with the container not being able to check app port was listening and I'm also using kind as the kubernetes provider, so probably this is not going to work never, but I guess that panic is unexpected anyways.
```
sudo nsenter -t 1109984 -n daprd -logtostderr -v 5 --mode kubernetes --dapr-http-port 3500 --dapr-grpc-port 50001  --dapr-id nodeapp --control-plane-address http://dapr-api.default.svc.cluster.local --protocol http --placement-address dapr-placement.default.svc.cluster.local:80 --config  --enable-profiling false --log-level info --max-concurrency -1
INFO[0000] starting Dapr Runtime -- version 0.1.0 -- commit 4358565-dirty
INFO[0000] log level set to: info
WARN[0030] error loading config: lookup dapr-api.default.svc.cluster.local on 172.30.0.1:53: no such host. loading default config
INFO[0030] kubernetes mode configured
INFO[0030] dapr id: nodeapp
WARN[0060] failed to load components: lookup dapr-api.default.svc.cluster.local on 172.30.0.1:53: no such host
WARN[0060] failed to init input bindings: app channel not initialized
WARN[0060] failed to init actors: actors: state store must be present to initialize the actor runtime
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1e06bcb]

goroutine 1 [running]:
github.com/dapr/dapr/pkg/runtime.(*DaprRuntime).startHTTPServer(0xc00012e580, 0xdac, 0x1e61, 0x235abe1, 0x1)
        /home/vsts/work/1/s/gopath/src/github.com/dapr/dapr/pkg/runtime/runtime.go:409 +0x23b
github.com/dapr/dapr/pkg/runtime.(*DaprRuntime).initRuntime(0xc00012e580, 0x23652ac, 0xb)
        /home/vsts/work/1/s/gopath/src/github.com/dapr/dapr/pkg/runtime/runtime.go:160 +0x381
github.com/dapr/dapr/pkg/runtime.(*DaprRuntime).Run(0xc00012e580, 0x0, 0xc00012e580)
        /home/vsts/work/1/s/gopath/src/github.com/dapr/dapr/pkg/runtime/runtime.go:105 +0x166
main.main()
        /home/vsts/work/1/s/gopath/src/github.com/dapr/dapr/cmd/daprd/main.go:111 +0x1038
```

**Comment by yaron2** [comment]
Is this happening with using the k8s operator?

How do we reproduce this?

**Comment by yaron2** [comment]
Just to make sure, this is sort of expected if you are trying to run with kubernetes mode out side of kubernetes..

**Comment by adrianlzt** [comment]
It was simulating the same behaviour of the sidecar, but from outside of k8s.
If this error is expected, nothing to add.
Thanks
