### ISSUE TITLE
GRPC data receive limits

### ISSUE THREAD

**Issue by dgunseli** [dapr/dapr#7218]
## What version of Dapr?
Runtime version
`
CLI version: 1.12.0
Runtime version: 1.12.0
`

Client Versions
`
<PackageReference Include="Dapr.Client" Version="1.12.0" />
<PackageReference Include="Dapr.Workflow" Version="1.12.0" />
<PackageReference Include="Dapr.AspNetCore" Version="1.12.0" />
`

## Expected Behavior

When I call a workflow with a message size higher than default GRPC size after setting parameters `daprHTTPMaxRequestSize` and `UseGrpcChannelOptions` with higher data size, it is expected that this request is accepted by the workflow and workflow is being executed.

## Actual Behavior
When I call the workflow, I receive "ResourceExhausted" error with detail "Received message exceeds the maximum configured message size.". Detailed stack trace is below:

```
== APP - dapr-sample-app ==       Unexpected error in handling of instance ID ''.
== APP - dapr-sample-app ==       Grpc.Core.RpcException: Status(StatusCode="ResourceExhausted", Detail="Received message exceeds the maximum configured message size.")
== APP - dapr-sample-app ==          at Grpc.Net.Client.Internal.StreamExtensions.ReadMessageAsync[TResponse](Stream responseStream, GrpcCall call, Func`2 deserializer, String grpcEncoding, Boolean singleMessage, CancellationToken cancellationToken)
== APP - dapr-sample-app ==          at Grpc.Net.Client.Internal.HttpContentClientStreamReader`2.MoveNextCore(CancellationToken cancellationToken)
== APP - dapr-sample-app ==          at Microsoft.DurableTask.GrpcExtensions.ReadAllAsync[T](IAsyncStreamReader`1 reader, CancellationToken cancellationToken)+MoveNext()
== APP - dapr-sample-app ==          at Microsoft.DurableTask.GrpcExtensions.ReadAllAsync[T](IAsyncStreamReader`1 reader, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
== APP - dapr-sample-app ==          at Microsoft.DurableTask.Worker.Grpc.GrpcDurableTaskWorker.Processor.ProcessWorkItemsAsync(AsyncServerStreamingCall`1 stream, CancellationToken cancellation)
== APP - dapr-sample-app ==          at Microsoft.DurableTask.Worker.Grpc.GrpcDurableTaskWorker.Processor.ProcessWorkItemsAsync(AsyncServerStreamingCall`1 stream, CancellationToken cancellation)
== APP - dapr-sample-app ==          at Microsoft.DurableTask.Worker.Grpc.GrpcDurableTaskWorker.Processor.ExecuteAsync(CancellationToken cancellation)
```

## Steps to Reproduce the Problem
This issue can be reproduces with the repository below, required directions are in the Readme.md

https://github.com/dgunseli/dapr-grpc-limit

**Comment by humandigital-ruud** [comment]
@dgunseli Did you ever find a workaround for this?
I'm running into exactly this issue.

**Comment by AlanGRutter** [comment]
I have also run into this problem today. I am using workflows to pull change records from Dynamics 365 - the first request always returns all records since I don't have a valid data token. This can be a lot of data and I was trying to pull all pages before returning the response from the activity to the workflow for further processing. 

The communication is internal between the activity and workflow. I know these could be running on different machines (?) but perhaps the limit can be ignored if on the same machine and configurable if not.

I have had to re-think my approach to pull a single page of data and process that before re-scheduling the workflow.

**Comment by samuelya** [comment]
Any suggested workaround until it gets fixed?

**Comment by olitomlinson** [comment]
Keep alive
