### ISSUE TITLE
python workflow flaky

### ISSUE THREAD

**Issue by sicoyle** [dapr/dapr#7229]
## In what area(s)?

> /area runtime

> /area python-sdk

## What version of Dapr?

> 1.12.2

## Expected Behavior

Python SDK Workflow works as expected.

## Actual Behavior

Python SDK Workflow does not work as expected consistently.
Python SDK workflow calling a child workflow also does not work.

## Steps to Reproduce the Problem

Run a dapr workflow using python, and call a child workflow within the parent workflow.

Below you will see that I've modified the sample workflow listed in the python sdk repo:
```
from flask import Flask, request, jsonify
import threading
from time import sleep
from dapr.ext.workflow import WorkflowRuntime, DaprWorkflowContext, WorkflowActivityContext
from dapr.conf import Settings
from dapr.clients import DaprClient
from dapr.clients.exceptions import DaprInternalError
import requests

app = Flask(__name__)

settings = Settings()

counter = 0
instanceId = "exampleInstanceID36"
workflowComponent = "dapr"
workflowName = "hello_world_wf"
inputData = "Hi Counter!"
workflowOptions = dict()
workflowOptions["task_queue"] =  "testQueue"
eventName = "event1"
eventData = "eventData"
nonExistentIDError = "no such instance exists"


def hello_world_wf(ctx: DaprWorkflowContext, input):
    print(f'{input}')
    yield ctx.call_activity(hello_act, input=1)
    yield ctx.call_activity(call_child_workflow, input=1)
    yield ctx.call_activity(generate_report, input=1)

def call_child_workflow(ctx: WorkflowActivityContext, input):
    print(f'Sam TODO to call other workflow!', flush=True)

    workflow_api_endpoint = "http://localhost:3500/v1.0-beta1/workflows/dapr/ChildWorkflow/start?instanceID=child"

    # Input data for the child workflow
    child_workflow_input = {"input_data": "TODO Child Workflow Input Data"}

    dapr_app_id = "workflow"

      # Headers to include in the request
    headers = {
        "Content-Type": "application/json",
        "dapr-app-id": dapr_app_id,
    }

    # Make a POST request to start the child workflow
    response = requests.post(workflow_api_endpoint, json=child_workflow_input, headers=headers)


    if response.status_code == 202:
        print("Child workflow started successfully.")
    else:
        print(f"Failed to start child workflow. Status code: {response.status_code}, Response: {response.text}")

def generate_report(ctx: WorkflowActivityContext, input):
    print(f'Sam success work on report!', flush=True)
    with DaprClient() as client:
        #Using Dapr SDK to invoke output binding
        resp = client.invoke_binding("mybinding", "create", json.dumps("hi"))
        print(f'Sending message: ' + "hi")
        print(f'Sending message: {resp}' + "hi")

def hello_act(ctx: WorkflowActivityContext, input):
    global counter
    counter += input
    print(f'Hi Sam! New counter value is: {counter}!', flush=True)

def run_workflow():
    with DaprClient() as d:
        host = settings.DAPR_RUNTIME_HOST
        port = settings.DAPR_GRPC_PORT
        workflowRuntime = WorkflowRuntime(host, port)
        workflowRuntime = WorkflowRuntime()
        workflowRuntime.register_workflow(hello_world_wf)
        workflowRuntime.register_activity(hello_act)
        workflowRuntime.register_activity(call_child_workflow)
        workflowRuntime.register_activity(generate_report)

        workflowRuntime.start()

        print("==========Start Counter Increase as per Input:==========")
        start_resp = d.start_workflow(
            instance_id=instanceId,
            workflow_component=workflowComponent,
            workflow_name=workflowName,
            input=inputData,
            workflow_options=workflowOptions
        )
        print(f"start_resp {start_resp.instance_id}")

        sleep(15)

        workflowRuntime.shutdown()

# Define an endpoint for starting the workflow
@app.route('/start-workflow', methods=['POST'])
def start_workflow_endpoint():
    # Retrieve input data from the request
    input_data = request.json.get('input_data', None)

    # Run the workflow in a separate thread to avoid blocking the HTTP server
    workflow_thread = threading.Thread(target=run_workflow)
    workflow_thread.start()

    return jsonify({'status': 'Workflow started successfully'}), 202

if __name__ == '__main__':
    # Run the Flask app
    app.run(port=5001)

```

Please let me know if there is a different way to invoke a child workflow from a python sdk perspective, or if this is indeed a dapr runtime workflow engine bug, or both... I'm not as familiar with workflows, so it's hard for me to know.

I've seen an assortment of errors, and it fails more often than not:

Sometimes see this error (even with commenting out the child workflow logic):
```
== APP == Exception in thread Thread-2 (run_workflow):
== APP == Traceback (most recent call last):
== APP ==   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dapr/clients/grpc/client.py", line 1175, in start_workflow
== APP ==     response = self._stub.StartWorkflowBeta1(req)
== APP ==   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/grpc/_channel.py", line 1161, in __call__
== APP ==     return _end_unary_response_blocking(state, call, False, None)
== APP ==   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/grpc/_channel.py", line 1004, in _end_unary_response_blocking
== APP ==     raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
== APP == grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
== APP ==       status = StatusCode.INTERNAL
== APP ==       details = "error starting workflow 'hello_world_wf': unable to start workflow: failed to start orchestration: failed to invoke target 192.168.1.196:55068 after 3 retries. Error: rpc error: code = Unavailable desc = last connection error: connection error: desc = "transport: Error while dialing: dial tcp 192.168.1.196:55068: connect: connection refused""
== APP ==       debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::1%5D:50001 {created_time:"2023-11-22T10:33:08.392675-06:00", grpc_status:13, grpc_message:"error starting workflow \'hello_world_wf\': unable to start workflow: failed to start orchestration: failed to invoke target 192.168.1.196:55068 after 3 retries. Error: rpc error: code = Unavailable desc = last connection error: connection error: desc = \"transport: Error while dialing: dial tcp 192.168.1.196:55068: connect: connection refused\""}"
== APP == >
== APP == 
== APP == During handling of the above exception, another exception occurred:
== APP == 
== APP == Traceback (most recent call last):
== APP ==   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
== APP ==     self.run()
== APP ==   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
== APP ==     self._target(*self._args, **self._kwargs)
== APP ==   File "/Users/samcoyle/go/src/github.com/dapr-volleyball-demo/tournament-workflow/flaskapp.py", line 86, in run_workflow
== APP ==     start_resp = d.start_workflow(
== APP ==   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dapr/clients/grpc/client.py", line 1178, in start_workflow
== APP ==     raise DaprInternalError(err.details())
== APP == dapr.clients.exceptions.DaprInternalError: error starting workflow 'hello_world_wf': unable to start workflow: failed to start orchestration: failed to invoke target 192.168.1.196:55068 after 3 retries. Error: rpc error: code = Unavailable desc = last connection error: connection error: desc = "transport: Error while dialing: dial tcp 192.168.1.196:55068: connect: connection refused"
```

I've also seen:
```
INFO[0003] work item stream established by user-agent: [grpc-python/1.59.3 grpc-c/36.0.0 (osx; chttp2)]  app_id=orderapp instance=Samanthas-MBP-2.lan scope=dapr.runtime.wfengine type=log ver=1.12.2
INFO[0003] Workflow engine started                       app_id=orderapp instance=Samanthas-MBP-2.lan scope=dapr.runtime.wfengine type=log ver=1.12.2
INFO[0003] work item stream established by user-agent: [grpc-python/1.59.3 grpc-c/36.0.0 (osx; chttp2)]  app_id=orderapp instance=Samanthas-MBP-2.lan scope=dapr.runtime.wfengine type=log ver=1.12.2
INFO[0004] Placement tables updated, version: 20         app_id=orderapp instance=Samanthas-MBP-2.lan scope=dapr.runtime.actors.placement type=log ver=1.12.2
== APP == 127.0.0.1 - - [22/Nov/2023 08:38:12] "POST /start-workflow HTTP/1.1" 202 -
INFO[0006] Placement tables updated, version: 21         app_id=orderapp instance=Samanthas-MBP-2.lan scope=dapr.runtime.actors.placement type=log ver=1.12.2
== APP == 2023-11-22 08:38:12.508 durabletask-worker INFO: Starting gRPC worker that connects to dns:localhost:50001
== APP == /Users/samcoyle/go/src/github.com/dapr-volleyball-demo/tournament-workflow/flaskapp.py:87: UserWarning: The Workflow API is a Beta version and is subject to change.
== APP ==   start_resp = d.start_workflow(
INFO[0006] work item stream established by user-agent: [grpc-python/1.59.3 grpc-c/36.0.0 (osx; chttp2)]  app_id=orderapp instance=Samanthas-MBP-2.lan scope=dapr.runtime.wfengine type=log ver=1.12.2
== APP == 2023-11-22 08:38:12.513 durabletask-worker INFO: Successfully connected to dns:localhost:50001. Waiting for work items...
WARN[0006] Redis does not support transaction rollbacks and should not be used in production as an actor state store.  app_id=orderapp component="statestore-actors (state.redis/v1)" instance=Samanthas-MBP-2.lan scope=dapr.contrib type=log ver=1.12.2
INFO[0006] exampleInstanceID35: starting new 'hello_world_wf' instance with ID = 'exampleInstanceID35'.  app_id=orderapp instance=Samanthas-MBP-2.lan scope=wfengine.backend type=log ver=1.12.2
INFO[0011] work item stream established by user-agent: [grpc-python/1.59.3 grpc-c/36.0.0 (osx; chttp2)]  app_id=orderapp instance=Samanthas-MBP-2.lan scope=dapr.runtime.wfengine type=log ver=1.12.2
INFO[0011] work item stream closed                       app_id=orderapp instance=Samanthas-MBP-2.lan scope=dapr.runtime.wfengine type=log ver=1.12.2
== APP == 2023-11-22 08:38:27.533 durabletask-worker INFO: Stopping gRPC worker...
INFO[0021] work item stream closed                       app_id=orderapp instance=Samanthas-MBP-2.lan scope=dapr.runtime.wfengine type=log ver=1.12.2
== APP == 2023-11-22 08:38:27.534 durabletask-worker INFO: Disconnected from dns:localhost:50001
== APP == 2023-11-22 08:38:27.534 durabletask-worker INFO: No longer listening for work items
== APP == 2023-11-22 08:38:27.534 durabletask-worker INFO: Worker shutdown completed
WARN[0036] exampleInstanceID35: execution timed-out and will be retried later: context deadline exceeded  app_id=orderapp instance=Samanthas-MBP-2.lan scope=dapr.runtime.wfengine type=log ver=1.12.2
^Cℹ️  
terminated signal received: shutting down
INFO[0044] Received signal 'interrupt'; beginning shutdown  app_id=orderapp instance=Samanthas-MBP-2.lan scope=dapr.signals type=log ver=1.12.2
✅  Exited Dapr successfully
✅  Exited App successfully
```
On the above, the key bits to me appear to be the `work item stream closed`, then it looks like the gRPC worker stops for some reason, and then I get `context deadline exceeded`. 

## Release Note

RELEASE NOTE:

**Comment by shivamkm07** [comment]
Hi @sicoyle, There are few issues with above code:
1. `http://localhost:3500/v1.0-beta1/workflows/dapr/ChildWorkflow/start?instanceID=child"` -> This is for starting a new workflow with name `ChildWorkflow`. Since you don't have any workflow registered with name `ChildWorkflow`, it would definitely fail. You should first register another workflow named `ChildWorkflow` similar to `hello_world_wf`.
2. The start api used above doesn't create a child workflow. Instead it creates a new workflow with the name passed in API endpoint(`ChildWorkflow` above). It doesn't actually create `a child workflow of the current workflow instance`. For creating a child workflow, you need to use this: https://github.com/dapr/python-sdk/blob/6ee22ebe3c16e880a5935407ddbb55405ba44e57/ext/dapr-ext-workflow/dapr/ext/workflow/dapr_workflow_context.py#L58. Also do note that you can only create a child workflow from a workflow(`hello_world_wf` above) not an activity(like you are doing above). 

These should resolve the issue ideally.

**Comment by sicoyle** [comment]
Okay, thank you for the info! @shivamkm07 I'll have to recheck this out later in the week and see if it resolves my issues.
