### ISSUE TITLE
ERR_DIRECT_INVOKE  fail to invoke, id: 

### ISSUE THREAD

**Issue by wangchao732** [dapr/dapr#7438]
dapr 1.7.0

Occasionally, the call to DAPR is exceptional, for example, a normal call during the day and an inexplicable call fails in the early morning。

error info:   

2024-01-24 02:00:15.236 ERROR 1 --- [nio-8080-exec-1] u.t.b.d.config.GlobalExceptionHandler    : ERR_DIRECT_INVOKE: fail to invoke, id: dapr-service-xxx, err: rpc error: code = Canceled desc = grpc: the client connection is closing

io.dapr.exceptions.DaprException: ERR_DIRECT_INVOKE: fail to invoke, id: dapr-service-xxx, err: rpc error: code = Canceled desc = grpc: the client connection is closing
        at io.dapr.client.DaprHttp$ResponseFutureCallback.onResponse(DaprHttp.java:375) ~[dapr-sdk-1.8.0.jar!/:na]
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) ~[okhttp-4.9.0.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:100) ~[reactor-core-3.4.31.jar!/:3.4.31]
                at reactor.core.publisher.Mono.block(Mono.java:1742) ~[reactor-core-3.4.31.jar!/:3.4.31]
                at uml.tech.bigdata.daprserviceaikesync.util.DaprUtil.invokeMethod(DaprUtil.java:23) ~[classes!/:1.0.0]
                at uml.tech.bigdata.daprserviceaikesync.controller.SyncController.getTerminalResult(SyncController.java:698) ~[classes!/:1.0.0]
                at uml.tech.bigdata.daprserviceaikesync.controller.SyncController.syncInfo(SyncController.java:175) ~[classes!/:1.0.0]
                at uml.tech.bigdata.daprserviceaikesync.controller.SyncController$$FastClassBySpringCGLIB$$8f37428c.invoke(<generated>) ~[classes!/:1.0.0]
                at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.29.jar!/:5.3.29]
                at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.29.jar!/:5.3.29]
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.29.jar!/:5.3.29]
                at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.29.jar!/:5.3.29]
                at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:102) ~[spring-aop-5.3.29.jar!/:5.3.29]
                at uml.tech.bigdata.daprserviceaikesync.config.ServiceLogAspect.before(ServiceLogAspect.java:139) ~[classes!/:1.0.0]
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
                at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
                at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634) ~[spring-aop-5.3.29.jar!/:5.3.29]
                at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624) ~[spring-aop-5.3.29.jar!/:5.3.29]
                at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72) ~[spring-aop-5.3.29.jar!/:5.3.29]
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.29.jar!/:5.3.29]
                at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.29.jar!/:5.3.29]
                at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:102) ~[spring-aop-5.3.29.jar!/:5.3.29]
                at uml.tech.bigdata.daprserviceaikesync.config.ServiceLogAspect.around(ServiceLogAspect.java:84) ~[classes!/:1.0.0]
                at jdk.internal.reflect.GeneratedMethodAccessor16.invoke(Unknown Source) ~[na:na]
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
                at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
                at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634) ~[spring-aop-5.3.29.jar!/:5.3.29]
                at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624) ~[spring-aop-5.3.29.jar!/:5.3.29]

**Comment by yaron2** [comment]
I highly recommend you upgrade to version 1.12.4 and see if the issue still occurs

**Comment by wangchao732** [comment]
> I highly recommend you upgrade to version 1.12.4 and see if the issue still occurs

Thanks for the reply, I will try it.
