### ISSUE TITLE
Actor manager throws a null reference exception when firing actor timer

### ISSUE THREAD

**Issue by jpiquot** [dapr/dapr#7551]
## In what area(s)?
/area runtime

## What version of Dapr?
1.11.6

## Expected Behavior
No errors.

## Actual Behavior
Throws a null reference exception in actor manager.

```
2024-02-20T18:51:12.003247671Z [18:51:12 ERR] Connection id "0HN1I8HFU2SM0", Request id "0HN1I8HFU2SM0:00000102": An unhandled exception was thrown by the application.
2024-02-20T18:51:12.003254071Z **System.NullReferenceException: Object reference not set to an instance of an object.**
2024-02-20T18:51:12.003260471Z    at **Dapr.Actors.Runtime.ActorManager.<>c__DisplayClass25_0.<<FireTimerAsync>g__RequestFunc|0>d.MoveNext()**
2024-02-20T18:51:12.003266671Z --- End of stack trace from previous location ---
2024-02-20T18:51:12.003273671Z    at Dapr.Actors.Runtime.ActorManager.DispatchInternalAsync[T](ActorId actorId, ActorMethodContext actorMethodContext, Func`3 actorFunc, CancellationToken cancellationToken)
2024-02-20T18:51:12.003279971Z    at Dapr.Actors.Runtime.ActorManager.DispatchInternalAsync[T](ActorId actorId, ActorMethodContext actorMethodContext, Func`3 actorFunc, CancellationToken cancellationToken)
2024-02-20T18:51:12.003286471Z    at Dapr.Actors.Runtime.ActorManager.DispatchInternalAsync[T](ActorId actorId, ActorMethodContext actorMethodContext, Func`3 actorFunc, CancellationToken cancellationToken)
2024-02-20T18:51:12.003292771Z    at Dapr.Actors.Runtime.ActorManager.FireTimerAsync(ActorId actorId, Stream requestBodyStream, CancellationToken cancellationToken)
2024-02-20T18:51:12.003299271Z    at Microsoft.AspNetCore.Builder.ActorsEndpointRouteBuilderExtensions.<>c__DisplayClass5_0.<<MapTimerEndpoint>b__0>d.MoveNext()
2024-02-20T18:51:12.003305471Z --- End of stack trace from previous location ---
2024-02-20T18:51:12.003312371Z    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
2024-02-20T18:51:12.003318571Z    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
2024-02-20T18:51:12.003324871Z    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
2024-02-20T18:51:12.003331271Z    at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
2024-02-20T18:51:12.003336771Z    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
2024-02-20T18:51:12.003341771Z    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
2024-02-20T18:51:12.003345771Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2024-02-20T18:51:12.003668370Z [18:51:12 INF] Request finished HTTP/1.1 PUT http://127.0.0.1:80/actors/LogisticsPartnerSalesOrderAggregateActor/LogisticsPartnerSalesOrder-CHR-0031-Spring-Bloomingdales-3246392/method/timer/ContinueProcess application/json 88 - 500 0 - 1.8553ms
2024-02-20T18:51:13.001457002Z [18:51:13 INF] Request starting HTTP/1.1 PUT http://127.0.0.1:80/actors/LogisticsPartnerSalesOrderAggregateActor/LogisticsPartnerSalesOrder-CHR-0031-Spring-Bloomingdales-3246392/method/timer/ContinueProcess application/json 88
2024-02-20T18:51:13.001510902Z [18:51:13 INF] Executing endpoint 'Dapr Actors Timer'
2024-02-20T18:51:13.002176799Z [18:51:13 INF] Executed endpoint 'Dapr Actors Timer'
```

## Steps to Reproduce the Problem

Was initially working well and after a month, the application throws an error.

**Comment by vlardn** [comment]
@jpiquot What was the reason of this exception?
