### ISSUE TITLE
Exception thrown during Job schedule API call

### ISSUE THREAD

**Issue by rochabr** [dapr/dapr#7897]
While running this [HTTP quickstart ](https://github.com/rochabr/quickstarts/tree/distr-scheduler/job/go/http)(not released, yet). Dapr throws an exception and the job is not scheduled.

## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?

1.14 rc.1
> 1.1.x
> 1.0.x
> edge: output of `git describe --dirty`

## Actual Behavior

The API returns an empty response and this exception is thrown in the sidecar:

```
2024/07/05 10:27:23 http: panic serving [::1]:63000: runtime error: invalid memory address or nil pointer dereference
goroutine 94 [running]:
net/http.(*conn).serve.func1()
        /Users/runner/hostedtoolcache/go/1.22.4/arm64/src/net/http/server.go:1898 +0xb0
panic({0x10a4275e0?, 0x10e3d16e0?})
        /Users/runner/hostedtoolcache/go/1.22.4/arm64/src/runtime/panic.go:770 +0x124
github.com/dapr/dapr/pkg/runtime/scheduler/clients.(*Clients).Next(...)
        /Users/runner/work/dapr/dapr/pkg/runtime/scheduler/clients/clients.go:65
github.com/dapr/dapr/pkg/api/universal.(*Universal).ScheduleJobAlpha1(0x1400179c480, {0x10b061120, 0x1400134c660}, 0x1400134c690)
        /Users/runner/work/dapr/dapr/pkg/api/universal/jobs.go:66 +0x464
github.com/dapr/dapr/pkg/api/http.UniversalHTTPHandler[...].func1(0x140016ba240)
        /Users/runner/work/dapr/dapr/pkg/api/http/universal.go:105 +0x10c
net/http.HandlerFunc.ServeHTTP(0x10b061120?, {0x115c4b108?, 0x14000789ae0?}, 0x1049ac7e0?)
        /Users/runner/hostedtoolcache/go/1.22.4/arm64/src/net/http/server.go:2166 +0x38
github.com/dapr/dapr/pkg/api/http.(*server).handle.(*server).unescapeRequestParametersHandler.func1({0x115c4b108, 0x14000789ae0}, 0x140016ba240)
        /Users/runner/work/dapr/dapr/pkg/api/http/server.go:400 +0x78
net/http.HandlerFunc.ServeHTTP(0x80?, {0x115c4b108?, 0x14000789ae0?}, 0x1400129f860?)
        /Users/runner/hostedtoolcache/go/1.22.4/arm64/src/net/http/server.go:2166 +0x38
github.com/dapr/dapr/pkg/api/http.(*server).handle.(*server).addEndpointCtx.func2({0x115c4b108, 0x14000789ae0}, 0x140016ba240)
        /Users/runner/work/dapr/dapr/pkg/api/http/server.go:445 +0xf8
net/http.HandlerFunc.ServeHTTP(0x10a3d00a0?, {0x115c4b108?, 0x14000789ae0?}, 0x14001154365?)
        /Users/runner/hostedtoolcache/go/1.22.4/arm64/src/net/http/server.go:2166 +0x38
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0x1400167f7a0, {0x115c4b108, 0x14000789ae0}, 0x140016ba240)
        /Users/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.11/mux.go:443 +0x26c
net/http.HandlerFunc.ServeHTTP(0x1400188b448?, {0x115c4b108?, 0x14000789ae0?}, 0x10abb79c0?)
        /Users/runner/hostedtoolcache/go/1.22.4/arm64/src/net/http/server.go:2166 +0x38
github.com/dapr/dapr/pkg/middleware/http.(*HTTP).BuildPipelineFromSpec.(*pipeline).http.func1.1({0x115c4b108, 0x14000789ae0}, 0x140016ba240)
        /Users/runner/work/dapr/dapr/pkg/middleware/http/pipeline.go:65 +0x70
net/http.HandlerFunc.ServeHTTP(0x10e3e1b30?, {0x115c4b108?, 0x14000789ae0?}, 0x40?)
        /Users/runner/hostedtoolcache/go/1.22.4/arm64/src/net/http/server.go:2166 +0x38
github.com/dapr/dapr/pkg/diagnostics.(*httpMetrics).HTTPMiddleware-fm.(*httpMetrics).HTTPMiddleware.func1({0x115c4b108, 0x14000789ae0}, 0x140016ba240)
        /Users/runner/work/dapr/dapr/pkg/diagnostics/http_monitoring.go:332 +0x12c
net/http.HandlerFunc.ServeHTTP(0x10e3e19b0?, {0x115c4b108?, 0x14000789ae0?}, 0x10e21be08?)
        /Users/runner/hostedtoolcache/go/1.22.4/arm64/src/net/http/server.go:2166 +0x38
github.com/dapr/dapr/pkg/api/http.(*server).useTracing.func1.HTTPTraceMiddleware.1({0x10b045210, 0x14001678000}, 0x140016ba240)
        /Users/runner/work/dapr/dapr/pkg/diagnostics/http_tracing.go:81 +0x19c
net/http.HandlerFunc.ServeHTTP(0x140016ba120?, {0x10b045210?, 0x14001678000?}, 0x10e500f40?)
        /Users/runner/hostedtoolcache/go/1.22.4/arm64/src/net/http/server.go:2166 +0x38
github.com/dapr/dapr/pkg/api/http.(*server).StartNonBlocking.(*server).useContextSetup.func4.1({0x10b045210, 0x14001678000}, 0x140016ba120)
        /Users/runner/work/dapr/dapr/pkg/api/http/server.go:308 +0xa8
net/http.HandlerFunc.ServeHTTP(0x10b02c1a8?, {0x10b045210?, 0x14001678000?}, 0x10?)
        /Users/runner/hostedtoolcache/go/1.22.4/arm64/src/net/http/server.go:2166 +0x38
github.com/dapr/dapr/pkg/api/http.(*server).useMaxBodySize.MaxBodySizeMiddleware.func1.1({0x10b045210, 0x14001678000}, 0x140016ba120)
        /Users/runner/work/dapr/dapr/pkg/api/http/middlewares.go:33 +0x90
net/http.HandlerFunc.ServeHTTP(0x1400134c570?, {0x10b045210?, 0x14001678000?}, 0x10491228c?)
        /Users/runner/hostedtoolcache/go/1.22.4/arm64/src/net/http/server.go:2166 +0x38
github.com/dapr/dapr/pkg/api/http.StripSlashesMiddleware.func1({0x10b045210, 0x14001678000}, 0x140016ba120)
        /Users/runner/work/dapr/dapr/pkg/api/http/middlewares.go:96 +0x18c
net/http.HandlerFunc.ServeHTTP(0x14001154365?, {0x10b045210?, 0x14001678000?}, 0x14000412408?)
        /Users/runner/hostedtoolcache/go/1.22.4/arm64/src/net/http/server.go:2166 +0x38
github.com/dapr/dapr/pkg/api/http.CleanPathMiddleware.func1({0x10b045210, 0x14001678000}, 0x140016ba120)
        /Users/runner/work/dapr/dapr/pkg/api/http/middlewares.go:115 +0xdc
net/http.HandlerFunc.ServeHTTP(0x10b061158?, {0x10b045210?, 0x14001678000?}, 0x10e3d7760?)
        /Users/runner/hostedtoolcache/go/1.22.4/arm64/src/net/http/server.go:2166 +0x38
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0x1400167f7a0, {0x10b045210, 0x14001678000}, 0x140016ba000)
        /Users/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.11/mux.go:90 +0x280
golang.org/x/net/http2/h2c.h2cHandler.ServeHTTP({{0x10b00cda0?, 0x1400167f7a0?}, 0x1400167f800?}, {0x10b045210, 0x14001678000}, 0x140016ba000)
        /Users/runner/go/pkg/mod/golang.org/x/net@v0.26.0/http2/h2c/h2c.go:125 +0x4c8
net/http.serverHandler.ServeHTTP({0x10b02c1a8?}, {0x10b045210?, 0x14001678000?}, 0x6?)
        /Users/runner/hostedtoolcache/go/1.22.4/arm64/src/net/http/server.go:3137 +0xbc
net/http.(*conn).serve(0x1400046e000, {0x10b061120, 0x14001712390})
        /Users/runner/hostedtoolcache/go/1.22.4/arm64/src/net/http/server.go:2039 +0x508
created by net/http.(*Server).Serve in goroutine 128
        /Users/runner/hostedtoolcache/go/1.22.4/arm64/src/net/http/server.go:3285 +0x3f0
```

## Steps to Reproduce the Problem

The API should return a 202, 400 or 500 response.

## Release Note

RELEASE NOTE:

**Comment by artursouza** [comment]
While I could reproduce this stacktrace and have a fix for it, this also means that the runtime does not have the address for the scheduler service. While the fix will avoid the panic, it will not fix the fact of the sidecar not getting the right cmd arg for scheduler. Can you comment on what wad the command you used to run the sidecar? How did you pass the address for scheduler.

**Comment by artursouza** [comment]
Check 1.14.0-rc.2 once build is done, please. Remember that you might still need to figure out why the sidecar is not getting the scheduler endpoint. It might be related to the CLI bug too, so use 1.14.0-rc.2 for CLI as well.

**Comment by cicoyle** [comment]
Moving to 1.15. We should at least check on if this still happens

**Comment by rochabr** [comment]
@cicoyle isn't this fixed? my runtime can reach the scheduler service without any annotations.

**Comment by mikeee** [comment]
> This issue has been automatically marked as stale because it has not had activity in the last 60 days. It will be closed in the next 7 days unless it is tagged (pinned, good first issue, help wanted or triaged/resolved) or other activity occurs. Thank you for your contributions.

/keep-alive

This isn't quite stale yet, needs confirmation of the issue being resolved
