### ISSUE TITLE
Is it possible to Unregister actors to aid in a graceful shutdown? How to avoid routing actor invocations to a pod that is terminating?

### ISSUE THREAD

**Issue by MattCosturos** [dapr/dapr#8171]
How can we tell the dapr placement service that a pod is shutting down, and should no longer service actor invocations?

Is there any way to UN-register an actor? (in contrast to `services.Actors.RegisterActor<ActorType>("actorName);`

Background : Dapr enabled microservices, hosted in kubernetes, deployed via helm charts.

We have a CI/CD pipeline build new images, push images to a container repository, and then issue a helm deploy cmd. The following sequence of events happens as a result of the helm deploy cmd.

- New pods with new image are started and report ready.
- Placement table update goes out
- Every microservice now sees 2 actor pods it can submit jobs to.
- Kube sends sigterm to old pods. 
- We have entered the DangerZone
- Pods shut down.
- Placement table service sees pods are gone and sends out another update.
- Every microservice now has only 1 actor pod it can submit jobs to.
- Out of the DangerZone.

While in the danger zone, some actor calls get routed to $actorPod_OLD which is in the process of getting terminated. These calls time out 3 times and the calling application logs the following

```
2024-10-04T13:37:05-04:00       Dapr.DaprApiException: error invoke actor method: failed to invoke target 10.1.0.37:50002 after 3 retries. Error: rpc error: code = Unavailable desc = last connection error: connection error: desc = "transport: Error while dialing: dial tcp 10.1.0.37:50002: connect: no route to host"
2024-10-04T13:37:05-04:00          at Dapr.Actors.DaprHttpInteractor.SendAsyncHandleUnsuccessfulResponse(Func`1 requestFunc, String relativeUri, CancellationToken cancellationToken)
2024-10-04T13:37:05-04:00          at Dapr.Actors.DaprHttpInteractor.SendAsync(Func`1 requestFunc, String relativeUri, CancellationToken cancellationToken)
2024-10-04T13:37:05-04:00          at Dapr.Actors.DaprHttpInteractor.InvokeActorMethodWithRemotingAsync(ActorMessageSerializersManager serializersManager, IActorRequestMessage remotingRequestRequestMessage, CancellationToken cancellationToken)
2024-10-04T13:37:05-04:00          at Dapr.Actors.Communication.Client.ActorRemotingClient.InvokeAsync(IActorRequestMessage remotingRequestMessage, CancellationToken cancellationToken)
2024-10-04T13:37:05-04:00          at Dapr.Actors.Client.ActorProxy.InvokeMethodAsync(Int32 interfaceId, Int32 methodId, String methodName, IActorRequestMessageBody requestMsgBodyValue, CancellationToken cancellationToken)
2024-10-04T13:37:05-04:00          at Dapr.Actors.Client.ActorProxy.ContinueWithResult[TRetval](Int32 interfaceId, Int32 methodId, Task`1 task)
``` 

I found various issues about graceful shutdowns, but these seem to be more about having the sidecar and components shutdown correctly. I didn't see any mention of actor service invocations in the issues or PRs I was able to find.

This issue links to PR #4456 which was never merged to master, and then the issues closed as stale.
https://github.com/dapr/dapr/issues/4067
https://github.com/dapr/dapr/pull/4456

https://github.com/dapr/dapr/issues/2478
This issue has a lot of mentions, but i'm not clear on what the changes referenced did for a graceful shutdown. It seems like it was to keep the sidecar running and shut down components gracefully, but not the actor service.

**Comment by vlardn** [comment]
This issue is very annoying when you work with actors and deploy app often. Please help!

**Comment by darraghjones** [comment]
It seems like the dapr runtime should inform the placement server when it's shutting down....rather than relying on a the 'timeout' for the placement service to notice the pod has been killed.
