### ISSUE TITLE
grpc_message:"did not find address for actor dapr.internal.xxx.workflow.workflow/yyy", grpc_status:2

### ISSUE THREAD

**Issue by guybartal** [dapr/dapr#8247]
## In what area(s)?

> /area runtime

## What version of Dapr?

> 1.14.1

## Expected Behavior

workflow will run all activities

## Actual Behavior

```
== APP - media-indexer-workflow == INFO:     127.0.0.1:44654 - "POST /media-indexer-workflow HTTP/1.1" 500 Internal Server Error
== APP - media-indexer-workflow == ERROR:    Exception in ASGI application
== APP - media-indexer-workflow == Traceback (most recent call last):
== APP - media-indexer-workflow ==   File "/home/gubert/.local/share/virtualenvs/multilingual_tts-3R5GsHLL/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
== APP - media-indexer-workflow ==     result = await app(  # type: ignore[func-returns-value]
== APP - media-indexer-workflow ==   File "/home/gubert/.local/share/virtualenvs/multilingual_tts-3R5GsHLL/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
== APP - media-indexer-workflow ==     return await self.app(scope, receive, send)
== APP - media-indexer-workflow ==   File "/home/gubert/.local/share/virtualenvs/multilingual_tts-3R5GsHLL/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
== APP - media-indexer-workflow ==     await super().__call__(scope, receive, send)
== APP - media-indexer-workflow ==   File "/home/gubert/.local/share/virtualenvs/multilingual_tts-3R5GsHLL/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
== APP - media-indexer-workflow ==     await self.middleware_stack(scope, receive, send)
== APP - media-indexer-workflow ==   File "/home/gubert/.local/share/virtualenvs/multilingual_tts-3R5GsHLL/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
== APP - media-indexer-workflow ==     raise exc
== APP - media-indexer-workflow ==   File "/home/gubert/.local/share/virtualenvs/multilingual_tts-3R5GsHLL/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
== APP - media-indexer-workflow ==     await self.app(scope, receive, _send)
== APP - media-indexer-workflow ==   File "/home/gubert/.local/share/virtualenvs/multilingual_tts-3R5GsHLL/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
== APP - media-indexer-workflow ==     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
== APP - media-indexer-workflow ==   File "/home/gubert/.local/share/virtualenvs/multilingual_tts-3R5GsHLL/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
== APP - media-indexer-workflow ==     raise exc
== APP - media-indexer-workflow ==   File "/home/gubert/.local/share/virtualenvs/multilingual_tts-3R5GsHLL/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
== APP - media-indexer-workflow ==     await app(scope, receive, sender)
== APP - media-indexer-workflow ==   File "/home/gubert/.local/share/virtualenvs/multilingual_tts-3R5GsHLL/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
== APP - media-indexer-workflow ==     await self.middleware_stack(scope, receive, send)
== APP - media-indexer-workflow ==   File "/home/gubert/.local/share/virtualenvs/multilingual_tts-3R5GsHLL/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
== APP - media-indexer-workflow ==     await route.handle(scope, receive, send)
== APP - media-indexer-workflow ==   File "/home/gubert/.local/share/virtualenvs/multilingual_tts-3R5GsHLL/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
== APP - media-indexer-workflow ==     await self.app(scope, receive, send)
== APP - media-indexer-workflow ==   File "/home/gubert/.local/share/virtualenvs/multilingual_tts-3R5GsHLL/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
== APP - media-indexer-workflow ==     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
== APP - media-indexer-workflow ==   File "/home/gubert/.local/share/virtualenvs/multilingual_tts-3R5GsHLL/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
== APP - media-indexer-workflow ==     raise exc
== APP - media-indexer-workflow ==   File "/home/gubert/.local/share/virtualenvs/multilingual_tts-3R5GsHLL/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
== APP - media-indexer-workflow ==     await app(scope, receive, sender)
== APP - media-indexer-workflow ==   File "/home/gubert/.local/share/virtualenvs/multilingual_tts-3R5GsHLL/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
== APP - media-indexer-workflow ==     response = await f(request)
== APP - media-indexer-workflow ==   File "/home/gubert/.local/share/virtualenvs/multilingual_tts-3R5GsHLL/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
== APP - media-indexer-workflow ==     raw_response = await run_endpoint_function(
== APP - media-indexer-workflow ==   File "/home/gubert/.local/share/virtualenvs/multilingual_tts-3R5GsHLL/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
== APP - media-indexer-workflow ==     return await dependant.call(**values)
== APP - media-indexer-workflow ==   File "/home/gubert/repos/hackathons/storyteller/src/media-indexer/media-indexer-workflow/app.py", line 97, in process_media_subscriber
== APP - media-indexer-workflow ==     instance_id = wf_client.schedule_new_workflow(workflow=process_media_workflow, input=None)
== APP - media-indexer-workflow ==   File "/home/gubert/.local/share/virtualenvs/multilingual_tts-3R5GsHLL/lib/python3.10/site-packages/dapr/ext/workflow/dapr_workflow_client.py", line 98, in schedule_new_workflow
== APP - media-indexer-workflow ==     return self.__obj.schedule_new_orchestration(
== APP - media-indexer-workflow ==   File "/home/gubert/.local/share/virtualenvs/multilingual_tts-3R5GsHLL/lib/python3.10/site-packages/durabletask/client.py", line 119, in schedule_new_orchestration
== APP - media-indexer-workflow ==     res: pb.CreateInstanceResponse = self._stub.StartInstance(req)
== APP - media-indexer-workflow ==   File "/home/gubert/.local/share/virtualenvs/multilingual_tts-3R5GsHLL/lib/python3.10/site-packages/grpc/_channel.py", line 1181, in __call__
== APP - media-indexer-workflow ==     return _end_unary_response_blocking(state, call, False, None)
== APP - media-indexer-workflow ==   File "/home/gubert/.local/share/virtualenvs/multilingual_tts-3R5GsHLL/lib/python3.10/site-packages/grpc/_channel.py", line 1006, in _end_unary_response_blocking
== APP - media-indexer-workflow ==     raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
== APP - media-indexer-workflow == grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
== APP - media-indexer-workflow ==      status = StatusCode.UNKNOWN
== APP - media-indexer-workflow ==      details = "did not find address for actor dapr.internal.default.media-indexer-workflow.workflow/a1c72be05c0a4387944da17fea458b4c"
== APP - media-indexer-workflow ==      debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:43651 {grpc_message:"did not find address for actor dapr.internal.default.media-indexer-workflow.workflow/a1c72be05c0a4387944da17fea458b4c", grpc_status:2, created_time:"2024-10-28T18:20:10.504545311+02:00"}"
```

## Steps to Reproduce the Problem

# I've simplified the code

```python
wfr = wf.WorkflowRuntime()
wf_client = wf.DaprWorkflowClient()

# Dapr subscription in /dapr/subscribe sets up this route
@app.post('/workflow')
async def process_media_subscriber(request: CloudEventModel):
    instance_id = wf_client.schedule_new_workflow(workflow=process_media_workflow, input=None)

    try:
        state = wf_client.wait_for_workflow_completion(instance_id, timeout_in_seconds=10000)
        if not state:
            logger.error('Workflow not found!')  # not expected
        elif state.runtime_status.name == 'COMPLETED':
            logger.info(f'Workflow completed! Result: {state.serialized_output}')
            return json.dumps({'success': True}), 200, {'ContentType': 'application/json'}
        else:
            logger.error(f'Workflow failed! Status: {state.runtime_status.name}')  # not expected
    except TimeoutError as e:
        logger.exception('*** Workflow timed out!', exc_info=e)

    return json.dumps({'success': False}), 500, {'ContentType': 'application/json'}

@wfr.workflow(name='process_media_workflow')
def process_media_workflow(ctx: wf.DaprWorkflowContext, data: any):
    with DaprClient() as client:
        logger.debug(f'calling activity a')
        yield ctx.call_activity(a, input=None)
        logger.debug(f'calling activity b')
        yield ctx.call_activity(b, input=None)
        logger.debug(f'calling activity c')
        yield ctx.call_activity(c, input=None)

@wfr.activity(name='a')
async def a(ctx: wf.DaprWorkflowContext, data: any):
    return data

@wfr.activity(name='b')
async def b(ctx: wf.DaprWorkflowContext, data: any):
    return data

@wfr.activity(name='c')
async def c(ctx: wf.DaprWorkflowContext, data: any):
    return data

```

**Comment by guybartal** [comment]
my bad, forgot to start the workflow using `wfr.start()`
