### ISSUE TITLE
dapr init failed

### ISSUE THREAD

**Issue by xfab-hari** [dapr/dapr#8336]
## In what area(s)?

/area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

## What version of Dapr?
CLI version: 1.14.1
Runtime version: n/a

> 1.14.1

## Expected Behavior

`dapr init` 
should initialize the dapr components and the operation itself should be successful

## Actual Behavior

the output dump: 

```
dapr init                                                                                                                                                                      ─╯
⌛  Making the jump to hyperspace...
ℹ️  Container images will be pulled from Docker Hub
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x101ec1b14]

goroutine 1 [running]:
github.com/hashicorp/go-version.(*Version).String(0x0)
	/Users/runner/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/hashicorp/go-version@v1.6.0/version.go:369 +0x34
github.com/hashicorp/go-version.(*Version).Compare(0x0, 0x14000696000)
	/Users/runner/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/hashicorp/go-version@v1.6.0/version.go:116 +0x24
github.com/hashicorp/go-version.(*Version).GreaterThan(...)
	/Users/runner/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/hashicorp/go-version@v1.6.0/version.go:298
github.com/dapr/cli/pkg/version.GetLatestReleaseGithub.func1({0x14000998000, 0x35f6f3, 0x41e000})
	/private/tmp/dapr-cli-20240819-5654-e4cfq9/cli-1.14.1/pkg/version/version.go:124 +0x1c8
github.com/dapr/cli/pkg/version.GetVersionFromURL({0x1400062c090, 0x2f}, 0x102ccdb28)
	/private/tmp/dapr-cli-20240819-5654-e4cfq9/cli-1.14.1/pkg/version/version.go:102 +0x350
github.com/dapr/cli/pkg/version.GetLatestReleaseGithub({0x1400062c090?, 0x2b?})
	/private/tmp/dapr-cli-20240819-5654-e4cfq9/cli-1.14.1/pkg/version/version.go:107 +0x28
github.com/dapr/cli/pkg/version.GetDaprVersion()
	/private/tmp/dapr-cli-20240819-5654-e4cfq9/cli-1.14.1/pkg/version/version.go:63 +0x60
github.com/dapr/cli/pkg/standalone.Init({0x1022ebc59, 0x6}, {0x1022ebc59, 0x6}, {0x0, 0x0}, 0x0, {0x0, 0x0}, {0x0, ...}, ...)
	/private/tmp/dapr-cli-20240819-5654-e4cfq9/cli-1.14.1/pkg/standalone/standalone.go:215 +0x1b8
github.com/dapr/cli/cmd.init.func23(0x10401d3e0, {0x1022e8de4?, 0x4?, 0x1022e8eac?})
	/private/tmp/dapr-cli-20240819-5654-e4cfq9/cli-1.14.1/cmd/init.go:174 +0x2e8
github.com/spf13/cobra.(*Command).execute(0x10401d3e0, {0x104079c00, 0x0, 0x0})
	/Users/runner/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0x81c
github.com/spf13/cobra.(*Command).ExecuteC(0x10401ae80)
	/Users/runner/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/runner/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/dapr/cli/cmd.Execute({0x102669f40?, 0x100a6043c?}, {0x102669f3c?, 0x140000021c0?})
	/private/tmp/dapr-cli-20240819-5654-e4cfq9/cli-1.14.1/cmd/dapr.go:78 +0x150
main.main()
	/private/tmp/dapr-cli-20240819-5654-e4cfq9/cli-1.14.1/main.go:27 +0x3c
```

## Steps to Reproduce the Problem

- install dapr (Mac M2 Pro)
`arch -arm64 brew install dapr/tap/dapr-cli` 
- launch `docker`
- `dapr init`

## Release Note

RELEASE NOTE:

**Comment by yaron2** [comment]
Fixed

**Comment by TimothyHarrelson** [comment]
What is the fix for this and how do I acquire it? I am on the same version and am still encountering this issue on Windows 10. The issue persists across multiple versions and computer restarts. 

Is there a workaround? My dapr had been working on this environment without any changes for weeks before this.

**Comment by yaron2** [comment]
> What is the fix for this and how do I acquire it? I am on the same version and am still encountering this issue on Windows 10. The issue persists across multiple versions and computer restarts.
> 
> Is there a workaround? My dapr had been working on this environment without any changes for weeks before this.

Should be fixed now. We need to disable something in our build system that causes this
